// Semilla generada desde los Excels de memorias descriptivas.
// Se usa solo para precargar el MVP cuando una obra activa coincide por codigo.
export const MEMORIA_EXCEL_SEED = {
  "H161": {
    "propietario": "Ariel Dobiega",
    "motorizacion": "Volvo Diesel 300 HP",
    "color_casco": "Azul oscuro (como 7 Bravo), bandas, toma de aire y contorno de techo",
    "madera_muebles": "Roble Tinte Rayado",
    "piso": "La Europea White",
    "color_mesadas": "Negro",
    "grupo_electrogeno": "Si",
    "aire_acondicionado": true,
    "calefactor": true,
    "bow_thruster": true,
    "fabricadora_hielo": true,
    "teca_tipo": "X / Infinity gris",
    "adicionales": "Red en barandas",
    "tapiceria_mamparos": "Cerramiento / Negro",
    "color_acolchados": "Interdiseño Bhanu 01"
  },
  "H163": {
    "propietario": "Federico",
    "motorizacion": "Volvo Diesel 320 HP",
    "color_casco": "Blanco",
    "madera_muebles": "Gris Terso",
    "piso": "La Europea White",
    "color_mesadas": "Dekton Entzo Natural",
    "grupo_electrogeno": "Si / Coldmaster",
    "aire_acondicionado": true,
    "calefactor": true,
    "bow_thruster": true,
    "fabricadora_hielo": true,
    "teca_tipo": "X / Infinity gris c/rayas negras",
    "adicionales": "Seadek gris con rayas negras en planchada",
    "audio": "Red en baranda",
    "alfombra": "Bacha blanca en baño",
    "tapiceria_mamparos": "Cerramiento / Negro",
    "color_acolchados": "Shani 07"
  },
  "H164": {
    "propietario": "GERMAN",
    "motorizacion": "Volvo Diesel 300 HP",
    "color_casco": "Blanco",
    "color_mesadas": "Negro",
    "fabricadora_hielo": "Plotter:",
    "tapiceria_mamparos": "Cerramiento / CHARCOAL CON MOSQUITERO",
    "color_acolchados": "BHANU 01",
    "adicionales": "4 PARLANTES EN COCKPIT DE 6,5"
  },
  "H165": {
    "propietario": "Gabriel",
    "motorizacion": "Volvo Diesel 300 HP",
    "madera_muebles": "Gris terso",
    "color_mesadas": "Purastone color Dessert black mate",
    "grupo_electrogeno": "No",
    "aire_acondicionado": false,
    "calefactor": false,
    "bow_thruster": false,
    "fabricadora_hielo": false,
    "teca_tipo": "Si / Infinity gris c/rayas",
    "tapiceria_mamparos": "Cerramiento / Negro",
    "color_acolchados": "Shani 07",
    "adicionales": "Consola pintada de negro",
    "piso": "RED Baranda"
  },
  "H166": {
    "motorizacion": "Volvo Diesel 300 HP",
    "color_casco": "Pintar banda Gris, color Marbella",
    "color_mesadas": "Purastone Aria Pulido",
    "grupo_electrogeno": "Si / CooldMaster",
    "aire_acondicionado": true,
    "teca_tipo": "No",
    "audio": "No",
    "tapiceria_mamparos": "Cerramiento / Negro",
    "color_acolchados": "Almohadones grandes:",
    "adicionales": "Toma 12v tipo encendedor en el tacho de popa"
  },
  "H167": {
    "propietario": "JOSÉ LUIS",
    "motorizacion": "Volvo 320",
    "madera_muebles": "Nogal (Poro cerrado)",
    "color_mesadas": "Dekton entzo natural",
    "grupo_electrogeno": "Si / CooldMaster",
    "aire_acondicionado": true,
    "audio": "No / A CONFIRMAR CON GUSTAVO",
    "tapiceria_mamparos": "Cerramiento / Negro",
    "color_acolchados": "Samsara 01",
    "adicionales": "Techo HT y consola pintado de negro",
    "alfombra": "Bacha blanca en baño (Bacha De Baño Linea Sofy Color Blanco 27.5 X 10 Cm - Daccord)",
    "piso": "Mesa de cockpit de madera"
  },
  "H168": {
    "propietario": "Diego",
    "motorizacion": "Volvo 300",
    "color_casco": "Gris",
    "madera_muebles": "Roble Americano",
    "piso": "Macchia Vecchia",
    "color_mesadas": "Macchia Vecchia",
    "grupo_electrogeno": "Si / Onan 4Kva",
    "aire_acondicionado": "Si / Webasto",
    "teca_tipo": "No",
    "audio": "Si",
    "starlink": true,
    "tapiceria_mamparos": "Cerramiento / Negro",
    "color_acolchados": "Samsahara",
    "adicionales": "Volante Ferrara (Foto)"
  },
  "H169": {
    "propietario": "Armando",
    "motorizacion": "Volvo 300",
    "color_casco": "Muestra Gris (64-18)",
    "madera_muebles": "Nogal",
    "piso": "Infinity N°4 Gris Claro",
    "color_mesadas": "Purastone Travertino Navona",
    "grupo_electrogeno": "Si / Coldmaster",
    "aire_acondicionado": false,
    "teca_tipo": "No",
    "audio": "Si / STANDART",
    "starlink": true,
    "tapiceria_mamparos": "Cerramiento",
    "color_acolchados": "Bortice Liso",
    "adicionales": "Mueble con Parrilla (Gustavo confirma el modelo)"
  },
  "H170": {
    "propietario": "Ezequiel Catani",
    "motorizacion": "Techo:",
    "piso": "OFXP 452-13",
    "color_mesadas": "purastone Aria Pulido",
    "grupo_electrogeno": "Si",
    "aire_acondicionado": true,
    "calefactor": true,
    "bow_thruster": true,
    "fabricadora_hielo": true,
    "tapiceria_mamparos": "Bandeau / Pranna Gris Medio",
    "color_acolchados": "VER",
    "adicionales": "Parrilla en Planchada Confort Nautica",
    "starlink": "3 Luces bajo Planchada Blancas"
  },
  "H171": {
    "propietario": "Marcelo Coria",
    "motorizacion": "Volvo Diesel 300 HP",
    "color_casco": "Blanco",
    "madera_muebles": "Nocce Milano",
    "piso": "OFXP 452-13.",
    "color_mesadas": "Travertino Navona",
    "grupo_electrogeno": "No / Sleeper 6KvA",
    "aire_acondicionado": "No / COLDMASTER",
    "calefactor": false,
    "bow_thruster": false,
    "fabricadora_hielo": "Si / Frente de inoxidable",
    "tapiceria_mamparos": "Cerramiento / Charcoal Grey",
    "color_acolchados": "Bortice color 1",
    "adicionales": "Llevará Carpa",
    "starlink": "Gps Tactil 9´´ Garmin"
  },
  "H172": {
    "propietario": "Jorge",
    "motorizacion": "Volvo 320",
    "madera_muebles": "Nogal (Poro cerrado)",
    "color_mesadas": "Dekton entzo natural",
    "grupo_electrogeno": "Si / CooldMaster",
    "aire_acondicionado": true,
    "audio": "Si / Detalle abajo",
    "tapiceria_mamparos": "Cerramiento / Negro",
    "color_acolchados": "Samsara 01",
    "adicionales": "Techo HT y consola pintado de negro",
    "alfombra": "Bacha blanca en baño (Bacha De Baño Linea Sofy Color Blanco 27.5 X 10 Cm - Daccord)",
    "piso": "Mesa de cockpit de madera"
  },
  "H173": {
    "propietario": "Aldo Donzis",
    "motorizacion": "Volvo diesel 300",
    "madera_muebles": "Nogal Italiano Rayado",
    "piso": "OFXP 452-13",
    "color_mesadas": "Purastone Aria 25 Pulido",
    "fabricadora_hielo": "Plotter:",
    "tapiceria_mamparos": "Cerramiento / Negro Con Mosquitero",
    "color_acolchados": "Anila 01",
    "adicionales": "Mueble con Parrilla"
  },
  "H174": {
    "motorizacion": "Techo:",
    "madera_muebles": "Melamina Camellia",
    "fabricadora_hielo": "Plotter:",
    "teca_tipo": "TV en camarote popa:",
    "tapiceria_mamparos": "Cerramiento",
    "color_acolchados": "Almohadones grandes:"
  },
  "H175": {
    "motorizacion": "Techo:",
    "fabricadora_hielo": "Plotter:",
    "teca_tipo": "TV en camarote popa:",
    "tapiceria_mamparos": "Cerramiento",
    "color_acolchados": "Almohadones grandes:"
  },
  "37-21": {
    "propietario": "Dario Rosenthal",
    "cabina": "Soft-Top",
    "motorizacion": "2 x Mercury 450 HP Fuera de borda, nafta",
    "color_casco": "Blanco",
    "madera_muebles": "Gris Terso",
    "piso": "La Europea White",
    "color_mesadas": "Cocina y baño: Olimpo, Cockpit: Niagara Pulido",
    "audio": "Mesa de cockpit",
    "color_cerramientos": "Negro c/mosquiteros",
    "color_acolchados": "Shani 07",
    "tapiceria_mamparos": "Hielo",
    "adicionales": "Nombre con LED RGB \"ROZEN\" (va el que se sacó del 43-9)",
    "aire_acondicionado": "Ver si se puede hacer lugar de guarda bajo escalera, cajones o algo asi"
  },
  "37-22": {
    "propietario": "Ariel",
    "audio": "Mesa de cockpit",
    "tapiceria_mamparos": "Color exterior",
    "adicionales": "4 luces bajo agua blancas"
  },
  "37-23": {
    "propietario": "Gustavo Borrajo",
    "color_mesadas": "Baño cockpit Niagara; Cocina Olimpo",
    "teca_tipo": "Si",
    "sternthruster": true,
    "starlink": true,
    "audio": "Cotizar, detalle abajo",
    "color_acolchados": "Anila 01",
    "tapiceria_mamparos": "Color exterior / Gris claro con pranna Gris Oscuro",
    "adicionales": "2 Parlantes Proa, 4 parlantes cockpit, 1 subwoofer, potencia"
  },
  "37-24": {
    "propietario": "Mariano",
    "motorizacion": "Volvo 320 VDRIVE",
    "color_mesadas": "Dekton Olimpo",
    "grupo_electrogeno": "Si",
    "teca_tipo": "Si",
    "starlink": true,
    "audio": "Mesa de cockpit / Si",
    "color_cerramientos": "Negro",
    "color_acolchados": "Shani 03",
    "tapiceria_mamparos": "Hielo",
    "adicionales": "Luces de cortesia blancas"
  },
  "37-25": {
    "propietario": "Pires",
    "cabina": "Soft-Top",
    "motorizacion": "2 x Mercury 270 HP",
    "color_casco": "Blanco",
    "madera_muebles": "Gris Terso",
    "piso": "Valvi Floor 6spc1010-5 (Es el primero del muestrario)",
    "color_mesadas": "Cocina y baño: Limestone / Cockpit: Dekton Kira Natural",
    "grupo_electrogeno": "Si / Mase 6,05i",
    "teca_tipo": "No / Quiere Poner seadeck pero por ahora lo resuelve el cliente",
    "sternthruster": false,
    "starlink": true,
    "electronica": "Si",
    "radar": false,
    "audio": "Si / Fusion (detalle abajo)",
    "fabricadora_hielo": "No / Va heladera c/freezer 12v Dometic CRX50",
    "color_cerramientos": "Negro. Mosquitero enrollable en popa y proa solo babor",
    "color_acolchados": "Pranna 02",
    "tapiceria_mamparos": "Hielo",
    "adicionales": "Heladera interior 12v, ver modelo que se instalo en 42-76",
    "calefactor": "1 Toma 220v doble bajo mesa de cockpit y otro a popa del parlante de babor (Cambre Linea Bauhaus)"
  },
  "37-26": {
    "propietario": "Hernan Filoposky",
    "motorizacion": "1xVolvo D6-380 HP",
    "madera_muebles": "Gris Terso",
    "piso": "Corian o Similar, Int: Blanco; Ext: Negro",
    "color_mesadas": "Corian o Similar, Int: Blanco; Ext: Negro",
    "grupo_electrogeno": "No",
    "teca_tipo": "Si / Infinity Gris oscuro",
    "sternthruster": true,
    "starlink": true,
    "electronica": "No",
    "radar": true,
    "audio": "No / 2 Juego Parlantes Blancos Clasicos de 8,8 Signature 3i (cockpit y planchada)\n1 Subwoofer 10´´ Signature 3 Blanco Clasico\n1 Control a distancia Inalámbrico Fusion ARX \n1 Estereo Fusion MS-RA60 Marine Stereo",
    "color_acolchados": "Bhanu 01",
    "tapiceria_mamparos": "Hielo",
    "adicionales": "Sin Parrilla (Conserva la luz y el toma)"
  },
  "37-27": {
    "propietario": "Eduardo Pascarelli",
    "cabina": "Soft-Top",
    "motorizacion": "Volvo 440 c/Pata",
    "color_casco": "Blanco",
    "madera_muebles": "Gris Terso",
    "piso": "La Europea White",
    "color_mesadas": "Baño y Cockpit: Puraprima / Cocina: Macchia Vecchia Pulido",
    "grupo_electrogeno": "Si / Mase 6.05",
    "teca_tipo": "Si / Infinity el mas blanco \"10\"",
    "sternthruster": true,
    "starlink": true,
    "electronica": "No",
    "radar": true,
    "audio": "No / Estandar",
    "fabricadora_hielo": "X / Va helader 12v, ver reforma en mueble (Trae cliente)",
    "color_cerramientos": "Negro: Mosquitero popa enrollable y proa medio circulo",
    "color_acolchados": "Sohan 01 (Proa) Oishi 01(Popa- Cama Grande)\nCama popa Unida y lugar de guarda (3 almohadas y almohadones)",
    "tapiceria_mamparos": "Hielo",
    "adicionales": "Patas mesa Int y EXT (Trae el cliente)"
  },
  "37-28": {
    "propietario": "José",
    "constructor": "Maximiliano Cornejo",
    "cabina": "Soft-Top",
    "motorizacion": "2xVolvo D3-270 HP",
    "color_casco": "PEU EPE910",
    "madera_muebles": "Gris Terso",
    "piso": "LA EUROPEA WHITE RSSPC00400",
    "color_mesadas": "Purastone Aria Pulido",
    "grupo_electrogeno": "No / Maze 6kva",
    "teca_tipo": "No",
    "sternthruster": false,
    "starlink": true,
    "electronica": "No",
    "radar": false,
    "audio": "No",
    "fabricadora_hielo": true,
    "color_acolchados": "Bhanu 01",
    "tapiceria_mamparos": "Color exterior",
    "adicionales": "GRIFERÍAS NEGRAS\nBaño: FV Epuyén 0206/L2 color negra\nCocina: Fv Epuyen Monocomando Negro 411.04/l2 Color Negro\nAccesorios: Fv Epuyen L2 Ng 166(3 Unidades) y 167 Negro"
  },
  "37-29": {
    "propietario": "Luciano",
    "constructor": "Dionisio centuriòn",
    "cabina": "Soft-Top",
    "motorizacion": "2 x Mercury 270 HP",
    "color_casco": "Blanco",
    "madera_muebles": "Gris terso",
    "piso": "La Europea White",
    "color_mesadas": "Baño Niagara; Cocina: Olimpo; Cockpit Negro Marquina (Adicional)",
    "grupo_electrogeno": "Si / Mase 6kva",
    "teca_tipo": "Si / Gris",
    "sternthruster": true,
    "starlink": true,
    "electronica": "Si",
    "radar": true,
    "audio": "Si / Estándar",
    "fabricadora_hielo": true,
    "color_cerramientos": "Negro",
    "color_acolchados": "shani 07",
    "tapiceria_mamparos": "Hielo"
  },
  "37-30": {
    "propietario": "Agustin Trosman",
    "constructor": "Roberto Gonzalez",
    "motorizacion": "2xVolvo D3-270 HP",
    "madera_muebles": "Nogal Italiano Rayado",
    "piso": "Europea Nature Alamo",
    "color_mesadas": "Prima travertino navona",
    "grupo_electrogeno": "Si / Onan 6 kva",
    "teca_tipo": "No",
    "sternthruster": true,
    "starlink": true,
    "electronica": "No",
    "radar": true,
    "audio": "No / Estandar",
    "fabricadora_hielo": true,
    "color_cerramientos": "Charcoal",
    "tapiceria_mamparos": "Hielo",
    "adicionales": "Ver sillon mas grande (Curvo)"
  },
  "37-31": {
    "propietario": "Mario donzis",
    "constructor": "Maximiliano Cornejo",
    "motorizacion": "2xVolvo D3-270 HP",
    "madera_muebles": "Nogal Italiano Rayado",
    "piso": "OFXP 452-13",
    "color_mesadas": "Purastone Ora Gold (Negro Marquina en el exterior y mesada de baño)",
    "grupo_electrogeno": "Si / Kohler 7KVA",
    "teca_tipo": "Si / Infinity Gris Claro",
    "electronica": "Si",
    "audio": "Mesa de cockpit / Si",
    "color_cerramientos": "NEGRO",
    "tapiceria_mamparos": "Hielo",
    "adicionales": "Inverter de la marca Victron"
  },
  "37-32": {
    "propietario": "Mauro Yacht",
    "constructor": "Dionicio Centurion",
    "motorizacion": "2xVolvo D3-270 HP",
    "madera_muebles": "Nocce Milano (Melamina)",
    "piso": "Europea Cream",
    "color_mesadas": "Purastone Aria 25 Pulido",
    "grupo_electrogeno": "Si / Onan 6 kva",
    "teca_tipo": "Si / Infinity Gris",
    "sternthruster": false,
    "starlink": true,
    "electronica": "No / con Joystick (Trae Cliente)",
    "radar": false,
    "audio": "No",
    "fabricadora_hielo": true,
    "color_acolchados": "Interdiseño Lina Folk 09 Blanco",
    "tapiceria_mamparos": "Hielo Alplast",
    "adicionales": "Cuenta Cadena"
  },
  "37-33": {
    "propietario": "Juan Carlos",
    "motorizacion": "2xVolvo D3-270 HP",
    "madera_muebles": "Roble Tinte Rayado",
    "piso": "OFXP 452-13",
    "color_mesadas": "Purastone Aria 25 Pulido",
    "grupo_electrogeno": "Grupo de Folino 10Kva (Trae Cliente)",
    "teca_tipo": "Si / Teka",
    "starlink": true,
    "audio": "Si / Detalle Abajo",
    "fabricadora_hielo": "Si / IM-130 Smart-Tek (Trajo Cliente)",
    "color_cerramientos": "(Cerramiento de papa hasta atras de parrilla)",
    "color_acolchados": "Ver",
    "tapiceria_mamparos": "Hielo Alplast"
  },
  "37-34": {
    "propietario": "Christian Muller",
    "motorizacion": "2 x Mercury 270 HP",
    "madera_muebles": "Nocce Milano(Melamina)",
    "piso": "Europea Cream",
    "color_mesadas": "Baño y Cocina; Purastone Aria 25 Pulido",
    "grupo_electrogeno": "Maze",
    "teca_tipo": "Infinity simil teca",
    "audio": "Mesa de cockpit",
    "tapiceria_mamparos": "Interior / Capra Perla",
    "color_acolchados": "Anila 01"
  },
  "37-35": {
    "propietario": "Mariano/Ariel",
    "motorizacion": "Volvo 400",
    "madera_muebles": "Nogal Italiano Rayado",
    "piso": "Europea Nature Alamo",
    "color_mesadas": "Prima travertino navona",
    "grupo_electrogeno": "Si",
    "teca_tipo": "No",
    "sternthruster": false,
    "starlink": true,
    "electronica": "No",
    "radar": false,
    "audio": "No",
    "fabricadora_hielo": false,
    "tapiceria_mamparos": "Interior / Capra Perla",
    "color_acolchados": "Anila 01"
  },
  "37-36": {
    "propietario": "Alberto Moltrasi",
    "constructor": "Roberto Gonzalez",
    "madera_muebles": "Nogal Italiano rayado",
    "piso": "Europea Nature Alamo",
    "grupo_electrogeno": "No",
    "teca_tipo": "No",
    "sternthruster": false,
    "starlink": false,
    "electronica": "No",
    "radar": false,
    "audio": "No",
    "fabricadora_hielo": false,
    "tapiceria_mamparos": "Color exterior"
  },
  "37-37": {
    "propietario": "Fran Recio",
    "constructor": "Maximiliano Cornejo",
    "grupo_electrogeno": "No",
    "teca_tipo": "No",
    "sternthruster": false,
    "starlink": false,
    "electronica": "No",
    "radar": false,
    "audio": "No",
    "fabricadora_hielo": false,
    "tapiceria_mamparos": "Color exterior"
  },
  "37-38": {
    "grupo_electrogeno": "No",
    "teca_tipo": "No",
    "sternthruster": false,
    "starlink": false,
    "electronica": "No",
    "radar": false,
    "audio": "No",
    "fabricadora_hielo": false,
    "tapiceria_mamparos": "Color exterior"
  },
  "37-39": {
    "propietario": "Martín Hojman",
    "grupo_electrogeno": "No",
    "teca_tipo": "No",
    "sternthruster": false,
    "starlink": false,
    "electronica": "No",
    "radar": false,
    "audio": "No",
    "fabricadora_hielo": false,
    "tapiceria_mamparos": "Color exterior"
  },
  "37-40": {
    "propietario": "Guillermo Gaudino",
    "grupo_electrogeno": "No",
    "teca_tipo": "No",
    "sternthruster": false,
    "starlink": false,
    "electronica": "No",
    "radar": false,
    "audio": "No",
    "fabricadora_hielo": false,
    "tapiceria_mamparos": "Color exterior"
  },
  "37-41": {
    "propietario": "German",
    "motorizacion": "2 Mercury 270",
    "grupo_electrogeno": "No",
    "teca_tipo": "No",
    "sternthruster": false,
    "starlink": false,
    "electronica": "No",
    "radar": false,
    "audio": "No",
    "fabricadora_hielo": false,
    "tapiceria_mamparos": "Color exterior"
  },
  "37-42": {
    "propietario": "Luciano Barelini",
    "cabina": "Soft-Top",
    "motorizacion": "Iveco 400 Línea eje",
    "madera_muebles": "Roble Plata Rayado",
    "grupo_electrogeno": "No",
    "teca_tipo": "No",
    "sternthruster": false,
    "starlink": false,
    "electronica": "No",
    "radar": false,
    "audio": "No",
    "fabricadora_hielo": false,
    "tapiceria_mamparos": "Color exterior"
  },
  "37-43": {
    "audio": "Nª de barco",
    "cabina": "Soft-Top",
    "motorizacion": "2 Mercury Verado 400 F.B.",
    "madera_muebles": "Nogal Italiano Rayado",
    "piso": "Europea Alamo",
    "color_mesadas": "Bañ y Coc: Travertino Navona Cockpit: Desert Black",
    "teca_tipo": "No",
    "grupo_electrogeno": "No",
    "sternthruster": false,
    "electronica": "No",
    "radar": false,
    "fabricadora_hielo": false,
    "color_cerramientos": "Negro",
    "color_acolchados": "Anila 01",
    "tapiceria_mamparos": "Color exterior / Vertigo Gris Claro",
    "adicionales": "Griferias Negras"
  },
  "37-44": {
    "propietario": "Juan",
    "cabina": "Soft-Top",
    "motorizacion": "Iveco 400 L.E",
    "madera_muebles": "Roble Plata Rayado",
    "piso": "Europea Spc foster Maple",
    "electronica": "Ver Plotter más grande",
    "radar": false,
    "audio": "No",
    "sternthruster": false,
    "teca_tipo": "No",
    "tapiceria_mamparos": "Color exterior / Vértigo blanco con vivos chocolate",
    "adicionales": "Grifería Negra (Buscar modelo)\nBacha Negra (Buscar Modelo) / Cocina"
  },
  "42-75": {
    "propietario": "Mariano Pico",
    "cabina": "Open",
    "motorizacion": "2xIVECO 450 hp",
    "color_casco": "Blanco",
    "madera_muebles": "Gris Terso",
    "color_mesadas": "Dekton Olimpo",
    "grupo_electrogeno": "Si / Kohler 7kva",
    "teca_tipo": "Si",
    "pluma": true,
    "sternthruster": true,
    "starlink": "Garmin",
    "electronica": "Si / Garmin",
    "radar": true,
    "audio": "Si / Fusion, detalle abajo",
    "fabricadora_hielo": true,
    "color_cerramientos": "Negro",
    "color_acolchados": "Shani 06",
    "alfombra": "Luces calidas"
  },
  "42-76": {
    "propietario": "Pires",
    "cabina": "Hard Top",
    "motorizacion": "2xIVECO 400 hp",
    "color_mesadas": "Todo Olimpo - Cockpit Gris",
    "grupo_electrogeno": "Si / Kohler 9Kva",
    "teca_tipo": "Si / Pasillos NO",
    "starlink": true,
    "audio": "Si / Cotizar en JL Y Fusion (Detalle de unidades abajo)*",
    "fabricadora_hielo": "Si / Freezer 12v",
    "color_acolchados": "Shani 06",
    "adicionales": "Reforma baranda en proa y escalera para bajar a la playa. Tambien chapa que protege roda. Hace todo Gollino, ya lo pidio Gustavo",
    "calefactor": "Carpa beige o clara"
  },
  "42-77": {
    "propietario": "Sebastian Ferreyra",
    "cabina": "ST",
    "motorizacion": "Volvo 440",
    "madera_muebles": "Roble Tinte Rallado",
    "piso": "PURASTONE ARIA PULIDO",
    "color_mesadas": "PURASTONE ARIA PULIDO",
    "grupo_electrogeno": "kOHLER 7 kva",
    "pluma": true,
    "starlink": "Simrad",
    "electronica": "Simrad",
    "audio": "Si",
    "color_cerramientos": "Charcoal",
    "color_acolchados": "Shani 06",
    "adicionales": "4 Parlantes en cockpit, 2 de proa, subwoofer y potencia Todo XS"
  },
  "42-78": {
    "propietario": "Ariel Bertino",
    "cabina": "Softop",
    "motorizacion": "Volvo 440",
    "color_casco": "Blanco",
    "madera_muebles": "Nogal Rayado",
    "piso": "Orbis FLOOR OFxp 452-13",
    "color_mesadas": "Purastone Macchia Vecchia - (Cockpit: Krion Gris Estandar)",
    "grupo_electrogeno": "Si / Kohler 7Kva",
    "teca_tipo": "Si / Infinity Gris Claro",
    "pluma": true,
    "sternthruster": true,
    "starlink": true,
    "electronica": "Si",
    "radar": "Si / Garmin 24xblanco",
    "audio": "Si",
    "fabricadora_hielo": "Si / Ver medidas para poner otro modelo",
    "color_acolchados": "Color paneles salon / Hielo",
    "tapiceria_mamparos": "Hielo",
    "adicionales": "Lateral de cocina hacia proa en dekton - Purastone Macchia Vecchia"
  },
  "42-79": {
    "propietario": "Daniel Casabe",
    "constructor": "FELICIANO",
    "motorizacion": "Iveco 400",
    "madera_muebles": "Nogal Poro Cerrado",
    "piso": "OXF 452-13",
    "color_mesadas": "Baño: Negro Marquina Cocina: Macchia Vecchia",
    "grupo_electrogeno": "Si / Onan 6 kva",
    "teca_tipo": "No",
    "pluma": false,
    "sternthruster": true,
    "starlink": "Plotter Garmin",
    "electronica": "Si / Plotter Garmin",
    "radar": false,
    "audio": "Si",
    "fabricadora_hielo": "Si / Tipo U-line",
    "color_acolchados": "Color paneles salon",
    "tapiceria_mamparos": "Color exterior / Vertigo Blanco con Hilo Chocolate",
    "adicionales": "Almohadon en tapa de parrilla",
    "color_cerramientos": "Cava Philco Phcav08n2 8 Botellas"
  },
  "42-80": {
    "propietario": "Eduardo Salis",
    "constructor": "Feliciano Centurion",
    "motorizacion": "Iveco 400",
    "color_casco": "Blanco",
    "madera_muebles": "Nogal Italiano Rayado",
    "piso": "OFXP 452-13",
    "color_mesadas": "Cocina; Macchia Vecchia - Baño; Negro Marquina",
    "grupo_electrogeno": "Si / Kholer 7 kva",
    "teca_tipo": "No",
    "pluma": true,
    "sternthruster": true,
    "starlink": true,
    "electronica": "No",
    "radar": true,
    "audio": "Si",
    "fabricadora_hielo": true,
    "color_cerramientos": "Charcoal",
    "color_acolchados": "Color paneles salon / Hielo",
    "tapiceria_mamparos": "Techo Hueso, Mamparo Hielo",
    "adicionales": "2 Juego Parlantes 6,5 xs\n 1 Subwoofer 10´´ xs\n 1 Juego baranda 6,5 xs\n Potencia 5 o 6 cananales\n Estereo 210"
  },
  "42-81": {
    "propietario": "Ezequiel",
    "motorizacion": "Iveco 400",
    "color_casco": "Franja en casco y parte en arco Gris Plomo",
    "madera_muebles": "Nogal Italiano Rayado",
    "piso": "Europea Nature Alamo",
    "color_mesadas": "Cocina: Bianco Lasa / Baño: Travertino Navona / Exterior a definir",
    "grupo_electrogeno": "Si / (Mas Grande)",
    "teca_tipo": "Si / Infinity ( A confirmar )",
    "pluma": true,
    "sternthruster": true,
    "starlink": true,
    "electronica": "No",
    "radar": false,
    "audio": "No",
    "fabricadora_hielo": true,
    "color_acolchados": "Anila 01"
  },
  "42-82": {
    "propietario": "Santiago",
    "constructor": "Damian. R",
    "motorizacion": "Iveco 450",
    "madera_muebles": "Roble Plata Rayado",
    "piso": "La Europea White",
    "color_mesadas": "Purastone Travertino Navona",
    "grupo_electrogeno": "No",
    "teca_tipo": "Si / Infinity gris",
    "pluma": false,
    "sternthruster": "Si / Joystick doble",
    "electronica": "Si / Garmin",
    "radar": false,
    "audio": "No",
    "fabricadora_hielo": false,
    "color_acolchados": "Anila 01",
    "tapiceria_mamparos": "Vértigo Gris claro",
    "adicionales": "Techo y arco ploteado de negro"
  },
  "43-21": {
    "propietario": "Maxi",
    "constructor": "Gabriel Ramirez",
    "motorizacion": "2xIVECO 450 hp",
    "color_casco": "Blanco",
    "madera_muebles": "Gris Terso",
    "piso": "La Europea White",
    "color_mesadas": "Cocina: Olimpo, Baños: Korso",
    "grupo_electrogeno": "Si / Onan 9,5 kva",
    "teca_tipo": "Si",
    "pluma": true,
    "sternthruster": true,
    "starlink": true,
    "radar": true,
    "audio": "Si / Fusion + JL, trajo el cliente. Detalle abajo",
    "fabricadora_hielo": true,
    "color_cerramientos": "Charcoal grey c/mosquitero y bimini",
    "color_acolchados": "Bhanu 01",
    "adicionales": "2 camaras: popa y proa"
  },
  "43-22": {
    "propietario": "Emiliano Cuoto",
    "motorizacion": "2xIVECO 450 hp",
    "color_casco": "Blanco",
    "madera_muebles": "Roble Tinte Rayado. Cocina pintada como 43-12",
    "piso": "OFXP 452-13",
    "color_mesadas": "Cocina: Dekton blanco brillante, Baños: Zenith Solid",
    "grupo_electrogeno": "No / Onan 9,5 kva",
    "teca_tipo": "Si",
    "pluma": true,
    "sternthruster": false,
    "starlink": true,
    "electronica": "No",
    "radar": true,
    "audio": "Si / Cotizar, detalle abajo",
    "fabricadora_hielo": true,
    "color_cerramientos": "Charcoal",
    "color_acolchados": "Interdiseño Anila 01",
    "adicionales": "Respaldo de comando inox"
  },
  "43-23": {
    "propietario": "Pilar",
    "motorizacion": "2xIVECO 450 hp",
    "color_casco": "Blanco",
    "madera_muebles": "Avorio Milan",
    "piso": "La Europea White",
    "color_mesadas": "Todo Dekton Olimpo",
    "grupo_electrogeno": "Si",
    "teca_tipo": "Si",
    "sternthruster": true,
    "starlink": true,
    "radar": true,
    "audio": "Si / Detalle abajo",
    "fabricadora_hielo": true,
    "color_cerramientos": "Cadet Grey",
    "color_acolchados": "Anila 01",
    "adicionales": "2 juegos parlantes 6,5\" xs, 2 parlantes baranda 6,5\", 1 potencias 6 canales, 1 estereo RA 210 todo con LED RGB (Todo Blanco)"
  },
  "43-24": {
    "propietario": "Mario Castelli",
    "motorizacion": "Iveco 450",
    "madera_muebles": "Milan Fumé",
    "piso": "1RSSPC00300",
    "color_mesadas": "Baño: Puraprima Aria Pulido\nCocina: Puraprima Blanco Zen Mate",
    "grupo_electrogeno": "Kholer 9 Kva",
    "pluma": "Si / Con cama",
    "sternthruster": true,
    "starlink": "Simrad NSX 3012",
    "electronica": "Si / Simrad NSX 3012",
    "radar": true,
    "audio": "Si",
    "color_cerramientos": "Charcoal",
    "color_acolchados": "Pana Horizonte Color 1",
    "adicionales": "Piloto automatico para plotter Simrad NSX 3012"
  },
  "43-25": {
    "propietario": "Alejandro Fredijedo",
    "constructor": "Damian Curatitoli",
    "motorizacion": "2xIVECO 570 hp",
    "madera_muebles": "Roble Tinte Rayado",
    "color_mesadas": "Baños: (Purastone) Aria Pulido / Cocina: Blanco ZEN Mate (Purastone)",
    "grupo_electrogeno": "Si / Kholer 9 Kva",
    "teca_tipo": "No",
    "pluma": false,
    "sternthruster": true,
    "starlink": "Si / Mini (Trae el Cliente)",
    "electronica": "No",
    "radar": false,
    "audio": "Si / Trae Cliente, Instala el tano",
    "fabricadora_hielo": true,
    "color_acolchados": "Anila 01",
    "adicionales": "Con Tender"
  },
  "43-26": {
    "propietario": "Ariel Sbdar",
    "motorizacion": "2xIVECO 450 hp",
    "color_casco": "Blanco",
    "madera_muebles": "Nogal",
    "piso": "OFXP 452-13",
    "color_mesadas": "Baños: Macchia Vecchia / Cocina: Blanco ZEN Mate (Purastone)",
    "grupo_electrogeno": "Si / Kholer 9 KVa",
    "teca_tipo": "No",
    "pluma": true,
    "sternthruster": true,
    "starlink": true,
    "electronica": "No",
    "radar": true,
    "audio": "Si",
    "fabricadora_hielo": true,
    "color_acolchados": "Color paneles / Hielo",
    "adicionales": "1 estereo Fusion RA-770\n\n4 juegos parlantes XS 6.5\" Classic blanco\n\n2 subwoofer XS 10\" Classic blanco\n\n1 juego parlantes c/soportes para baranda XS 6.5\" Sports negro\n\n2 potencias Alpine de 4 canales\n\n1 potencia Alpine de 6 canales\n\n1 Toldilla bimini en FLY"
  },
  "43-27": {
    "propietario": "Gaston Zabala",
    "constructor": "Gabriel Ramirez",
    "motorizacion": "450 Iveco",
    "madera_muebles": "Nogal Poro Abierto",
    "piso": "OFXPM 452-13 ORBIS FLOOR",
    "color_mesadas": "Baños y cocina: Purastone Ora Gold Pulido",
    "grupo_electrogeno": "Si / Onan 13,5 Kva",
    "teca_tipo": "Si",
    "pluma": "Parrillas Kenyon x2 (Trae el cliente)",
    "sternthruster": true,
    "starlink": "Garmin 16´´ 1623 xsv",
    "electronica": "Si / Garmin 16´´ 1623 xsv",
    "radar": "Caja Fuerte",
    "audio": "Si",
    "fabricadora_hielo": true,
    "color_cerramientos": "Charcoal ( Bimini, mosquitero para popa cockpit enrollable)",
    "color_acolchados": "Color paneles (Laterales Salon) / Liso Hermes Beige",
    "adicionales": "Duchador Rio en popa y en proa una canilla (ademas del que se pone habitualmente)"
  },
  "43-28": {
    "propietario": "Hugo Soria",
    "constructor": "Gabriel Ramirez",
    "motorizacion": "Iveco 450",
    "madera_muebles": "Nogal Poro Abierto",
    "piso": "OFXP 452-13",
    "color_mesadas": "Blanco ZEN Mate (Purastone)",
    "grupo_electrogeno": "Si / Kholer 9 KVa",
    "teca_tipo": "Si",
    "pluma": "x / No lleva",
    "sternthruster": true,
    "starlink": true,
    "electronica": "No / Garmin",
    "radar": false,
    "audio": "No",
    "fabricadora_hielo": true,
    "tapiceria_mamparos": "Interior / Rustico OIA Perla",
    "color_acolchados": "Bortice 01"
  },
  "43-29": {
    "propietario": "Stock",
    "constructor": "Gabriel Ramirez",
    "motorizacion": "Iveco 450",
    "madera_muebles": "Nogal",
    "piso": "Williamsburg, color beech",
    "color_mesadas": "Purastone Travertino Navona",
    "grupo_electrogeno": "No",
    "teca_tipo": "No",
    "pluma": false,
    "sternthruster": true,
    "starlink": false,
    "electronica": "No",
    "radar": false,
    "audio": "No",
    "fabricadora_hielo": false,
    "color_cerramientos": "Charcoal Grey",
    "color_acolchados": "Anila 01"
  },
  "43-30": {
    "propietario": "Pablo Zimmerman",
    "constructor": "Gabriel Ramirez",
    "motorizacion": "Iveco 450",
    "madera_muebles": "Chocolate Floreado",
    "grupo_electrogeno": "No",
    "teca_tipo": "No",
    "pluma": false,
    "sternthruster": false,
    "starlink": false,
    "electronica": "No",
    "radar": false,
    "audio": "No",
    "fabricadora_hielo": false,
    "color_acolchados": "Color paneles"
  },
  "52-9": {
    "propietario": "Daniel Dabah",
    "motorizacion": "2xIVECO 570 hp",
    "color_casco": "Blanco",
    "cabina": "HardTop",
    "madera_muebles": "NOGAL NATURAL PORO ABIERTO",
    "piso": "Simil Roble Americano",
    "alfombra": "EOS1",
    "color_mesadas": "Cocina y baños: Calacata Brillante Neolita. Cockpit: Dekton Negro Marquina",
    "sternthruster": "Antena de Directv",
    "audio": "Mesa de cockpit",
    "tapiceria_mamparos": "cuerina grevy fiore blanco bondeado",
    "color_acolchados": "sohan 01",
    "adicionales": "Mesa de cockpit con interior de calacata brillante neolith"
  },
  "52-10": {
    "propietario": "Lalo",
    "motorizacion": "2xIVECO 570 hp",
    "color_casco": "Blanco",
    "cabina": "SofTop",
    "madera_muebles": "Roble gris poro cerrado",
    "piso": "europea white",
    "alfombra": "espartano ht05",
    "color_mesadas": "Dekton olimpo stonika",
    "sternthruster": "Antena de Directv",
    "audio": "Mesa de cockpit",
    "tapiceria_mamparos": "alplast hielo",
    "color_acolchados": "bhanu 11",
    "adicionales": "dvd blue ray ?. NO CONSEGUIMOS NINGUNO CON PRECIO RAZONABLE"
  },
  "52-11": {
    "propietario": "Botbol",
    "motorizacion": "2xVOLVO 550 hp",
    "color_casco": "Blanco",
    "cabina": "hardtop",
    "madera_muebles": "Roble de milan fume poro cerrado",
    "piso": "48-c tambien en camarotes",
    "alfombra": "no",
    "color_mesadas": "baños y cocina dekton bergen stonika. Exterior dekton kira",
    "sternthruster": "Antena de Directv",
    "audio": "Mesa de cockpit",
    "tapiceria_mamparos": "jagger color ivory",
    "color_acolchados": "bhanu 01",
    "adicionales": "mesa de salon doble rusmar (ver sistema electrico en pañol)",
    "fabricadora_hielo": "luces bajo agua no bajo planchada"
  },
  "52-12": {
    "motorizacion": "2xVOLVO 550 hp",
    "color_casco": "Blanco",
    "cabina": "softop",
    "madera_muebles": "nogal",
    "piso": "ofxp 452-13 orbis floor - tambien en camarotes",
    "alfombra": "no lleva",
    "color_mesadas": "cocina: entzo natural, cockpit y baños:negro marquina",
    "sternthruster": "Antena de Directv",
    "audio": "Mesa de cockpit",
    "tapiceria_mamparos": "alplast hielo",
    "color_acolchados": "interdiseño shani 03",
    "adicionales": "sin tapa de parrilla pivoteante de mueble. Con marml encima y sin parrilla",
    "propietario": "capaz tiras tapizadas de cocina distintas, ojo"
  },
  "52-13": {
    "propietario": "52/13",
    "motorizacion": "2xIVECO 570 hp",
    "color_casco": "gris poliuretano ppg eft.74040",
    "cabina": "hardtop",
    "madera_muebles": "nogal poro abierto",
    "piso": "valvi floor 6spc6187-2",
    "alfombra": "PALLAS 190",
    "color_mesadas": "dekton olimpo completo",
    "sternthruster": "Antena de Directv",
    "audio": "Mesa de cockpit",
    "tapiceria_mamparos": "alplast hielo",
    "color_acolchados": "interdiseño shani 03",
    "adicionales": "LLEVA TENDER",
    "starlink": "heladera alta"
  },
  "52-14": {
    "propietario": "52/14",
    "motorizacion": "2xVOLVO 550 hp",
    "color_casco": "BLANCO",
    "cabina": "softop",
    "madera_muebles": "ROBLE DE MILAN FUME",
    "piso": "valvi floor 6spc6187-2",
    "alfombra": "velour plus",
    "color_mesadas": "baños y cockpit:dekton kelya natural. Cocina dekton kira natural.",
    "sternthruster": "Antena de Directv",
    "audio": "Mesa de cockpit",
    "tapiceria_mamparos": "JAGGER IGGORY",
    "color_acolchados": "bhanu 01",
    "adicionales": "TENDER OPACMARE TRAE EL CLIENTE",
    "starlink": "6 LUCES BAJO AGUA"
  },
  "52-15": {
    "motorizacion": "2xIVECO 570 hp",
    "cabina": "softop",
    "madera_muebles": "nogal por cerrado",
    "piso": "hard twist 01",
    "alfombra": "hard twist 01",
    "color_mesadas": "purastone ora gold barco completo",
    "sternthruster": "BAUL CORTO",
    "audio": "Mesa de cockpit",
    "tapiceria_mamparos": "ALPLAST HIELO",
    "adicionales": "NO LLEVA TENDERLIFT",
    "calefactor": "HELADERA CHICA + CAJON EN MUEBLE DE COCKPIT"
  },
  "52-16": {
    "propietario": "Fernando",
    "motorizacion": "2xIVECO 570 hp",
    "cabina": "softop",
    "madera_muebles": "NOGAL PORO ABIERTO",
    "piso": "ofxp 452-13 orbis floor - tambien en camarotes",
    "color_mesadas": "cocina: entzo natural, cockpit y baños:negro marquina",
    "grupo_electrogeno": "No / Kholer 9 Kva",
    "teca_tipo": "Si",
    "pluma": true,
    "sternthruster": false,
    "starlink": true,
    "electronica": "Si",
    "radar": true,
    "audio": "Si",
    "fabricadora_hielo": true,
    "tapiceria_mamparos": "alplast hielo",
    "color_acolchados": "interdiseño shani 03",
    "adicionales": "PLANCHADA 30 CM MAS LARGA? SOLO LA ZONA TENDERLIFT."
  },
  "52-8": {
    "propietario": "Mariano Calzonieri",
    "constructor": "Gustavo Fleitas",
    "motorizacion": "2 x IVECO 650 hp",
    "color_casco": "Blanco",
    "cabina": "Hard Top",
    "madera_muebles": "Roble gris Titanium - Calabria",
    "piso": "48-C",
    "alfombra": "EOS2",
    "color_mesadas": "Dekton Olimpo Stonika",
    "grupo_electrogeno": "Kholer 9 kva",
    "starlink": "Garmin",
    "electronica": "Garmin",
    "audio": "Fusion: Ver detalle abajo",
    "fabricadora_hielo": "U-line",
    "radar": "Encargar ?",
    "tapiceria_mamparos": "Gris focus",
    "color_acolchados": "Interdiseño Liso Bortice Color 1",
    "adicionales": "VAJILLERO de cockpit (que le ponemos)"
  },
  "52-17": {
    "propietario": "Diego Cimino",
    "constructor": "Damian Curatitoli",
    "motorizacion": "2 x IVECO 570 hp",
    "color_casco": "Blanco",
    "cabina": "SofTop exterior negro, int blanc",
    "madera_muebles": "Nogal",
    "piso": "OXFP 452-13 Orbis Floor",
    "grupo_electrogeno": "Kholer 9 kva",
    "audio": "MESA cockpit",
    "tapiceria_mamparos": "Alplast hielo",
    "color_acolchados": "??",
    "adicionales": "CAFETERA Nesspresso"
  },
  "52-18": {
    "propietario": "Ale Nico Caffaro",
    "constructor": "Gustavo Fleitas",
    "motorizacion": "2xIVECO 570 hp",
    "color_casco": "Blanco",
    "cabina": "SofTop Parantes Cachas negro",
    "madera_muebles": "Roble tinte rayado",
    "piso": "OXFP 452-13",
    "alfombra": "Pallas 190",
    "grupo_electrogeno": "Kholer 9 kva",
    "starlink": "No definido",
    "electronica": "No definido",
    "audio": "Estándar sin RGB",
    "fabricadora_hielo": "Modelo no definido",
    "tapiceria_mamparos": "Alplast hielo",
    "color_acolchados": "??",
    "adicionales": "SIN PARRILLA en cockpit"
  },
  "52-19": {
    "propietario": "LALO",
    "motorizacion": "Iveco 570",
    "madera_muebles": "Dekton Olimpo Stonika",
    "sternthruster": "Antena de Directv",
    "audio": "Mesa de cockpit",
    "tapiceria_mamparos": "Cuerina Blanca",
    "color_acolchados": "Bhanu 11",
    "adicionales": "1 Estereo, 2 Juego de parlantes en cockpit, 1 Potencia, 2parlantes en proa (Todo Blanco)"
  },
  "52-20": {
    "propietario": "Chine",
    "constructor": "Gustavo Fleitas",
    "motorizacion": "IVECO 570",
    "color_casco": "Blanco",
    "cabina": "Softop",
    "madera_muebles": "Nogal italiano rayado",
    "piso": "Europea Nature Alamo",
    "alfombra": "???",
    "color_mesadas": "Cocina: Purastone Travertino Navona \nBaño: Purastone Macchia Vecchia \nMesada de cockpit: Purastone Aria 25",
    "grupo_electrogeno": "Onan 9,5 kva. Se pone Kholer.",
    "sternthruster": true,
    "audio": "Con RGB / Detalle abajo",
    "fabricadora_hielo": true,
    "radar": false,
    "pluma": false,
    "tapiceria_mamparos": "HIELO",
    "color_acolchados": "Interdiseño Lina Folk 09 Blanco",
    "adicionales": "PLANCHADA Fija"
  },
  "52-21": {
    "propietario": "Pablo Rodriguez",
    "constructor": "Gustavo Fleitas",
    "motorizacion": "Iveco 570",
    "color_casco": "Blanco y Fondo con antifouling (3 manos)",
    "cabina": "Softop",
    "madera_muebles": "Melamina Camelia",
    "piso": "Orbis Floor OFXP 452-13",
    "alfombra": "No va",
    "grupo_electrogeno": "Kohler 9Kva",
    "sternthruster": true,
    "starlink": true,
    "electronica": "GARMIN GpsMap 1223",
    "audio": "Ver mas abajo (David)",
    "fabricadora_hielo": "Vitrifrigo IM-CL OCX2 REFILL RIGHT TD",
    "tapiceria_mamparos": "Hielo",
    "color_acolchados": "Anila 01",
    "adicionales": "Tenderlift / Instalado"
  },
  "52-22": {
    "propietario": "Marcelo Panizza",
    "constructor": "Gustavo Fleitas",
    "motorizacion": "Iveco 570",
    "color_casco": "Blanco y fondo convencional",
    "cabina": "Softop",
    "madera_muebles": "Nocce Milano",
    "piso": "Orbis Floor OFXP 452-13",
    "alfombra": "SIN",
    "grupo_electrogeno": "Kohler 9Kva",
    "starlink": "OK",
    "electronica": "GARMIN GpsMap 1223",
    "audio": "MESA cockpit / Convencional Levi",
    "adicionales": "Convencional Levi",
    "fabricadora_hielo": "Vitrifrigo IM-CL OCX2 REFILL RIGHT TD",
    "tapiceria_mamparos": "Hielo",
    "color_acolchados": "Anila 01"
  },
  "52-23": {
    "propietario": "Martín Gandara",
    "constructor": "Gustavo Fleitas",
    "motorizacion": "Iveco 570",
    "color_casco": "Blanco y fondo ?",
    "cabina": "HardTop",
    "madera_muebles": "Roble Plata Rayado",
    "alfombra": "MESADAS baño",
    "audio": "MESA cockpit",
    "fabricadora_hielo": "Vitrifrigo IM-CL OCX2 REFILL RIGHT TD",
    "radar": "CAMA Moto de agua / ??",
    "tapiceria_mamparos": "TECHOS",
    "adicionales": "Jacuzzi / Consultando a Barugel GP"
  },
  "52-24": {
    "propietario": "Diego",
    "constructor": "Gustavo Fleitas",
    "cabina": "Softop",
    "madera_muebles": "Nogal Poro Cerrado",
    "alfombra": "MESADAS baño",
    "audio": "MESA cockpit",
    "radar": "CAMA Moto de agua / ??",
    "tapiceria_mamparos": "TECHOS",
    "adicionales": "TenderLift"
  },
  "52-25": {
    "constructor": "Gustavo Fleitas",
    "cabina": "Softop",
    "madera_muebles": "Roble Plata Rayado",
    "alfombra": "MESADAS baño",
    "audio": "MESA cockpit",
    "radar": "CAMA Moto de agua / ??",
    "tapiceria_mamparos": "TECHOS"
  },
  "52-26": {
    "constructor": "Gustavo Fleitas",
    "alfombra": "MESADAS baño",
    "audio": "MESA cockpit",
    "radar": "CAMA Moto de agua",
    "tapiceria_mamparos": "TECHOS"
  },
  "55-1": {
    "propietario": "Marcelo Burgos",
    "constructor": "Daniel Indaburu",
    "motorizacion": "Volvo 715",
    "color_casco": "Blanco",
    "madera_muebles": "Chocolate Floreado \n(Con detalle en fórmica fendi top mate)",
    "piso": "Orbis Floor OFXP 452-13",
    "color_mesadas": "Coc; Purastone Metro Grey Mate - Bañ: Travertino",
    "electronica": "MESA cockpit / No",
    "teca_tipo": "No",
    "sternthruster": false,
    "starlink": false,
    "tapiceria_mamparos": "TECHOS",
    "audio": "Interior",
    "adicionales": "PLANCHADA extensible para bajar a Punta (1mt mas)"
  },
  "55-2": {
    "propietario": "German Kent",
    "constructor": "Damian Curatitoli",
    "motorizacion": "2x Iveco 630hp",
    "color_casco": "Blanco",
    "madera_muebles": "Roble Plata Rayado",
    "piso": "Orbis Floor OFXP 452-13",
    "color_mesadas": "Coc; Purastone Aria Pulido - Bañ; Desert Black",
    "electronica": "MESA cockpit / No",
    "teca_tipo": "No",
    "sternthruster": true,
    "radar": false,
    "pluma": false,
    "tapiceria_mamparos": "TECHOS",
    "audio": "Interior",
    "fabricadora_hielo": "Cava"
  },
  "55-3": {
    "propietario": "Emilio Salis",
    "constructor": "Feliciano Centurion",
    "motorizacion": "Volvo 725",
    "madera_muebles": "Nogal Poro Cerrado",
    "color_mesadas": "Purastone Travertino Navona",
    "grupo_electrogeno": "17 Kva ¿Qué modelo?",
    "electronica": "MESA cockpit / No",
    "teca_tipo": "No",
    "sternthruster": false,
    "radar": false,
    "pluma": false,
    "tapiceria_mamparos": "Hielo",
    "audio": "Interior",
    "adicionales": "Sin vestidor"
  },
  "55-4": {
    "constructor": "Damian Curatitoli",
    "madera_muebles": "Roble Plata Rayado",
    "electronica": "MESA cockpit / No",
    "teca_tipo": "No",
    "sternthruster": false,
    "radar": false,
    "pluma": false,
    "tapiceria_mamparos": "TECHOS",
    "audio": "Interior"
  },
  "64-21": {
    "propietario": "Roberto Cardalda",
    "constructor": "Montesano",
    "motorizacion": "IVECO 1000 735 Kw x 2 Bats 24 V",
    "color_casco": "Blanco",
    "cabina": "Closed Fly Salon",
    "madera_muebles": "Nogal Italiano Rayado",
    "piso": "Patagonia Madera Definir",
    "color_mesadas": "Cocina: \nBaños:",
    "sternthruster": true,
    "audio": "MESA cockpit",
    "fabricadora_hielo": "ESCALERA A SALON 2",
    "pluma": "TENDER / SI",
    "tapiceria_mamparos": "TECHOS"
  }
};
