-- ===== K37 BASE MATRIZ (398 items, limpio) — conserva vidrios revisados =====
do $$
declare v_modelo text := '37';
begin
  create temp table _stg(descripcion text, alias text, rubro text, proveedor text, unidad text, precio numeric, cantidad numeric, observaciones text) on commit drop;
  insert into _stg values
  ('Gelcoat Blanco MN2000B',null,'Laminación','Plaquimet/ADS','Balde x20Kg',6.6,200.0,null),
  ('Gelcoat MN2017',null,'Laminación','Plaquimet/ADS','Balde x20Kg',6.5,80.0,null),
  ('Gelcoat Negro',null,'Laminación','Plaquimet/ADS','Balde x20Kg',6.5,20.0,null),
  ('Mat 300',null,'Laminación','Riedel/Plaquimet','Rollo x43Kg',1.55,516.0,null),
  ('Mat 450',null,'Laminación','Riedel/Plaquimet','Rollo x46Kg',1.75,46.0,null),
  ('Rov 400',null,'Laminación','Riedel/Plaquimet','Rollo x75Kg',2.1,150.0,null),
  ('LT600',null,'Laminación','Náutica Recalada','Rollo x100Kg',2.1,300.0,null),
  ('Velo de superficie',null,'Laminación','Plaquimet','Rollo x250m²',0.9,250.0,null),
  ('Coremat 2mm',null,'Laminación','Plaquimet','Rollo x80m²',4.4,160.0,null),
  ('Resina 101',null,'Laminación','Plaquimet','Tambor x220Kg',2.7,2200.0,null),
  ('Resina 504',null,'Laminación','Plaquimet','Tambor x220Kg',3.4,220.0,null),
  ('Monómero',null,'Laminación','Plaquimet','Tambor x190Kg',2.25,190.0,null),
  ('Catalizador Akperox',null,'Laminación','Plaquimet','Bidón x20L',7.3,60.0,null),
  ('Acelerador Cobalto',null,'Laminación','Plaquimet','Bidón x20L',6.5,40.0,null),
  ('Airex H80 20mm',null,'Laminación','Plaquimet','Placa x3m²',165.0,36.0,null),
  ('Airex H80 15mm',null,'Laminación','Plaquimet','Placa x3m²',130.0,36.0,null),
  ('Masilla PQ7',null,'Laminación','ADS/All Built','Balde x17Kg',8.95,119.0,null),
  ('Talco industrial',null,'Laminación','All Built/ADS','Bolsa x25Kg',0.52,50.0,null),
  ('Britec Repair',null,'Laminación','Plaquimet','Lata x4Kg',7.5,8.0,null),
  ('Placas espuma poliuretano 100mm',null,'Carpintería y Varios','Argenpur','unid',75.0,10.0,null),
  ('Placa de carpintero',null,'Carpintería y Varios',null,'placa',75.0,8.0,null),
  ('Terciado 3mm',null,'Carpintería y Varios',null,'placa',14.5,4.0,null),
  ('Terciado 15mm',null,'Carpintería y Varios',null,'placa',56.0,1.0,null),
  ('Chapa de roble tinte rayado',null,'Carpintería y Varios','Calabria','m²',9.5,105.0,null),
  ('Pie de Okumé',null,'Carpintería y Varios',null,'pies',3.5,25.0,null),
  ('Pie de Lenga (marcos)',null,'Carpintería y Varios','Gaber','pies',2.5,25.0,null),
  ('Fórmica marfil',null,'Carpintería y Varios','Calabria','placa',64.0,1.0,null),
  ('PVC espumado espesor 20mm',null,'Carpintería y Varios','Heling','placa',64.0,1.0,null),
  ('Bisagra codo 9 + base con clip',null,'Herrajes','Rincón del Herraje','unid',0.77,30.0,null),
  ('Retén push Hafele 245.54.701',null,'Herrajes','Rincón del Herraje','unid',6.0,16.0,null),
  ('Guía telescóp. push 25cm',null,'Herrajes','Rincón del Herraje','juego',8.6,1.0,null),
  ('Guía telescóp. push 35cm',null,'Herrajes','Rincón del Herraje','juego',10.0,4.0,null),
  ('Guía telescóp. push 45cm',null,'Herrajes','Rincón del Herraje','juego',12.75,2.0,null),
  ('Bisagra para acrílico negro',null,'Herrajes','Rincón del Herraje','unid',1.85,1.0,null),
  ('Retén imán push',null,'Herrajes','Rincón del Herraje','unid',2.5,1.0,null),
  ('Bisagra oculta para puertas (14u)',null,'Herrajes','Rincón del Herraje','unid',5.5,14.0,null),
  ('Picaporte HL09 Hafele',null,'Herrajes','Rincón del Herraje','unid',60.0,4.0,'⚠️ REVISAR: $60 c/u es alto para picaporte HL09'),
  ('Cerradura Kallay 503',null,'Herrajes','Rincón del Herraje','unid',9.8,4.0,null),
  ('Retén imán para puerta Hafele',null,'Herrajes','Rincón del Herraje','unid',13.8,4.0,null),
  ('Pistón gas N60 para mueble',null,'Herrajes','Rincón del Herraje','unid',1.5,6.0,null),
  ('Cubeta cuadrada 35mm cromada',null,'Herrajes','Rincón del Herraje','unid',2.75,1.0,null),
  ('Topetinas transparentes chicas',null,'Herrajes','Rincón del Herraje','plancha',1.5,1.0,null),
  ('Bisagras codo 18 + base con clip',null,'Herrajes','Rincón del Herraje','unid',3.4,4.0,null),
  ('Buje reduc. bronce 1¼"x1"',null,'Mecánica','Gaona','unid',6.0,2.0,null),
  ('Buje reduc. bronce 1½"x1¼"',null,'Mecánica','Gaona','unid',8.0,2.0,null),
  ('Codo 90° MH bronce 3/4"',null,'Sanitarios','Gaona','unid',5.5,1.0,null),
  ('Codo 90° MH bronce 1/4"',null,'Mecánica','Iriarte','unid',2.5,10.0,null),
  ('Codo 90° MH bronce 1/2"',null,'Sanitarios','Gaona','unid',3.5,3.0,null),
  ('Codo 90° HH bronce 1/2"',null,'Mecánica','Iriarte','unid',3.5,2.0,null),
  ('Codo 90° MH bronce 1"',null,'Sanitarios','Gaona','unid',8.5,2.0,null),
  ('Codo 90° MH bronce 1¼"',null,'Mecánica','Iriarte','unid',14.0,1.0,null),
  ('Codo 90° MH bronce 2"',null,'Mecánica','Iriarte','unid',25.0,2.0,null),
  ('Cuchara bronce ranurada toma 1"',null,'Mecánica','Iriarte','unid',18.0,1.0,null),
  ('Entrerrosca bronce 1/4"',null,'Mecánica','Iriarte','unid',1.0,16.0,null),
  ('Entrerrosca bronce 1"',null,'Sanitarios','Gaona','unid',6.5,2.0,null),
  ('Tapa bronce 1/2"',null,'Mecánica','Iriarte','unid',2.5,2.0,null),
  ('Tapón bronce 1/4"',null,'Mecánica','Iriarte','unid',1.5,3.0,null),
  ('Tapón bronce 1"',null,'Mecánica','Gaona','unid',4.0,3.0,null),
  ('Te bronce 1¼"',null,'Mecánica','Gaona','unid',15.0,1.0,null),
  ('Válvula esférica 1/2" HH',null,'Mecánica','Gaona','unid',6.0,5.0,null),
  ('Válvula esférica 1" HH',null,'Mecánica','Gaona','unid',10.0,3.0,null),
  ('Válvula esférica 1¼" HH',null,'Mecánica','Gaona','unid',14.0,1.0,null),
  ('Válvula esférica 2" HH',null,'Mecánica','Gaona','unid',25.0,2.0,null),
  ('Entrerrosca bronce 1/2"x1/2" FLARE',null,'Mecánica','Iriarte','unid',3.5,8.0,null),
  ('Entrerrosca bronce 1/2"x3/8" FLARE',null,'Mecánica','Iriarte','unid',3.0,2.0,null),
  ('Poliamida 3/8" 3000PSI',null,'Mecánica','Iriarte','mts',4.5,20.0,'precio por metro'),
  ('Racor 1/4" espiga 6mm',null,'Mecánica','Iriarte','unid',3.8,1.0,'calefactor'),
  ('Racor 1" espiga 3/4"',null,'Mecánica','Iriarte','unid',6.0,3.0,null),
  ('Racor 1¼" espiga 44mm',null,'Mecánica','Iriarte','unid',10.0,1.0,null),
  ('Racor 2" espiga 50mm',null,'Mecánica','Iriarte','unid',15.0,2.0,null),
  ('Racor 3/4" espiga 19mm',null,'Mecánica','Iriarte','unid',4.5,2.0,null),
  ('Racor 1/2" espiga 5/8"',null,'Mecánica','Iriarte','unid',3.5,2.0,null),
  ('Venteo tanque cromado 3/4"',null,'Mecánica','Iriarte','unid',28.0,2.0,null),
  ('Grasera copa bronce N4',null,'Mecánica','Iriarte','unid',15.0,2.0,null),
  ('Te bronce 3/8" c/virola (dirección)',null,'Mecánica','Iriarte','unid',22.0,2.0,null),
  ('Manguera cristal alambre 3/4"',null,'Mecánica',null,'mts',12.0,2.0,null),
  ('Manguera cristal hidrocarburo 10mm',null,'Mecánica',null,'mts',2.5,2.0,null),
  ('Manguera goma y tela 4" int.',null,'Mecánica',null,'mts',48.0,4.0,null),
  ('Manguera goma y tela 10mm',null,'Mecánica',null,'mts',3.5,5.0,null),
  ('Manguera goma/tela hidrocarburo 2"',null,'Mecánica',null,'mts',35.0,5.0,null),
  ('Manguera goma/tela hidrocarburo 3/4"',null,'Mecánica',null,'mts',12.5,3.0,null),
  ('Toma pasacasco 1¼"',null,'Mecánica','Iriarte','unid',38.0,1.0,null),
  ('Toma pasacasco 1" bronce',null,'Mecánica','Iriarte','unid',31.0,1.0,null),
  ('Toma pasacasco 2" bronce',null,'Mecánica','Iriarte','unid',82.0,2.0,null),
  ('Abrazadera inox 10mm int. (16u)',null,'Mecánica','Rebollar','unid',1.2,16.0,null),
  ('Abrazadera inox 3/4" (8u)',null,'Sanitarios','Rebollar','unid',0.8,8.0,null),
  ('Abrazadera inox sup-pres 50-70mm (16u)',null,'Mecánica','Rebollar','unid',5.8,16.0,null),
  ('Abrazadera inox sup-pres 100-130mm (28u)',null,'Mecánica','Rebollar','unid',8.5,28.0,null),
  ('Salida escape 2"',null,'Mecánica','Iriarte','unid',115.0,1.0,null),
  ('Separador agua-gases Centek 2" 1020200',null,'Mecánica','Trimer','unid',865.0,1.0,null),
  ('Silenciador escape 2" Centek 1500027w (grupo)',null,'Mecánica','Trimer','unid',490.0,1.0,null),
  ('Bulón inox 1/2"x2½" (16u)',null,'Mecánica','Rebollar','unid',4.1,16.0,null),
  ('Bulón inox 1/2"x3" (4u)',null,'Mecánica','Rebollar','unid',4.8,4.0,null),
  ('Bulón inox 5/8"x2"',null,'Mecánica','Rebollar','unid',6.5,1.0,null),
  ('Tuerca 3/4" inox (6u)',null,'Mecánica','Rebollar','unid',4.5,6.0,null),
  ('Arandela inox 3/8" (40u)',null,'Mecánica','Rebollar','unid',0.6,40.0,null),
  ('Tuerca autofrenante galv. 3/8" (40u)',null,'Mecánica','Rebollar','unid',0.45,40.0,null),
  ('Varilla roscada 3/4" inox',null,'Mecánica','Rebollar','unid',85.0,1.0,null),
  ('Varilla roscada 3/8" inox (4u)',null,'Mecánica','Rebollar','unid',18.0,4.0,null),
  ('Abrazaderas 76,5mm (40u)',null,'Mecánica',null,'unid',4.5,40.0,null),
  ('Manguera goma Øint=100mm (8mts)',null,'Mecánica',null,'mts',42.0,8.0,null),
  ('Abrazaderas 100mm (32u)',null,'Mecánica',null,'unid',6.5,32.0,null),
  ('Manguera goma/alambre Øint=50mm (24mts)',null,'Mecánica',null,'mts',18.5,24.0,null),
  ('Abrazaderas 50/70 (80u)',null,'Mecánica',null,'unid',4.5,80.0,null),
  ('Flexible 1" hembra giratoria x1680mm',null,'Mecánica',null,'mts',45.0,1.7,'pata'),
  ('Flexible 1/2" hembra giratoria (pata)',null,'Mecánica',null,'mts',18.0,2.0,null),
  ('Flexible 10mm hembra giratoria (pata)',null,'Mecánica',null,'mts',12.5,6.0,null),
  ('Flexible 10mm x1800mm hembra (pata)',null,'Mecánica',null,'mts',18.0,1.8,null),
  ('Manguera flexible 10mm hidrocarburo (pata)',null,'Mecánica',null,'mts',6.5,2.0,null),
  ('Sensor combustible Wema 30"',null,'Mecánica','Baron','unid',65.0,1.0,null),
  ('Sensor combustible Wema 26"',null,'Mecánica','Baron','unid',60.0,1.0,'pata simple'),
  ('Sensor agua Wema 8"',null,'Mecánica','Baron','unid',45.0,1.0,null),
  ('Reloj nivel combustible Wema',null,'Mecánica','Trimer','unid',44.0,1.0,null),
  ('Chapa de 2mm Inox. 316 (3m x 1,5m) (TANQUES)',null,'Mecánica','Famiq','unid',375.0,5.0,'c/iva'),
  ('Cupla Inoxidable 1/4" (TANQUES)',null,'Mecánica','Famiq','unid',1.95,4.0,null),
  ('Cupla Inoxidable 1/2" (TANQUES)',null,'Mecánica','Famiq','unid',2.29,7.0,null),
  ('Cupla Inoxidable 3/4" (TANQUES)',null,'Mecánica','Famiq','unid',3.25,3.0,null),
  ('Cupla Inoxidable 1" (TANQUES)',null,'Mecánica','Famiq','unid',5.63,4.0,null),
  ('Cupla Inoxidable 1¼" (TANQUES)',null,'Mecánica','Famiq','unid',7.34,2.0,null),
  ('Cupla Inoxidable 2" (TANQUES)',null,'Mecánica','Famiq','unid',11.98,2.0,null),
  ('Bulon de Inox 1/4" x 1¼" todo rosca (TANQUES)',null,'Mecánica','Rebollar','unid',0.1,200.0,null),
  ('Arandela de Inox. 1/4" (TANQUES)',null,'Mecánica','Rebollar','unid',0.01,200.0,null),
  ('Tuerca autofrenante de Inox. 1/4" (TANQUES)',null,'Mecánica','Rebollar','unid',0.05,200.0,null),
  ('Tuerca de Inox 1/2" (TANQUES)',null,'Mecánica','Rebollar','unid',0.13,2.0,null),
  ('Sellador Threebond (TANQUES)',null,'Mecánica','Rebollar','unid',13.0,4.0,null),
  ('Goma p/hidrocarburos 3 mm (TANQUES)',null,'Mecánica','Rebollar','placa',7.8,1.0,null),
  ('Reloj nivel agua Wema',null,'Mecánica','Trimer','unid',44.0,1.0,null),
  ('Juego filtros doble combustible Rama RK18',null,'Mecánica','Rama','unid',316.1427586206897,1.0,null),
  ('Carga combustible Perko Diesel Cromada 2" (2u)',null,'Mecánica','Iriarte','unid',31.72413793103448,2.0,null),
  ('Filtro combustible Rama 160RK (grupo)',null,'Mecánica','Rama','unid',75.21241379310345,1.0,null),
  ('Filtro agua 1" (1u)',null,'Mecánica',null,'unid',59.18344827586207,1.0,null),
  ('Sistema de flaps Bennett 12V',null,'Mecánica','Trimer','juego',1165.0,1.0,null),
  ('Bowthruster Craftman 55-12V 55Kg',null,'Mecánica','Baron B19055','unid',1840.0,1.0,null),
  ('Barra 2 1/4" inox 316 L=2600mm (solo línea de eje)',null,'Mecánica','Famiq','mts',135.0,5.2,null),
  ('Brida 120mm ext x 50mm int, chapa 3/8" inox 316 (solo línea de eje)',null,'Mecánica','Famiq','unid',26.68,2.0,null),
  ('Brida 200mm ext x 100mm int, chapa 3mm inox 316 (solo línea de eje)',null,'Mecánica','Famiq','unid',25.0,2.0,null),
  ('Caño 32mm x 3mm inox 316 (solo línea de eje)',null,'Mecánica','Famiq','mts',36.0,0.8,null),
  ('Caño 127 x 2mm inox 316 (solo línea de eje)',null,'Mecánica','Famiq','mts',48.0,4.0,null),
  ('Corte s/plantilla chapa 1/4" inox 316 - corte n°1 (solo línea de eje)',null,'Mecánica','Famiq','unid',47.0,4.0,null),
  ('Corte s/plantilla chapa 1/2" inox 316 - corte n°2 (solo línea de eje)',null,'Mecánica','Famiq','unid',165.0,2.0,null),
  ('Corte 230x350mm chapa 1/2" 316 - corte n°3 (solo línea de eje)',null,'Mecánica','Famiq','unid',130.0,2.0,null),
  ('Curva para soldar 90° 127x2mm inox 316 (solo línea de eje)',null,'Mecánica','Famiq','unid',54.0,9.0,null),
  ('Caño s/costura inox Sch.10, 2" nominal (solo línea de eje)',null,'Mecánica','Aceros Fitzner','unid',110.0,1.0,null),
  ('Caño s/costura inox Sch.80, 3" nominal (solo línea de eje) 600 mm',null,'Mecánica','Aceros Fitzner','unid',241.0,1.0,null),
  ('Abrazadera sup.pres. 135-145mm inox (mang.5" int.) (solo línea de eje)',null,'Mecánica','Rebollar','unid',8.0,28.0,null),
  ('Buje de bronce 60mm ext x 40mm int (solo línea de eje)',null,'Mecánica','Parra','unid',70.0,1.0,null),
  ('Buje de bronce y goma para eje 2 1/4" (solo línea de eje)',null,'Mecánica','Parra','unid',120.0,3.0,null),
  ('Filtro de agua 1 1/2" inox (solo línea de eje)',null,'Mecánica','Abadie','unid',56.0,2.0,null),
  ('Hierro manchón Ø146mm x 155mm (solo línea de eje)',null,'Mecánica','Gueto','unid',168.0,2.0,null),
  ('Manguera goma y tela 5" int. (solo línea de eje)',null,'Mecánica','Rebollar','mts',60.0,5.0,null),
  ('Planchuela hierro 120mm x 4mm (solo línea de eje)',null,'Mecánica','Hierros Tigre','unid',45.0,1.0,null),
  ('"U" de hierro L=1000mm, 125x80mm int., esp=1/4" (solo línea de eje)',null,'Mecánica','Plegadora','unid',75.0,4.0,null),
  ('Tubo PRFV Dint=76mm, esp=7mm - tubo bocina (solo línea de eje)',null,'Mecánica',null,'unid',68.5,2.0,null),
  ('Ánodo timón (solo línea de eje)',null,'Mecánica','Trimer','unid',42.0,2.0,null),
  ('Ánodo eje 2 1/4" (solo línea de eje)',null,'Mecánica','Trimer','unid',148.0,2.0,null),
  ('Ánodo escudo (solo línea de eje)',null,'Mecánica','Trimer','unid',116.0,1.0,null),
  ('Ánodo de flaps (solo línea de eje)',null,'Mecánica','Trimer','unid',39.0,2.0,null),
  ('Bomba de dirección U-Flex UP28F (solo línea de eje)',null,'Mecánica','Trimer','unid',750.0,1.0,null),
  ('Cilindro de dirección U-Flex UC168-I (solo línea de eje)',null,'Mecánica','Trimer','unid',800.0,1.0,null),
  ('Sello PSS para eje 2 1/4", tubo 3 1/2" (solo línea de eje)',null,'Mecánica','Trimer','unid',950.0,2.0,null),
  ('Silenciador Centek Vernalift 5"',null,'Mecánica','Trimer','unid',1270.0,2.0,'REVISAR precio. (Lo fabrican los mecanicos porque el de trimer no entra)'),
  ('Hélices (solo línea de eje)',null,'Mecánica','Penna','unid',2231.0,2.0,null),
  ('Conector T WX1502','Whale','Sanitarios',null,'unid',6.9,7.0,'Orig: Conector T Whale WX1502'),
  ('Conector T M/H WX1521','Whale','Sanitarios','Trimer','unid',6.95,1.0,'Orig: Conector T M/H Whale WX1521'),
  ('Conector codo c/espiga WX1522','Whale','Sanitarios','Trimer','unid',5.5,1.0,'Orig: Conector codo c/espiga Whale WX1522'),
  ('Conector Codo WX1503','Whale','Sanitarios','Trimer','unid',4.92,3.0,'Orig: Conector Codo Whale WX1503'),
  ('Exclusa WX1573','Whale','Sanitarios','Trimer','unid',27.0,1.0,'Orig: Exclusa Whale WX1573'),
  ('Macho','Whale','Sanitarios',null,'unid',6.0,1.0,'Orig: Macho Whale'),
  ('Adaptador rosca H 1/2" WX1532','Whale','Sanitarios','Trimer','unid',5.22,2.0,'Orig: Adaptador rosca H 1/2" Whale WX1532'),
  ('Adaptador rosca M 1/2" WX1514','Whale','Sanitarios','Trimer','unid',5.5,2.0,'Orig: Adaptador rosca M 1/2" Whale WX1514'),
  ('Tubo rojo 15mm WX7154 (25mts)','Whale','Sanitarios','Trimer','mts',130.0,25.0,'Orig: Tubo Whale rojo 15mm WX7154 (25mts)'),
  ('Tubo azul 15mm WX7152 (25mts)','Whale','Sanitarios','Trimer','mts',130.0,25.0,'Orig: Tubo Whale azul 15mm WX7152 (25mts)'),
  ('Duchador popa frío/calor','Whale','Sanitarios','Baron','unid',210.0,1.0,'Orig: Duchador popa frío/calor Whale'),
  ('T plástica espiga 1/2"',null,'Sanitarios',null,'unid',1.5,1.0,null),
  ('T bronce 1"',null,'Sanitarios','Gaona','unid',11.0,1.0,null),
  ('Abrazadera inox 1½" (10u)',null,'Sanitarios','Rebollar','unid',1.5,10.0,null),
  ('Abrazadera inox 1" (10u)',null,'Sanitarios','Rebollar','unid',1.0,10.0,null),
  ('Buje reduc. 1¼"a1"',null,'Sanitarios','Gaona','unid',6.0,1.0,null),
  ('Buje reduc. 1"x3/4" plástico',null,'Sanitarios','Gaona','unid',1.5,1.0,null),
  ('Buje reduc. 3/4"x1/2"',null,'Sanitarios','Gaona','unid',3.0,1.0,null),
  ('Codo MH 1/2"a1" plástico',null,'Sanitarios','Gaona','unid',2.0,1.0,null),
  ('Codo rosca H 1¼" espiga 1" (3u)',null,'Sanitarios','Gaona','unid',2.5,3.0,null),
  ('Codo 90° HH bronce 1"',null,'Sanitarios','Gaona','unid',8.13,2.0,null),
  ('Codo 90° HH bronce 3/4"',null,'Sanitarios','Gaona','unid',5.5,1.0,null),
  ('Codo 90° HH bronce 3/4"x1/2"',null,'Sanitarios','Gaona','unid',5.0,1.0,null),
  ('Codo 90° HH bronce 1¼"',null,'Sanitarios','Gaona','unid',14.0,2.0,null),
  ('Codo 90° HH bronce 1½"',null,'Sanitarios','Gaona','unid',18.0,1.0,null),
  ('Codo 90° MH 1" plástico',null,'Sanitarios','Gaona','unid',2.0,1.0,null),
  ('Codo 90° MH bronce 1½"',null,'Sanitarios','Gaona','unid',18.5,1.0,null),
  ('Cuchara bronce Nro 104',null,'Sanitarios',null,'unid',13.8,2.0,null),
  ('Cupla 1"a1/2" HH',null,'Sanitarios',null,'unid',6.0,1.0,null),
  ('Entrerrosca bronce 1/2"',null,'Sanitarios','Gaona','unid',3.0,1.0,null),
  ('Entrerrosca plástico 1/2"',null,'Sanitarios','Gaona','unid',1.0,1.0,null),
  ('Entrerrosca 1/2"a3/4"',null,'Sanitarios','Gaona','unid',4.0,1.0,null),
  ('Válvula esférica 1½" HH',null,'Sanitarios','Gaona','unid',31.0,2.0,null),
  ('Válvula esférica 1/2"',null,'Sanitarios','Gaona','unid',8.0,1.0,null),
  ('Manguera cristal alambre 1½" (25mts)',null,'Sanitarios','Rebollar','mts',0.48,25.0,null),
  ('Manguera cristal alambre 1" (25mts)',null,'Sanitarios','Rebollar','mts',0.32,25.0,null),
  ('Manguera cristal alambre 3/4" (25mts)',null,'Sanitarios','Rebollar','mts',0.24,25.0,null),
  ('Manguera cristal alambre 5/8" (25mts)',null,'Sanitarios','Rebollar','mts',0.2,25.0,null),
  ('Manguera cristal alambre 1/2" (25mts)',null,'Sanitarios','Rebollar','mts',0.16,25.0,null),
  ('Plaquetas (bolsa)',null,'Sanitarios',null,'bolsa',5.0,1.0,null),
  ('Precintos 35cm (bolsa)',null,'Sanitarios',null,'bolsa',6.0,1.0,null),
  ('Racor bronce M 1½"x1½" manguera',null,'Sanitarios','Iriarte','unid',14.0,1.0,null),
  ('Racor bronce M 1"x1" manguera',null,'Sanitarios','Iriarte','unid',7.5,2.0,null),
  ('Racor bronce M 1"x5/8" manguera',null,'Sanitarios','Iriarte','unid',7.0,1.0,null),
  ('Racor bronce M espiga 1"',null,'Sanitarios','Iriarte','unid',7.5,1.0,null),
  ('Racor hembra 1" espiga macho 1"',null,'Sanitarios','Iriarte','unid',8.0,1.0,null),
  ('Racor 1½"',null,'Sanitarios','Iriarte','unid',12.0,1.0,null),
  ('Racor 1"',null,'Sanitarios','Iriarte','unid',7.0,3.0,null),
  ('Racor macho 1¼"x1" plástico',null,'Sanitarios','Iriarte','unid',2.5,1.0,null),
  ('Racor macho 1"x1" plástico',null,'Sanitarios','Iriarte','unid',2.0,3.0,null),
  ('Racor macho 1"x3/4" plástico',null,'Sanitarios','Iriarte','unid',1.5,1.0,null),
  ('Racor macho 3/4"x1/2" plástico',null,'Sanitarios','Iriarte','unid',1.2,1.0,null),
  ('Racor macho 1/2"x1/2" plástico',null,'Sanitarios','Iriarte','unid',1.0,1.0,null),
  ('Reducción 1½"a1"',null,'Sanitarios','Iriarte','unid',10.0,1.0,null),
  ('Tapón 1"',null,'Sanitarios',null,'unid',4.0,1.0,null),
  ('Toma pasacasco 3/4" Iriarte',null,'Sanitarios','Iriarte','unid',18.0,1.0,null),
  ('Toma pasacasco cromada 1½" Iriarte',null,'Sanitarios','Iriarte','unid',45.0,1.0,null),
  ('Sopapa bañera c/codo Delta 1½"',null,'Sanitarios','Gaona','unid',25.0,1.0,null),
  ('Sopapa lavatorio cromada Delta (2u)',null,'Sanitarios','Gaona','unid',18.0,2.0,null),
  ('Bomba agua automática 3GPM + prefiltro',null,'Sanitarios','Trimer','unid',190.0,1.0,null),
  ('Bomba achique Rule 2000 GPH 12V (3u)',null,'Sanitarios','Trimer','unid',185.0,3.0,null),
  ('Switch automático Rule 35A (3u)',null,'Sanitarios','Trimer','unid',42.5,3.0,null),
  ('Rule Panel Switch 43 tablero (3u)',null,'Sanitarios','Trimer','unid',43.5,3.0,null),
  ('Caja drenaje ducha Rule 800GPH (2u)',null,'Sanitarios','Trimer','unid',190.0,2.0,null),
  ('Termotanque Kuuma 42L (11 gal)',null,'Sanitarios','Baron','unid',908.0,1.0,'⚠️ REVISAR: Kuuma 23L del K43 era $730. 42L a $908 → ok si es correcto el modelo'),
  ('Duchador popa (2do cálculo Baron)','Whale','Sanitarios','Baron','unid',212.41,1.0,'Orig: Duchador popa Whale (2do cálculo Baron)'),
  ('Canilla plegable frío/calor cromada FV',null,'Sanitarios','Baron','unid',45.0,1.0,null),
  ('Canilla válvula esférica lavarropas',null,'Sanitarios',null,'unid',7.0,1.0,null),
  ('Monocomando lavatorio FV Libby',null,'Sanitarios',null,'unid',196.0,1.0,null),
  ('Monocomando ducha FV Libby',null,'Sanitarios',null,'unid',241.0,1.0,null),
  ('Ducha con barral FV Polca',null,'Sanitarios',null,'unid',65.0,1.0,null),
  ('Percha FV Libby',null,'Sanitarios',null,'unid',20.0,1.0,null),
  ('Monocomando cocina FV Arizona alto',null,'Sanitarios',null,'unid',69.0,1.0,null),
  ('Portarrollo FV Libby',null,'Sanitarios',null,'unid',31.0,1.0,null),
  ('Bidematic solo frío',null,'Sanitarios',null,'unid',59.0,1.0,null),
  ('Pileta inox Johnson Acero Q40',null,'Sanitarios',null,'unid',95.0,1.0,null),
  ('Pileta Ferrum Persis Chica blanca',null,'Sanitarios',null,'unid',55.0,1.0,null),
  ('Llave corte batería Blue Sea (4u)',null,'Electricidad','Costa','unid',22.0,4.0,null),
  ('Cargador/inversor Victron Multiplus 1600W/12V',null,'Electricidad','Trimer','unid',1100.0,1.0,null),
  ('Calefactor Autoterm Air 4D 12V 4000W',null,'Electricidad','Baron','unid',731.03,1.0,null),
  ('Contactor bobina',null,'Electricidad',null,'unid',20.0,1.0,null),
  ('Malacate Lofrans X1 700W cod.473002',null,'Electricidad','Baron','unid',1100.0,1.0,null),
  ('Térmico para malacate',null,'Electricidad',null,'unid',100.0,1.0,null),
  ('Botón malacate / Footswitch (2u)',null,'Electricidad','Baron/Trimer','unid',93.0,2.0,null),
  ('Inversor/cargador Victron 1600W 12V',null,'Electricidad','Trimer','unid',1100.0,1.0,null),
  ('Panel Multicontrol Digital Victron',null,'Electricidad','Trimer','unid',210.0,1.0,null),
  ('Conexión puerto Marinco 16A 230V',null,'Electricidad','Trimer','unid',83.0,1.0,null),
  ('Ficha Marinco Hembra',null,'Electricidad','Trimer','unid',47.0,1.0,null),
  ('Funda Marinco',null,'Electricidad','Trimer','unid',25.0,1.0,null),
  ('Cable amarillo Marinco 2,5mm² (10mts)',null,'Electricidad','Trimer','mts',8.0,10.0,null),
  ('Llave corte batería remota Blue Sea',null,'Electricidad',null,'unid',245.0,1.0,'4/6/7 unidades según motor'),
  ('Luz techo LED inox cuadrada grande (26u)',null,'Electricidad','M.Martyniuk','unid',17.93,26.0,null),
  ('Luz techo LED inox cuadrada chica (2u)',null,'Electricidad','M.Martyniuk','unid',12.0,2.0,null),
  ('Luz cortesía blanca 3LED oval cromado',null,'Electricidad','Trimer','unid',7.93,2.0,null),
  ('Luz cortesía LED Azul inox (38u)',null,'Electricidad','M.Martyniuk','unid',7.93,38.0,null),
  ('Luz cortesía LED Blanco inox (12u)',null,'Electricidad','M.Martyniuk','unid',7.93,12.0,null),
  ('Tira LED blanco cálido (14mts)',null,'Electricidad','Janored/2001','mts',5.0,14.0,null),
  ('Baterías 180 Ah (4u)',null,'Electricidad','PowerBat','unid',203.45,4.0,null),
  ('Batería 90 Ah',null,'Electricidad','PowerBat','unid',130.0,1.0,null),
  ('Caja para batería',null,'Electricidad','Baron','unid',25.0,1.0,null),
  ('Velador individual c/interruptor (4u)',null,'Electricidad',null,'unid',39.1,4.0,'del K43'),
  ('Tira de LED (20mts)',null,'Electricidad',null,'mts',5.0,20.0,null),
  ('Perfil aluminio tira LED (2mts)',null,'Electricidad',null,'mts',6.0,2.0,null),
  ('Soporte pared TV (2u)',null,'Electricidad',null,'unid',16.5,2.0,null),
  ('TV 32" Smart Samsung/LG',null,'Electricidad',null,'unid',272.0,1.0,'75cm ancho máx'),
  ('TV 24"/26" Smart Samsung/LG',null,'Electricidad',null,'unid',220.0,1.0,null),
  ('BASE PORTA FUSIBLE NH-00 160 (2u)',null,'Electricidad',null,'unid',20.0,2.0,null),
  ('Cable canal 100x70 (3 tiras)',null,'Electricidad',null,'unid',10.0,3.0,null),
  ('Cable 1x0,75 – 6 colores x35mts c/u',null,'Electricidad','Janored/2001','mts',0.2,210.0,'precio por metro'),
  ('Cable 1x1 negro (100mts)',null,'Electricidad','Janored/2001','mts',0.25,100.0,null),
  ('Cable 1x1 rojo (200mts)',null,'Electricidad','Janored/2001','mts',0.25,200.0,null),
  ('Cable 1x1,5 gris (100mts)',null,'Electricidad','Janored/2001','mts',0.35,100.0,null),
  ('Cable 1x1,5 negro (200mts)',null,'Electricidad','Janored/2001','mts',0.35,200.0,null),
  ('Cable 1x1,5 rojo (300mts)',null,'Electricidad','Janored/2001','mts',0.35,300.0,null),
  ('Cable 1x1,5 violeta (200mts)',null,'Electricidad','Janored/2001','mts',0.35,200.0,null),
  ('Cable 1x2,5 negro (300mts)',null,'Electricidad','Janored/2001','mts',0.55,300.0,null),
  ('Cable 1x2,5 rojo (600mts)',null,'Electricidad','Janored/2001','mts',0.55,600.0,null),
  ('Cable 1x4 negro (50mts)',null,'Electricidad','Janored/2001','mts',0.9,50.0,null),
  ('Cable 1x4 rojo (100mts)',null,'Electricidad','Janored/2001','mts',0.9,100.0,null),
  ('Cable 1x6 negro (300mts)',null,'Electricidad','Janored/2001','mts',1.4,300.0,null),
  ('Cable 1x6 rojo (400mts)',null,'Electricidad','Janored/2001','mts',1.4,400.0,null),
  ('Cable chato 3x1,5 (50mts)',null,'Electricidad','Janored/2001','mts',1.0,50.0,null),
  ('Cable chato 3x2,5 (100mts)',null,'Electricidad','Janored/2001','mts',1.5,100.0,null),
  ('Cable chato 3x4 (60mts)',null,'Electricidad','Janored/2001','mts',2.4,60.0,null),
  ('Cable coaxil RG-58 (50mts)',null,'Electricidad','Janored/2001','mts',0.4,50.0,null),
  ('Cable paralelo bicolor 2x1 (100mts)',null,'Electricidad','Janored/2001','mts',0.35,100.0,null),
  ('Cable RCA audio/video 3x0,25 (100mts)',null,'Electricidad','Janored/2001','mts',0.35,100.0,null),
  ('Cable soldadura flex 1x16 (5mts)',null,'Electricidad','Janored/2001','mts',4.0,5.0,null),
  ('Cable soldadura flex 1x25 (55mts)',null,'Electricidad','Janored/2001','mts',6.0,55.0,null),
  ('Cable soldadura flex 1x35 (60mts)',null,'Electricidad','Janored/2001','mts',8.0,60.0,null),
  ('Cable soldadura flex 1x50 (45mts)',null,'Electricidad','Janored/2001','mts',11.0,45.0,null),
  ('Cable soldadura flex 1x70 (45mts)',null,'Electricidad','Janored/2001','mts',15.0,45.0,null),
  ('Cable tipo taller 7x1,5 (30mts)',null,'Electricidad','Janored/2001','mts',2.4,30.0,null),
  ('Cable tipo taller 3x6 (30mts)',null,'Electricidad','Janored/2001','mts',3.5,30.0,null),
  ('Caño corrugado flex 1" (50mts)',null,'Electricidad','Janored/2001','mts',0.25,50.0,null),
  ('Caño corrugado flex 1/2" (20mts)',null,'Electricidad','Janored/2001','mts',0.15,20.0,null),
  ('Caño corrugado flex 3/4" (50mts)',null,'Electricidad',null,'mts',0.2,50.0,null),
  ('Varios eléctricos (terminales/precintos/módulos/Carlings)',null,'Electricidad','Janored/2001/Cambre','global',100.0,1,null),
  ('Parabrisas completo (3 partes)',null,'Vidrios','Mercoglass','unid',600.0,1.0,null),
  ('Ventana claraboya Templado 6mm Gris',null,'Vidrios','Mercoglass','unid',117.0,1.0,null),
  ('Ventana lateral casco B1a Templado 10mm curvo',null,'Vidrios','Mercoglass/Favicur','unid',121.84,1.0,null),
  ('Ventana lateral casco B1b Templado 10mm curvo',null,'Vidrios','Mercoglass/Favicur','unid',96.16,1.0,null),
  ('Ventana lateral casco E1a Templado 10mm curvo',null,'Vidrios','Mercoglass/Favicur','unid',121.84,1.0,null),
  ('Ventana lateral casco E1b Templado 10mm curvo',null,'Vidrios','Mercoglass/Favicur','unid',96.16,1.0,null),
  ('Ventana lateral casco B2 Templado 10mm',null,'Vidrios','Mercoglass/Favicur','unid',86.0,1.0,null),
  ('Ventana lateral casco E2 Templado 10mm',null,'Vidrios','Mercoglass/Favicur','unid',86.66,1.0,null),
  ('Ventana lateral casco B3 Templado 10mm',null,'Vidrios','Mercoglass/Favicur','unid',83.03,1.0,null),
  ('Ventana lateral casco E3 Templado 10mm',null,'Vidrios','Mercoglass/Favicur','unid',83.03,1.0,null),
  ('Ventana lateral casco B4 Templado 10mm',null,'Vidrios','Mercoglass/Favicur','unid',83.03,1.0,null),
  ('Ventana lateral casco E4 Templado 10mm',null,'Vidrios','Mercoglass/Favicur','unid',83.03,1.0,null),
  ('Espejo 580x530mm espesor 3mm',null,'Vidrios',null,'unid',55.86,1.0,null),
  ('Acrílicos de timonera 8mm (3u)',null,'Carpintería y Varios','Acrimold','unid',null,3.0,'FALTA PRECIO'),
  ('Acrílico tapa tablero eléctrico 8mm',null,'Carpintería y Varios','Acrimold','unid',null,1.0,null),
  ('Acrílico mesa de salón 5mm',null,'Carpintería y Varios','Acrimold','unid',null,1.0,null),
  ('Acrílico posavasos 10mm (3u)',null,'Carpintería y Varios','Acrimold','unid',null,3.0,null),
  ('Acrílico tapa selectora 6mm',null,'Carpintería y Varios','Acrimold','unid',null,1.0,null),
  ('Acrílico fondo selectora 3mm',null,'Carpintería y Varios','Acrimold','unid',null,1.0,null),
  ('Anafe vitrocerámica 2 hornallas','Samsung','Electricidad','ML','unid',296.24,1.0,'Orig: Anafe vitrocerámica 2 hornallas Samsung'),
  ('Heladera WRX12','Whirpool','Electricidad','ML','unid',450.0,1.0,'bajo mesada / Orig: Heladera Whirpool WRX12'),
  ('Parrilla eléctrica ATMA',null,'Electricidad','ML','unid',433.93,1.0,'igual al K43'),
  ('Microondas 23L negro MG23S','Samsung','Electricidad','ML','unid',175.0,1.0,'Orig: Microondas Samsung 23L negro MG23S'),
  ('Pileta sillón de popa Johnson E28',null,'Electricidad','Johnson Acero','unid',58.0,1.0,'28,5x34x15'),
  ('Fabricadora de hielo U-Line BI95',null,'Electricidad','Trimer','unid',2662.0,1.0,null),
  ('Cierre levantapiso redondo inox c/perno',null,'Carpintería y Varios','Baron L06475','unid',25.0,1.0,null),
  ('Ancla Delta 16kg galvanizada',null,'Carpintería y Varios','Baron A95562','unid',140.0,1.0,null),
  ('Cadena 6mm calibrada galvanizada (50mts)',null,'Carpintería y Varios','Baron C05066','mts',4.5,50.0,null),
  ('Giratorio gusano cadena 6-8mm',null,'Carpintería y Varios','Baron G08302','unid',45.0,1.0,null),
  ('Grillete omega 8mm',null,'Carpintería y Varios','Baron G20052','unid',1.62,1.0,null),
  ('Sapito desagote ancla (2u)',null,'Carpintería y Varios',null,'unid',2.2,2.0,null),
  ('Punto fijo 6mm 4 agujeros',null,'Carpintería y Varios','Baron B10155','unid',3.5,1.0,null),
  ('Grillete largo 6mm',null,'Carpintería y Varios','Baron G20039','unid',0.96,1.0,null),
  ('Cabo 6mm con gazas en extremos',null,'Carpintería y Varios','Baron C51667','unid',2.19,1.0,null),
  ('Defensas blancas c/2m cabo negro (6u)',null,'Carpintería y Varios',null,'unid',41.24,6.0,null),
  ('Cabos 14mm x10m negro (4u)',null,'Carpintería y Varios',null,'unid',15.0,4.0,null),
  ('Posavasos inox (2u)',null,'Carpintería y Varios','Baron S16985','unid',7.51,2.0,null),
  ('Omegas inox chicos (2u)',null,'Carpintería y Varios','Baron','unid',1.5,2.0,null),
  ('Tapa estanca plástica blanca 60,5x35',null,'Carpintería y Varios','Baron T12913','unid',45.0,1.0,null),
  ('Levantapisos interior (2u)',null,'Carpintería y Varios','Baron L06004','unid',4.35,2.0,null),
  ('Levantapisos exterior (3u)',null,'Carpintería y Varios','Baron L06112','unid',24.48,3.0,null),
  ('Bisagra chica perno arriba (6u)',null,'Carpintería y Varios','Baron B21688','unid',3.58,6.0,null),
  ('Bisagra grande perno arriba (4u)',null,'Carpintería y Varios','Baron B21666','unid',4.86,4.0,null),
  ('Bisagra doble perno abajo (4u)',null,'Carpintería y Varios',null,'unid',3.7,4.0,null),
  ('Cierre gallina',null,'Carpintería y Varios','Baron C42533','unid',11.38,1.0,null),
  ('Pistones 20kg (2u)',null,'Carpintería y Varios','Baron R05051','unid',16.34,2.0,null),
  ('Toma USB (3u)',null,'Carpintería y Varios','Baron E03032','unid',12.0,3.0,null),
  ('Rejillas obturables plástico blanco (3u)',null,'Carpintería y Varios','Baron R15007','unid',5.63,3.0,null),
  ('Rejillas obturables plástico negro 60mm (2u)',null,'Carpintería y Varios','Baron C89099','unid',2.6,2.0,null),
  ('Boca de carga agua c/venteo cromada 1½"',null,'Carpintería y Varios','Baron T13176','unid',50.0,1.0,null),
  ('Entrada agua potable cromada',null,'Carpintería y Varios','Baron B29029','unid',15.0,1.0,null),
  ('Rejillas orientables negro 60mm (2u)',null,'Carpintería y Varios','Baron C89943','unid',2.6,2.0,null),
  ('Rejilla aluminio 14"x6" retorno',null,'Carpintería y Varios',null,'unid',36.71,1.0,null),
  ('Botazo plástico blanco (27mts)',null,'Carpintería y Varios','Profilplast','mts',10.0,27.0,null),
  ('Fleje inox para botazo (27mts)',null,'Carpintería y Varios','Profilplast','mts',12.89,27.0,null),
  ('Tornillos inox botazo cab.fresada (130u)',null,'Carpintería y Varios','Rebollar','unid',0.2,130.0,null),
  ('Stereo Apollo RA670','Fusion','Carpintería y Varios','Garmin','unid',908.0,1.0,'Orig: Stereo Fusion Apollo RA670'),
  ('Parlantes 6,5" FM-F65RW blancos (2u)','Fusion','Carpintería y Varios','Garmin','unid',279.0,2.0,'Orig: Parlantes 6,5" Fusion FM-F65RW blancos (2u)'),
  ('Parlantes 6,5" FM-F65RB negros (2u)','Fusion','Carpintería y Varios','Garmin','unid',279.0,2.0,'Orig: Parlantes 6,5" Fusion FM-F65RB negros (2u)'),
  ('Plotter Echomap UHD 92sv','Garmin','Carpintería y Varios','Garmin','unid',1512.0,1.0,'Orig: Plotter Garmin Echomap UHD 92sv'),
  ('VHF 110 Marine Audio','Garmin','Carpintería y Varios','Garmin','unid',613.0,1.0,'Orig: VHF 110 Marine Audio Garmin'),
  ('Matafuego 1kg',null,'Carpintería y Varios',null,'unid',93.0,2.0,null),
  ('Antirruido metalizado sala maquinas (20m²)',null,'Carpintería y Varios',null,'m2',61.32,20.0,null),
  ('Aire acondicionado Webasto 16000 BTU',null,'Carpintería y Varios','Baron','unid',2365.0,1.0,null),
  ('Extractores Jabsco 4" 12V Flexmount (2u)',null,'Carpintería y Varios','Trimer 240','unid',240.0,2.0,null),
  ('Ducto extractor 4" (2mts)',null,'Carpintería y Varios','Trimer 34959-0200','mts',7.9,2.0,null),
  ('Extractor Rule 3" 12V',null,'Carpintería y Varios','Trimer 140','unid',51.0,1.0,null),
  ('Ducto extractor 3" (2mts)',null,'Carpintería y Varios','Trimer 34959-0100','mts',5.75,2.0,null),
  ('Ducto aire AC 4" (6mts)',null,'Carpintería y Varios',null,'mts',7.9,6.0,null),
  ('Ducto aire AC 6" (6mts)',null,'Carpintería y Varios',null,'mts',12.0,6.0,null),
  ('Ducto calefacción 90mm (12mts)',null,'Carpintería y Varios','Zaneti','mts',18.5,12.0,null),
  ('Ducto calefacción 60mm (4mts)',null,'Carpintería y Varios','Zaneti','mts',12.5,4.0,null),
  ('Tubo bowthruster Ø150mm x1mt',null,'Carpintería y Varios','Craftsman','mts',175.0,1.0,'⚠️ REVISAR: viene x6m, verificar cant. usada'),
  ('Faro Jabsco 135SL c/control',null,'Carpintería y Varios',null,'unid',435.0,1.0,null),
  ('Antena VHF + base',null,'Carpintería y Varios',null,'unid',125.0,1.0,null),
  ('Antena TV Shakespeare',null,'Carpintería y Varios',null,'unid',140.0,1.0,null),
  ('Luz nav. roja Aquasignal Serie 33',null,'Carpintería y Varios','Trimer 33303-1','unid',35.5,1.0,null),
  ('Luz nav. verde Aquasignal Serie 33',null,'Carpintería y Varios','Trimer 33203-1','unid',35.5,1.0,null),
  ('Luz nav. estela Aquasignal Serie 33',null,'Carpintería y Varios',null,'unid',35.5,1.0,null),
  ('Luz fondeo Aquasignal Serie 34',null,'Carpintería y Varios','Trimer 34000-7','unid',35.5,1.0,null),
  ('Pisos',null,'Carpintería y Varios','Cantofil','m2',222.0,1,null),
  ('Combustible',null,'Carpintería y Varios','Comercial delta','lts',1.37931034475,400.0,'Precio corregido: combustible por litro; antes estaba cargado como total x400'),
  ('Servicio de Hidrogrúa de 8:00 a 16:00h',null,'Carpintería y Varios','Hidrogruas Florencia','global',413.7931034,1,null),
  ('Desmoldes y traslados',null,'Carpintería y Varios','De Giovani','global',1241.37931,1,null),
  ('Servicio de Grua 32HS',null,'Carpintería y Varios','Gruas delta','global',1434.482759,1,null),
  ('Plegado de tanques',null,'Carpintería y Varios','San gines','global',804.4137931,1,null),
  ('Armado de tanques',null,'Carpintería y Varios','Abadie','global',628.9655172,1,null),
  ('Enchapado',null,'Carpintería y Varios','Acuña','global',918.6206897,1,null),
  ('Fletes muebles',null,'Carpintería y Varios','Flete Oberti','global',350.0,1,null),
  ('Colchones',null,'Carpintería y Varios','Decor Yatchs','global',1000.0,1,null),
  ('Puerta corrediza',null,'Carpintería y Varios','Acrimold','unid',null,1.0,null),
  ('Cortes inox 3mm — escalones de salón',null,'Carpintería y Varios',null,'juego',null,1.0,'¿TODO ESTO ES MAXI HERRERO? CHECKEAR'),
  ('Chapa con logo — puerta de cockpit',null,'Carpintería y Varios',null,'unid',null,1.0,null),
  ('Corte letras "K 37"',null,'Carpintería y Varios',null,'juego',null,1.0,null),
  ('Corte letras "NOMBRE DEL BARCO"',null,'Carpintería y Varios',null,'juego',null,1.0,null),
  ('Corte logo',null,'Carpintería y Varios',null,'juego',null,1.0,null),
  ('Corte chapa de proa',null,'Carpintería y Varios',null,'unid',null,1.0,null),
  ('Cortes chapas de catalina (cuerpo y pivot)',null,'Carpintería y Varios',null,'juego',null,1.0,null);

  insert into panol_categorias (nombre, orden) select 'Carpintería y Varios',50 where not exists (select 1 from panol_categorias where lower(nombre)=lower('Carpintería y Varios'));
  insert into panol_categorias (nombre, orden) select distinct rubro,50 from _stg s where rubro<>'' and not exists (select 1 from panol_categorias c where lower(c.nombre)=lower(s.rubro));
  insert into panol_proveedores (nombre, activo) select distinct proveedor,true from _stg s where proveedor<>'' and not exists (select 1 from panol_proveedores p where lower(p.nombre)=lower(s.proveedor));
  insert into panol_materiales (descripcion, categoria_id, proveedor_id, proveedor, unidad_medida, precio_unitario, moneda, alias, notas, revisado, activo, origen)
  select s.descripcion,
         coalesce((select c.id from panol_categorias c where lower(c.nombre)=lower(s.rubro) order by c.parent_id nulls first limit 1),
                  (select c.id from panol_categorias c where lower(c.nombre)=lower('Carpintería y Varios') limit 1)),
         (select p.id from panol_proveedores p where lower(p.nombre)=lower(s.proveedor) limit 1),
         nullif(s.proveedor,''), nullif(s.unidad,''), s.precio, case when s.precio is not null then 'USD' end,
         nullif(s.alias,''), nullif(s.observaciones,''), false, true, 'import-k37'
  from _stg s where not exists (select 1 from panol_materiales m where lower(btrim(m.descripcion))=lower(btrim(s.descripcion)) and m.activo);
  delete from panol_material_modelo where modelo=v_modelo and material_id not in (
    select m.id from panol_materiales m join panol_categorias c on c.id=m.categoria_id where m.revisado and lower(c.nombre) like '%vidrio%');
  insert into panol_material_modelo (material_id, modelo, cantidad, variante)
  select m.id, v_modelo, coalesce(s.cantidad,1), 'standard'
  from _stg s join lateral (select mm.id from panol_materiales mm where lower(btrim(mm.descripcion))=lower(btrim(s.descripcion)) and mm.activo order by mm.created_at limit 1) m on true
  on conflict (material_id, modelo, variante) do update set cantidad=excluded.cantidad;
end $$;
