-- ===== K55 BASE MATRIZ (solo STD, 250 items) — REEMPLAZA modelo 55 =====
do $$
declare v_modelo text := '55';
begin
  create temp table _stg(descripcion text, alias text, rubro text, proveedor text, cantidad numeric, observaciones text) on commit drop;
  insert into _stg values
  ('Ecosonda',null,'Carpintería y Varios',null,1.0,'AIRMAR P319 (010-10194-21) / [STD]'),
  ('Radio VHF',null,'Carpintería y Varios',null,1.0,'Garmin VHF 215 Marine Radio (010-02097-00) Garmin GHS 11 wired VHF Handset (010-01759-00) / [STD]'),
  ('Anafe CTR432','Samsung','Electricidad',null,1.0,'[STD]'),
  ('Horno NV7B4040VAS/BG','Samsung','Electricidad',null,1.0,'EMPOTRABLE / [STD]'),
  ('Barral de ropero',null,'Carpintería y Varios',null,1.0,'Vestidor y camarote proa / [STD]'),
  ('Bisagra tipo piano',null,'Carpintería y Varios',null,1.5,'Muebles babor salon, estribor camarote popa / [STD]'),
  ('Bisagras codo 0',null,'Carpintería y Varios',null,20.0,'Puertas alacenas / [STD]'),
  ('Bisagras codo 9',null,'Carpintería y Varios',null,34.0,'Puertas roperos / [STD]'),
  ('Bisagras ocultas de puerta',null,'Carpintería y Varios',null,21.0,'7 puertas / [STD]'),
  ('Bisagras ocultas de puerta - OPCIONAL sin vestidor',null,'Carpintería y Varios',null,18.0,'6 puertas / [STD]'),
  ('Cerraduras de puertas / BRONZEN',null,'Carpintería y Varios',null,7.0,'https://www.mercadolibre.com.ar/cerradura-magnetica-puerta-placa-acero-inoxidable-iman-color-zincada/p/MLA56662348 / [STD]'),
  ('Cerraduras de puertas / BRONZEN - OPCIONAL sin vestidor',null,'Carpintería y Varios',null,6.0,'https://www.mercadolibre.com.ar/cerradura-magnetica-puerta-placa-acero-inoxidable-iman-color-zincada/p/MLA56662348 / [STD]'),
  ('Correderas de cajon - LARGO 200mm Cierre suave',null,'Carpintería y Varios',null,2.0,'[STD]'),
  ('Correderas de cajon - LARGO 250mm Cierre suave',null,'Carpintería y Varios',null,3.0,'[STD]'),
  ('Correderas de cajon - LARGO 400mm Cierre suave',null,'Carpintería y Varios',null,6.0,'[STD]'),
  ('Correderas de cajon - LARGO 450mm Cierre suave',null,'Carpintería y Varios',null,6.0,'[STD]'),
  ('Correderas ocultas Bronzen LARGO 500mm',null,'Carpintería y Varios',null,1.0,'https://www.mercadolibre.com.ar/sistema-corredera-pocket-door-mueble-oculto-500mm-par-color-negro/p/MLA48512423#polycard_client=search-desktop&be_origin=backend&search_layout=grid&position=3&type=product&tracking_id=fab1bd4e-5ba8-450b-89e1-d5f2ab5188d3&wid=MLA2055674764&sid=search / [STD]'),
  ('Imanes para puertas de muebles',null,'Carpintería y Varios',null,46.0,'[STD]'),
  ('Picaportes de puertas - OPCIONAL sin vestidor',null,'Carpintería y Varios',null,12.0,'6 puertas / [STD]'),
  ('Picaportes de puertas ¿?',null,'Carpintería y Varios',null,14.0,'7 puertas / [STD]'),
  ('Resorte a gas para puertas de alacenas - 60N',null,'Carpintería y Varios',null,6.0,'Hafele 60N / [STD]'),
  ('Resorte a gas para puertas de alacenas - 80N',null,'Carpintería y Varios',null,4.0,'Hafele 80N / [STD]'),
  ('Soporte elevador TV - JC35VT-1000',null,'Carpintería y Varios',null,1.0,'Soporte TV Salon / [STD]'),
  ('Soporte TV plano',null,'Carpintería y Varios',null,3.0,'Camarote PROA, MEDIO, POPA / [STD]'),
  ('Soportes de barral de ropero',null,'Carpintería y Varios',null,4.0,'Vestidor y camarote proa / [STD]'),
  ('Baterias de motor, MODELO, CANTIDAD??',null,'Carpintería y Varios',null,2.0,'??? / [STD]'),
  ('Baterias de servicio, MODELO, CANTIDAD??',null,'Carpintería y Varios',null,1.0,'??? / [STD]'),
  ('GENSET 17kVA, CONFIRMAR','Kohler','Carpintería y Varios',null,1.0,'??? / [STD]'),
  ('PARLANTES, STEREOS, EQUIPO DE AUDIO???',null,'Carpintería y Varios',null,1.0,'??? / [STD]'),
  ('Tableros electricos COSTA, modelo??',null,'Carpintería y Varios',null,2.0,'??? / [STD]'),
  ('Limpia Parabrisas pantograficos, detallar motor, modelo, etc',null,'Carpintería y Varios',null,2.0,'??? / [STD]'),
  ('Tanques de combustible',null,'Carpintería y Varios','Astillero',2.0,'??? / [STD]'),
  ('Central hidraulica, modelo ¿? flaps, tender lift',null,'Carpintería y Varios','Astillero',2.0,'??? / [STD]'),
  ('Tiras de led iluminacion interior',null,'Carpintería y Varios','Astillero',1.0,'tipo, largo ??? / [STD]'),
  ('Perfiles de aluminio para tiras led',null,'Carpintería y Varios','Astillero',1.0,'tipo, largo ??? / [STD]'),
  ('Calefactor - Autoterm - Rejilla D60 Obturable Negra',null,'Sanitarios','Baron',4.0,'C89099 / [STD]'),
  ('Calefactor - Autoterm - Rejilla D90 Obturable Negra',null,'Sanitarios','Baron',4.0,'C89108 / [STD]'),
  ('Calefactor - Autoterm - Rejilla D60 Orientable Negra',null,'Sanitarios','Baron',2.0,'C89943 / [STD]'),
  ('Tender lift OPACMARE 5222/90.04',null,'Carpintería y Varios','Astillero',2.0,'STD / [STD]'),
  ('AUTOMATICO JOHNSON PUMP 20AMP',null,'Electricidad','Flojumar',4.0,'BOMBAS DE ACHIQUE / [STD]'),
  ('BOMBA DE ACHIQUE JHONSON PUMP 12V 2200GPH',null,'Electricidad','Flojumar',3.0,'[STD]'),
  ('BOMBA DE ACHIQUE JHONSON PUMP 12V 4000GPH',null,'Electricidad','Flojumar',1.0,'[STD]'),
  ('BOMBA DE ACHIQUE JOHNSON PUMP 12V 2200 GPH HEAVY DUTY',null,'Sanitarios',null,1.0,'BOMBAS DE ACHIQUE / [STD]'),
  ('BOMBA DE ACHIQUE JOHNSON PUMP 12V 4000 GPH (HEAVY DUTY)',null,'Electricidad','Flojumar',5.0,'BOMBAS DE ACHIQUE / [STD]'),
  ('VALVULA DE UN SOLO SENTIDO PARA BOMBAS DE ACHIQUE 1 1/2"',null,'Sanitarios','Casa Iriarte',2.0,'VALRET1/2 COM / [STD]'),
  ('VALVULA DE UN SOLO SENTIDO PARA BOMBAS DE ACHIQUE 1"',null,'Sanitarios','Casa Iriarte',4.0,'VALRET 1 COM / [STD]'),
  ('ADAPTADOR TUNEL STERNTHURSTER 250MM',null,'Mecánica','Flojumar',1.0,'[STD]'),
  ('ANODO PERFORMANCE METAL USA PARA EJE 2 3/4"',null,'Mecánica','Flojumar',2.0,'[STD]'),
  ('ANODO PERFORMANCE METAL USA PARA FLAP BARRA',null,'Mecánica','Flojumar',2.0,'[STD]'),
  ('ANODO PERFORMANCE METAL USA PARA TIMON 95MM',null,'Mecánica','Flojumar',2.0,'[STD]'),
  ('ANODO PERFORMANCE METAL USA PARA: EJE 2 3/4" -- PARA TIMON 95MM -- FLAP BARRA -- PLACA 30X15',null,'Mecánica','Flojumar',7.0,'[STD]'),
  ('ANODO PERFORMANCE METAL USA PLACA 30X15',null,'Mecánica','Flojumar',1.0,'[STD]'),
  ('ANTENA VHF SHAKESPEARE 2.4M CON BASE ACERO INOXIDABLE',null,'Electricidad','Flojumar',2.0,'ANTENAS / [STD]'),
  ('BASE ANTENA VHF ACERO INOXIDABLE',null,'Electricidad','Flojumar',2.0,'ANTENAS / [STD]'),
  ('BOCINA MARINCO DOBLE ACERO INOX ELECTRICA 12V',null,'Electricidad','Flojumar',1.0,'[STD]'),
  ('BOWTHURSTER DOBLE HELICE 6,5 KW 250MM 12V','Quick','Electricidad','Flojumar',1.0,'[STD]'),
  ('Cadena calibrada 10MM galvanizada importada',null,'Mecánica','Flojumar',50.0,'[STD]'),
  ('CONTROL CON INDICADOR SEGUNDA ESTACION LENCO',null,'Electricidad','Flojumar',1.0,'FLAPS ELECTRICOS LENCO / [STD]'),
  ('CONTROL FARO SEGUNDA ESTACION MARINCO',null,'Electricidad','Flojumar',1.0,'[STD]'),
  ('CONTROL MULTICONTROL VICTRON ENERGY CON CABLE',null,'Electricidad','Flojumar',1.0,'[STD]'),
  ('DESTORCEDOR TIPO "GUSANO" ACERO INOXIDABLE CADENA 10-12MM',null,'Mecánica','Flojumar',1.0,'[STD]'),
  ('FARO MARINCO 12V DIRIGIBLE',null,'Electricidad','Flojumar',1.0,'[STD]'),
  ('LUZ BANDA ROJA LED',null,'Electricidad','Flojumar',1.0,'KIT HELLA MARINE LED / [STD]'),
  ('LUZ BANDA VERDE LED',null,'Electricidad','Flojumar',1.0,'KIT HELLA MARINE LED / [STD]'),
  ('LUZ FONDEO LED BLANCA 360',null,'Electricidad','Flojumar',1.0,'KIT HELLA MARINE LED / [STD]'),
  ('LUZ NAVEGACION PROA BLANCA LED',null,'Electricidad','Flojumar',1.0,'KIT HELLA MARINE LED / [STD]'),
  ('LUZ POPA LED BLANCA',null,'Electricidad','Flojumar',1.0,'KIT HELLA MARINE LED / [STD]'),
  ('MALACATE ITALY 1500 WATTS 12V ACERO INOXIDABLE','Quick','Electricidad','Flojumar',1.0,'[STD]'),
  ('Metros de botazo',null,'Carpintería y Varios',null,44.0,'Mismo modelo que el K52 / [STD]'),
  ('Pantalla tactil de timonera interior, modelo?? accesorios??',null,'Carpintería y Varios',null,1.0,'modelo?? accesorios?? / [STD]'),
  ('Plotter de flybridge, modelo?? accesorios??',null,'Carpintería y Varios',null,1.0,'modelo?? accesorios?? / [STD]'),
  ('SISTEMA FLAP LENCO 24 X 16 " SIN CONTROL DOBLE PISTON',null,'Electricidad','Flojumar',1.0,'CONTROL CON INDICADOR PRIMERA ESTACION LENCO / CONTROL CON INDICADOR SEGUNDA ESTACION LENCO / [STD]'),
  ('STERN THURSTER DOBLE HELICE 6,5KW 250MM 12V','Quick','Electricidad','Flojumar',1.0,'[STD]'),
  ('Tubo bowthruster D= 250mm, e= 9 mm, L = 1,50 m',null,'Mecánica',null,1.0,'[STD]'),
  ('CAVA 8 BOTELLAS PHILCO - PHCAV08N2',null,'Electricidad',null,1.0,'https://www.philco.com.ar/products/cavas/94PHCAV08N2?srsltid=AfmBOoplwU3k_1q1kg7FczB9AeICWNUXnRLehyzwn8GPbZH1MsdEn-hw / [STD]'),
  ('Microondas MG23F3K3TAS/BG GRILL','Samsung','Electricidad',null,1.0,'[STD]'),
  ('Resorte a gas para escalera - MODELO A DEFINIR',null,'Carpintería y Varios',null,2.0,'MODELO A DEFINIR / [STD]'),
  ('AIRE ACONCIONADO FRIO CALOR PLATINUM 16.000 BTU',null,'Electricidad','Flojumar',3.0,'CON CONTROL, CABLE Y CONTROL INALAMBRICO / [STD]'),
  ('AIRE ACONCIONADO FRIO CALOR PLATINUM 6.000 BTU',null,'Electricidad','Flojumar',1.0,'CON CONTROL, CABLE Y CONTROL INALAMBRICO / [STD]'),
  ('BOMBA AIRE ACONDICIONADO 220V SUMERGIBLE 500 GPM',null,'Electricidad','Flojumar',4.0,'[STD]'),
  ('Bacha Johnson Z52, PROFUNDIDAD 15cm (cocina)',null,'Carpintería y Varios',null,1.0,'PROFUNDIDAD 15cm, Con sopapa / [STD]'),
  ('Bacha Piazza A426 Blanco',null,'Carpintería y Varios',null,2.0,'Baños proa y popa / [STD]'),
  ('CAJA DUCHA JOHNSON PUMP 12V 1000 GPH USA',null,'Electricidad','Flojumar',2.0,'[STD]'),
  ('CAÑERIA DE TERMOFUSIÓN 25⌀ 14 TIRAS',null,'Sanitarios',null,56.0,'TERMOFUSION / [STD]'),
  ('CAÑO AZUL WX7152','Whale','Sanitarios',null,60.0,'ITEM WHALE / [STD]'),
  ('CAÑO POLIAMIDA REFORZADO DE 1/4"',null,'Sanitarios','Casa Iriarte',2.0,'M PA6SP1/4 / [STD]'),
  ('CAÑO ROJO WX7154','Whale','Sanitarios',null,50.0,'ITEM WHALE / [STD]'),
  ('CODO 25⌀ A 90',null,'Sanitarios',null,8.0,'[STD]'),
  ('CODO CON ESPIGA WX1522','Whale','Sanitarios',null,10.0,'ITEM WHALE / [STD]'),
  ('CODO H H 1 1/4" PLASTICO',null,'Sanitarios','Casa Iriarte',1.0,'[STD]'),
  ('CODO M.H DE 1 1/2" PLASTICO',null,'Sanitarios','Casa Iriarte',1.0,'PX COD90MH11/2 / [STD]'),
  ('CODO M.H DE BRONCE 1"',null,'Sanitarios','Casa Iriarte',1.0,'PX COD90MH11/2 / [STD]'),
  ('CODO M.H DE BRONCE 1/2"',null,'Sanitarios','Casa Iriarte',8.0,'C 116 1/2 FU / [STD]'),
  ('CODO M.H DE BRONCE 3/4"',null,'Sanitarios','Casa Iriarte',2.0,'C 116 1 FU / [STD]'),
  ('CODO WX1503',null,'Sanitarios',null,6.0,'ITEM WHALE / [STD]'),
  ('CONECTOR 25⌀ CON ROSCA HEMBRA',null,'Sanitarios',null,6.0,'TERMOFUSION / [STD]'),
  ('CUCHARA 1/2" BRONCE RANURADA',null,'Sanitarios',null,1.0,'OPCIONAL DUCHADOR Y BOMBA DE RIO / [STD]'),
  ('CUCHARAS DE BRONCE 104',null,'Sanitarios','Casa Iriarte',3.0,'REJ104 / [STD]'),
  ('CUPLA 25⌀',null,'Sanitarios',null,8.0,'TERMOFUSION / [STD]'),
  ('CUPLA DE BRONCE 1/2"',null,'Sanitarios',null,1.0,'C 103 1/2 FU / [STD]'),
  ('Duchador con barral Polca 0128.17 Cromado',null,'Carpintería y Varios',null,2.0,'Griferia 2 baños / [STD]'),
  ('DUCHADOR FRIO CALOR TWIST','Whale','Sanitarios','Flojumar',1.0,'[STD]'),
  ('EMPALME ESPIGA PARA MANGUERA 1" PLASTICO',null,'Sanitarios','Casa Iriarte',3.0,'[STD]'),
  ('ENTRERROSCA DE BRONCE DE 1"',null,'Sanitarios','Casa Iriarte',2.0,'C 112 1 FU / [STD]'),
  ('ENTRERROSCA DE BRONCE DE 1/2"',null,'Sanitarios','Casa Iriarte',4.0,'C 112 1/2 FU / [STD]'),
  ('ENTRERROSCA DE BRONCE DE 3/4"',null,'Sanitarios','Casa Iriarte',2.0,'C 112 3/4 FU / [STD]'),
  ('ENTRERROSCA DE PLASTICO 1/2"',null,'Sanitarios','Casa Iriarte',4.0,'PX ENTRR1/2 / [STD]'),
  ('ENTRERROSCA DE REDUCCION 3/4" X 1/2" PLASTICO',null,'Sanitarios','Casa Iriarte',1.0,'FAG-FIL-MED3/4 / [STD]'),
  ('Epuyén – Juego monocomando para mesada de cocina (cromado)',null,'Carpintería y Varios',null,1.0,'0411.04/L2-CR / [STD]'),
  ('Esféricas','Whale','Sanitarios',null,4.0,'ITEM WHALE / [STD]'),
  ('Juego monocomando para bañera y ducha Epuyén 0106/L2 Cromado',null,'Carpintería y Varios',null,2.0,'Griferia 2 baños / [STD]'),
  ('Juego monocomando para lavatorio Epuyén 0206/L2 Cromado',null,'Carpintería y Varios',null,2.0,'Griferia 2 baños / [STD]'),
  ('MANGUERA CRISTAL CON ALAMBRE 19 MM',null,'Sanitarios',null,65.0,'MANGUERAS / [STD]'),
  ('MANGUERA CRISTAL CON ALAMBRE 25 MM',null,'Sanitarios',null,65.0,'MANGUERAS / [STD]'),
  ('MANGUERA CRISTAL CON ALAMBRE 38 MM',null,'Sanitarios',null,50.0,'MANGUERAS / [STD]'),
  ('Percha Epuyén 0166/L2 Cromado',null,'Carpintería y Varios',null,4.0,'Griferia 2 baños / [STD]'),
  ('Portarrollo Epuyén 0167/L2 Cromado',null,'Carpintería y Varios',null,2.0,'Griferia 2 baños / [STD]'),
  ('RACOR H A CODO DE 1 1/2" PLASTICO',null,'Sanitarios','Casa Iriarte',5.0,'PX CODRAC11/2 / [STD]'),
  ('RACOR H A CODO DE 1" PLASTICO',null,'Sanitarios','Casa Iriarte',12.0,'PX CODRAC1H / [STD]'),
  ('RACOR H A CODO DE 1/2" PLASTICO',null,'Sanitarios','Casa Iriarte',5.0,'PX CODRAC11/2 / [STD]'),
  ('RACOR H A CODO DE 3/4" PLASTICO',null,'Sanitarios','Casa Iriarte',3.0,'PX CODRAC3/4H / [STD]'),
  ('RACOR M 1" X 25 MM BRONCE',null,'Sanitarios','Casa Iriarte',2.0,'C127 1X1 FU LR / [STD]'),
  ('RACOR M 3/4" BRONCE',null,'Sanitarios','Casa Iriarte',6.0,'[STD]'),
  ('RACOR M A CODO DE 1" PLASTICO',null,'Sanitarios','Casa Iriarte',3.0,'PX RACCOD90-1 / [STD]'),
  ('RACOR M A CODO DE 1/2" PLASTICO',null,'Sanitarios','Casa Iriarte',8.0,'PX RACCOD1/2M / [STD]'),
  ('RACOR M A CODO DE 3/4" PLASTICO',null,'Sanitarios','Casa Iriarte',2.0,'C 110 1 X 3/4 FL / [STD]'),
  ('RACOR M DE 1" PLASTICO',null,'Sanitarios','Casa Iriarte',5.0,'PX RACCOD90-1 / [STD]'),
  ('RACOR M DE 1/2" PLASTICO',null,'Sanitarios',null,2.0,'PX RAC1/2M / [STD]'),
  ('RACOR M DE 3/4" PLASTICO',null,'Sanitarios','Casa Iriarte',7.0,'PX RACCOD3/4M / [STD]'),
  ('RACOR M DE BRONCE 1 1/2" X 38 MM',null,'Sanitarios','Casa Iriarte',3.0,'C127 11/2X11/2 / [STD]'),
  ('REGULADOR DE AGUA AMARRA',null,'Electricidad','Flojumar',1.0,'[STD]'),
  ('T CON ESPIGA 1 1/2" PLASTICO',null,'Sanitarios','Casa Iriarte',2.0,'PX TEERAC11/2F / [STD]'),
  ('T CON ESPIGA ROSCA CENTRAL DE 1" PLASTICO',null,'Sanitarios','Casa Iriarte',2.0,'PX BUJRED3/4X1 / [STD]'),
  ('T CON ESPIGA WX1521','Whale','Sanitarios',null,11.0,'ITEM WHALE / [STD]'),
  ('T WX1502','Whale','Sanitarios',null,21.0,'ITEM WHALE / [STD]'),
  ('TANQUE ACUMULADOR PRESION FLOJET-JABSCO',null,'Electricidad','Flojumar',1.0,'[STD]'),
  ('TAPA TANQUE FORESTI SUARDI AGUA 1 1/2"',null,'Sanitarios','Flojumar',1.0,'[STD]'),
  ('TAPA TANQUE FORESTI SUARDI COMBUSTIBLE 2"',null,'Sanitarios','Flojumar',2.0,'[STD]'),
  ('TAPA TANQUE FORESTI SUARDI WASTE 1 1/2"',null,'Sanitarios','Flojumar',1.0,'[STD]'),
  ('TAPON ROSCA M DE 1/2" PLASTICO',null,'Sanitarios','Casa Iriarte',3.0,'PX TAN 1/2 / [STD]'),
  ('Tee 25⌀ CON ROSCA CENTRAL HEMBRA 1/2',null,'Sanitarios',null,16.0,'TERMOFUSION / [STD]'),
  ('TERMOTANQUE CAMCO 76 LITROS DUAL MARINO',null,'Electricidad','Flojumar',1.0,'[STD]'),
  ('Toallero Epuyén 0163/L2 Cromado',null,'Carpintería y Varios',null,2.0,'Griferia 2 baños / [STD]'),
  ('TOMA CROMADA 1 1/2"',null,'Sanitarios','Casa Iriarte',6.0,'TO11/2C / [STD]'),
  ('TOMA CROMADA 1"',null,'Sanitarios','Casa Iriarte',9.0,'TO1"C / [STD]'),
  ('TOMA CROMADA 3/4"',null,'Sanitarios','Casa Iriarte',6.0,'TO3/4C / [STD]'),
  ('TOMA PLASTICA 1"',null,'Sanitarios','Casa Iriarte',4.0,'TO1"POL / [STD]'),
  ('UNIÓN DOBLE 25⌀',null,'Sanitarios',null,4.0,'TERMOFUSION / [STD]'),
  ('UNION ROSCA H 1/2" WX1514','Whale','Sanitarios',null,19.0,'ITEM WHALE / [STD]'),
  ('UNION ROSCA M 1/2" WX1532','Whale','Sanitarios',null,23.0,'ITEM WHALE / [STD]'),
  ('UNION ROSCA M DE 1/2" BRONCE X CAÑO POLIAMIDA 1/4" CON TUERCA Y VIROLA',null,'Sanitarios','Casa Iriarte',1.0,'C 681/4X1/2 / [STD]'),
  ('VALVULA ESFERICA DE BRONCE 1"',null,'Sanitarios','Casa Iriarte',1.0,'VAE1J / [STD]'),
  ('VALVULA ESFERICA DE BRONCE 1/2"',null,'Sanitarios','Casa Iriarte',9.0,'VAE1/2J / [STD]'),
  ('VALVULA ESFERICA DE BRONCE 3/4"',null,'Sanitarios','Casa Iriarte',2.0,'VAE3/4J / [STD]'),
  ('CON ROSCA HEMBRA 1/2"','Whale','Sanitarios',null,1.0,'OPCIONAL DUCHADOR Y BOMBA DE RIO / [STD]'),
  ('CON ROSCA MACHO 1/2"','Whale','Sanitarios',null,1.0,'OPCIONAL DUCHADOR Y BOMBA DE RIO / [STD]'),
  ('ABRAZADERA INOX PARA MANGUERA 1 1/2"',null,'Sanitarios',null,38.0,'[STD]'),
  ('ABRAZADERA INOX PARA MANGUERA 1"',null,'Sanitarios',null,32.0,'[STD]'),
  ('ABRAZADERA INOX PARA MANGUERA 3/4"',null,'Sanitarios',null,44.0,'[STD]'),
  ('1 caño inox 316 de 1/2", L = 1,5 m',null,'Mecánica',null,1.0,'TANQUES / [STD]'),
  ('1 caño inox 316 de 3/4", L = 3 m',null,'Mecánica',null,1.0,'TANQUES / [STD]'),
  ('1 chapa de inox 316 de 3 x 1,5 m, espesor = 2 mm',null,'Mecánica',null,1.0,'TANQUES / [STD]'),
  ('1 cupla de inox 316 de 1 1/2"',null,'Mecánica',null,1.0,'TANQUES / [STD]'),
  ('1 cupla de inox 316 de 2"',null,'Mecánica',null,1.0,'TANQUES / [STD]'),
  ('1 niple de inox 316 de 1/2", L= 100 mm',null,'Mecánica',null,1.0,'TANQUES / [STD]'),
  ('1 niple de inox 316 de 3/4", L = 100 mm',null,'Mecánica',null,1.0,'TANQUES / [STD]'),
  ('2 bridas cuadrada inox 316, medidas 300 mm interior x 400 mm exterior, espesor = 1/4"',null,'Mecánica',null,2.0,'TANQUES / [STD]'),
  ('2 chapas de inox 316 de 2 x 1,25 m, espesor = 2 mm',null,'Mecánica',null,2.0,'TANQUES / [STD]'),
  ('2 chapas de inox 316 de 2 x 1,25 m, espesor = 3 mm',null,'Mecánica',null,2.0,'TANQUES / [STD]'),
  ('2 chapas inox 316 de 400 x 400 mm, espesor = 1/4"',null,'Mecánica',null,2.0,'TANQUES / [STD]'),
  ('3 cupla de inox 316 de 1 1/4"',null,'Mecánica',null,3.0,'TANQUES / [STD]'),
  ('3 cupla de inox 316 de 1/2"',null,'Mecánica',null,3.0,'TANQUES / [STD]'),
  ('3 cupla de inox 316 de 3/4"',null,'Mecánica',null,3.0,'TANQUES / [STD]'),
  ('5 chapas de inox 316 de 3 x 1,5 m, espesor = 3 mm',null,'Mecánica',null,5.0,'TANQUES / [STD]'),
  ('5 cupla de inox 316 de 1"',null,'Mecánica',null,5.0,'TANQUES / [STD]'),
  ('5 cupla de inox 316 de 1/4"',null,'Mecánica',null,5.0,'TANQUES / [STD]'),
  ('1 enchufe hembra',null,'Electricidad',null,1.0,'[STD]'),
  ('1 enchufe macho',null,'Electricidad',null,1.0,'[STD]'),
  ('1 rollo de cable negro 1.5mm',null,'Electricidad',null,100.0,'[STD]'),
  ('1 rollo de cable rojo 1.5mm',null,'Electricidad',null,100.0,'[STD]'),
  ('1 toma de 10 amp',null,'Electricidad',null,1.0,'[STD]'),
  ('10 mts de caño corrugado blanco',null,'Electricidad',null,10.0,'[STD]'),
  ('100 plaquetas',null,'Electricidad',null,100.0,'[STD]'),
  ('100 precintos',null,'Electricidad',null,100.0,'[STD]'),
  ('2 tomas cambre de 20 amp',null,'Electricidad',null,2.0,'[STD]'),
  ('3 cajas exteriores cambre',null,'Electricidad',null,3.0,'[STD]'),
  ('60 m de perfil de aluminio según foto (tengo muestra también)',null,'Electricidad',null,60.0,'[STD]'),
  ('80 m de tira de LED COB blanco cálido (2700K, +500 LED/m)',null,'Electricidad',null,80.0,'[STD]'),
  ('80 tapas o punteras de plástico para ese perfil de aluminio',null,'Electricidad',null,80.0,'[STD]'),
  ('CABLE TIPO MARINCO 3X10MM X METRO',null,'Electricidad','Flojumar',12.0,'[STD]'),
  ('CABLEADO A SALON',null,'Electricidad',null,1.0,'??? / [STD]'),
  ('CABLEADO B CAMAROTE PRINCIPAL',null,'Electricidad',null,1.0,'??? / [STD]'),
  ('CABLEADO C COCINA',null,'Electricidad',null,1.0,'??? / [STD]'),
  ('CABLEADO D CAMAROTE DE PROA',null,'Electricidad',null,1.0,'??? / [STD]'),
  ('Caja paso Roker Pr1005',null,'Electricidad',null,1.0,'162x212x81mm / [STD]'),
  ('Caja paso Roker Pr1010/106',null,'Electricidad',null,4.0,'300x230x106mm / [STD]'),
  ('FABRICADORA DE HIELO ISOTHERM WHITE ICE ACERO INOXIDABLE',null,'Electricidad','Flojumar',2.0,'? / [STD]'),
  ('FOOTSWICHT ITALY CON TAPA INOX EL PAR','Quick','Electricidad','Flojumar',1.0,'[STD]'),
  ('INSTRUMENTO AGUA/COMBUSTIBLE ARO CROMADO',null,'Electricidad','Flojumar',2.0,'? / [STD]'),
  ('INVERSOR CARGADOR VICTRON ENERGY MULTIPLUS 12V 3000W 120AMP',null,'Electricidad','Flojumar',1.0,'[STD]'),
  ('JOSTICK DOBLE ITALY','Quick','Electricidad','Flojumar',2.0,'CABLE Y DERIVACION 2 ESTACIONES QUICK / [STD]'),
  ('KIT TAPA + FICHA + FUNDA MARINCO',null,'Electricidad','Flojumar',1.0,'? / [STD]'),
  ('LLAVE CARLING MALACATE 2 PUNTOS (2 UNIDADES)',null,'Electricidad','Flojumar',2.0,'[STD]'),
  ('LLAVE CORTE BATERIA A DISTANCIA BLUE SEA SYSTEMS',null,'Electricidad','Flojumar',6.0,'Comprobar cantidad al terminar barco 1 / [STD]'),
  ('PANEL BOMBA DE ACHIQUE JOHNSON PUMP',null,'Sanitarios','Flojumar',5.0,'BOMBAS DE ACHIQUE / [STD]'),
  ('SENSOR 115CM CON ROSCA FLOTANTE AGUA/COMBUSTIBLE',null,'Electricidad','Flojumar',1.0,'[STD]'),
  ('SOLENOIDE ITALY 12V','Quick','Electricidad','Flojumar',1.0,'[STD]'),
  ('TERMICO MALACATE 130 AMP',null,'Electricidad','Flojumar',1.0,'[STD]'),
  ('TOMA TIERRA MARINCO GRANDE EMBUTIR',null,'Electricidad','Flojumar',1.0,'[STD]'),
  ('Victron, combinador de baterias cyrix-ct',null,'Electricidad','Flojumar',1.0,'Pendiente de compra 01/04 / [STD]'),
  ('Antirruido metalizado para sala de máquinas (Aislante acustico)',null,'Mecánica',null,30.0,'[STD]'),
  ('Barra de 2 1/2" x 1000 mm. Inox 316',null,'Mecánica',null,2.0,'[STD]'),
  ('Barra de 2 3/4" x 3000mm. Inox 316',null,'Mecánica',null,2.0,'[STD]'),
  ('Brida de 100 mm interior x 160 mm exterior x 3/8. Inox 316',null,'Mecánica',null,2.0,'[STD]'),
  ('Brida de 85 mm interior x 160 mm exterior x 3/8". Inox 316',null,'Mecánica',null,2.0,'[STD]'),
  ('Buje Duramax para eje de 2 3/4", 85.73 mm exterior, 279 mm largo',null,'Mecánica',null,3.0,'[STD]'),
  ('Bujes de bronce y goma para eje de 2 3/4"',null,'Mecánica','Parra',1.0,'Lo compra directamente torneria / [STD]'),
  ('Caño D. exterior = 90 mm, e = 4 mm, L = 1100 mm. Inox 316',null,'Mecánica',null,1.0,'[STD]'),
  ('Caño schedule 80, 3 1/2" nominal, L = 285 mm Inox 316',null,'Mecánica',null,4.0,'[STD]'),
  ('Recorte chapa de inox 316 de 400mm x 250mm x 1/2" de espesor',null,'Mecánica',null,2.0,'[STD]'),
  ('Recorte chapa de inox 316 según plantilla "Patas de gallo - K52", e = ?',null,'Mecánica',null,4.0,'[STD]'),
  ('Separador Agua-Gases 2" Centek 1020200 p/grupo GEN-SEP',null,'Mecánica','Trimer',1.0,'[STD]'),
  ('Silenciador de escape 2" Centek Vernalift 1500027w p/grupo',null,'Mecánica','Trimer',1.0,'[STD]'),
  ('Silenciador de escape 6" Centek 16X16',null,'Mecánica','Trimer',2.0,'[STD]'),
  ('Ducto p/extractor de 3"',null,'Electricidad','Trimer',3.0,'[STD]'),
  ('FILTRO PARA AGUA DE RIO CON SOPORTE Y ROSCA 1" (Genset?)',null,'Sanitarios','Casa Iriarte',1.0,'FAG-FIL-MED1IN / [STD]'),
  ('FILTRO PARA AGUA DE RIO CON SOPORTE Y ROSCA 3/4" (A.C. proa y popa)',null,'Electricidad','Casa Iriarte',2.0,'FAG-FIL-MED3/4 / [STD]'),
  ('FLEXIBLES MALLADOS PARA AGUA DE 1/2" X 40 CM',null,'Sanitarios','Casa Iriarte',8.0,'FLAG-AF2076-1/ / [STD]'),
  ('FLEXIBLES MALLADOS PARA AGUA DE 1/2" X 50 CM',null,'Sanitarios','Casa Iriarte',3.0,'FLAG-AF2076-1/ / [STD]'),
  ('HOLDING TANK MATROMARINE ITALIANO 73 LITROS 12V',null,'Sanitarios','Flojumar',1.0,'INCLUYE: BOMBA MACERADORA + FILTRO DE VENTEO + VENTEO + SENSOR DE NIVEL + MONITOR DE SENSOR DE NIVEL'),
  ('INODORO TECMA THETFORD SILENCE 2 PLUSG CON BIDET Y TAPA 12V',null,'Sanitarios','Flojumar',2.0,'INODOROS. HOLDING TANK / [STD]'),
  ('SOPAPA A CODO PARA BAÑERA',null,'Sanitarios','Casa Iriarte',7.0,'SOP11/2CO / [STD]'),
  ('Direccion electro asistida twin disk',null,'Electricidad',null,1.0,'[STD]'),
  ('SELLO LASDROP USA GENERACION 2 EJE 2-3/4" BOCINA 4"',null,'Mecánica','Flojumar',2.0,'SELLOS / [STD]'),
  ('BOMBA DUAL 10.4 GPM 12V JOHNSON PUMP',null,'Electricidad','Flojumar',1.0,'? / [STD]'),
  ('Bridas inox + bocina mecanizada y perforada',null,'Mecánica','Flojumar',2.0,'[STD]'),
  ('BUJES DE REDUCCION 1 1/2" X 1" PLASTICO',null,'Sanitarios','Casa Iriarte',1.0,'C 110 11/2 X 1 F / [STD]'),
  ('BUJES DE REDUCCION 1 1/2" X 3/4" PLASTICO',null,'Sanitarios','Casa Iriarte',2.0,'C 110 11/2 X 3/4 / [STD]'),
  ('BUJES DE REDUCCION 1 1/4" X 1" PLASTICO',null,'Sanitarios','Casa Iriarte',4.0,'PX BUJRED11/4> / [STD]'),
  ('BUJES DE REDUCCION 1" X 3/4" PLASTICO',null,'Sanitarios','Casa Iriarte',2.0,'PX BUJRED1X3/4 / [STD]'),
  ('BUJES DE REDUCCION 3/4" X 1/2" PLASTICO',null,'Sanitarios','Casa Iriarte',2.0,'C 110 3/4 X 1/2 / [STD]'),
  ('Extractores Rule 3" 12V',null,'Electricidad','Trimer',2.0,'[STD]'),
  ('Pie de tablón Okume',null,'Mecánica',null,300.0,'Chequear cantidad real en barco 4 / [STD]'),
  ('Placa de honeycomb (terciado de 6 mm + núcleo de panal de abeja de 15 mm + terciado de 6 mm) de 1,2 mts x 2,45 mts',null,'Mecánica',null,22.0,'? / [STD]'),
  ('PLAQUETA PARA PRECINTO',null,'Sanitarios',null,500.0,'VARIOS / [STD]'),
  ('PRECINTO DE 35 CM',null,'Sanitarios',null,700.0,'VARIOS / [STD]'),
  ('Defensas con cabo 8mm - 4m',null,'Carpintería y Varios',null,6.0,'[STD]'),
  ('Cabos Amarre 18mm - 12mts',null,'Carpintería y Varios',null,4.0,'[STD]'),
  ('Tambucho de proa - MODELO???',null,'Carpintería y Varios',null,1.0,'[STD]'),
  ('Pasamanos INOX',null,'Carpintería y Varios',null,1.0,null);

  insert into panol_categorias (nombre, orden) select 'Carpintería y Varios',50 where not exists (select 1 from panol_categorias where lower(nombre)=lower('Carpintería y Varios'));
  insert into panol_categorias (nombre, orden) select distinct rubro,50 from _stg s where rubro<>'' and not exists (select 1 from panol_categorias c where lower(c.nombre)=lower(s.rubro));
  insert into panol_proveedores (nombre, activo) select distinct proveedor,true from _stg s where proveedor<>'' and not exists (select 1 from panol_proveedores p where lower(p.nombre)=lower(s.proveedor));
  insert into panol_materiales (descripcion, categoria_id, proveedor_id, proveedor, alias, notas, revisado, activo, origen)
  select s.descripcion,
         coalesce((select c.id from panol_categorias c where lower(c.nombre)=lower(s.rubro) order by c.parent_id nulls first limit 1),
                  (select c.id from panol_categorias c where lower(c.nombre)=lower('Carpintería y Varios') limit 1)),
         (select p.id from panol_proveedores p where lower(p.nombre)=lower(s.proveedor) limit 1),
         nullif(s.proveedor,''), nullif(s.alias,''), nullif(s.observaciones,''), false, true, 'import-k55'
  from _stg s where not exists (select 1 from panol_materiales m where lower(btrim(m.descripcion))=lower(btrim(s.descripcion)) and m.activo);
  delete from panol_material_modelo where modelo=v_modelo;
  insert into panol_material_modelo (material_id, modelo, cantidad, variante)
  select m.id, v_modelo, coalesce(s.cantidad,1), 'standard'
  from _stg s join lateral (select mm.id from panol_materiales mm where lower(btrim(mm.descripcion))=lower(btrim(s.descripcion)) and mm.activo order by mm.created_at limit 1) m on true
  on conflict (material_id, modelo, variante) do update set cantidad=excluded.cantidad;
end $$;