// Plantillas de tareas importadas desde Excel
// K42: 310 tareas / 14 procesos
// K52: 102 tareas / 8 procesos

export const PLANTILLA_K42 = [
  {
    nombre: "Matrices",
    orden: 1,
    color: "#8b5cf6",
    dias_estimados: 15,
    tareas: [
      { nombre: "Preparar Matriz de Casco con postizos", orden: 1, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carp. Extra" },
      { nombre: "Preparar Matriz de Cubierta con postizos", orden: 2, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carp. Extra" },
      { nombre: "Laminado de Casco", orden: 3, horas_estimadas: 80.0, personas_necesarias: 5, observaciones: "Plastico" },
      { nombre: "Laminado de Cubierta", orden: 4, horas_estimadas: 64.0, personas_necesarias: 4, observaciones: "Plastico" },
      { nombre: "Preparar matrices de interior con postizos", orden: 5, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carp. Extra" },
      { nombre: "Laminado de piezas de interiores", orden: 6, horas_estimadas: 40.0, personas_necesarias: 4, observaciones: "Plastico" },
      { nombre: "Preparar de matrices de contratechos con postizos", orden: 7, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carp. Extra" },
      { nombre: "Laminado de piezas de contratechos", orden: 8, horas_estimadas: 32.0, personas_necesarias: 4, observaciones: "Plastico" },
      { nombre: "Armado de grilla Long.", orden: 9, horas_estimadas: 16.0, personas_necesarias: 2, observaciones: "Carp. Extra" },
      { nombre: "Laminado de Grilla Long.", orden: 10, horas_estimadas: 6.0, personas_necesarias: 3, observaciones: "Plastico" },
      { nombre: "Armado grilla transversal y caños de desmolde, sacar bulones de postizos", orden: 11, horas_estimadas: 16.0, personas_necesarias: 2, observaciones: "Carp. Extra" },
      { nombre: "Laminado de grilla transversal y caños de desmolde", orden: 12, horas_estimadas: 6.0, personas_necesarias: 3, observaciones: "Plastico" },
    ],
  },
  {
    nombre: "Preparado abajo",
    orden: 2,
    color: "#64748b",
    dias_estimados: 20,
    tareas: [
      { nombre: "Preparado de bases de casco e imbornales", orden: 1, horas_estimadas: 8.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Preparado de mamparos segun plantilla", orden: 2, horas_estimadas: 16.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Preparado de tiranteria de pisos segun plano", orden: 3, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Hacer tapas de inspeccion de sentina, camas y sillon", orden: 4, horas_estimadas: 6.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Ensamblar tomas de aire de sala de maquinas", orden: 5, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Armar estructura de cabina HT", orden: 6, horas_estimadas: 6.0, personas_necesarias: 1, observaciones: "Carp. Grueso" },
      { nombre: "Ensamblar contratecho de cabina HT", orden: 7, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Ensamblar techo corredizo", orden: 8, horas_estimadas: 8.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Sellar y pintar cabina de HT", orden: 9, horas_estimadas: 40.0, personas_necesarias: 2, observaciones: "Plastico" },
      { nombre: "Ensamblar Baños", orden: 10, horas_estimadas: 8.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Hacer cortes de inspeccion que falten en piezas de interior", orden: 11, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Cortar luces y tapas de inspeccion de contratechos", orden: 12, horas_estimadas: 6.0, personas_necesarias: 1, observaciones: "Carp. Grueso" },
      { nombre: "Ajustar tapizados de techo de proa y mandar a tapizar", orden: 13, horas_estimadas: 7.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Ajustar tapizados de techo de salon y mandar a tapizar", orden: 14, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Ajustar tapizados de techo de popa y mandar a tapizar", orden: 15, horas_estimadas: 8.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Ajustar bandeau de cama de proa, poner liston y mandar a tapizar", orden: 16, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Ajustar bandeau de camas de popa, poner liston y mandar a tapizar", orden: 17, horas_estimadas: 5.0, personas_necesarias: 1, observaciones: "Carp. Grueso" },
      { nombre: "Hacer mascaras de sillon y mandar a tapizar", orden: 18, horas_estimadas: 16.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Ajustar mascara de sillones de cockpit", orden: 19, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Hacer pisos de sala de maquinas", orden: 20, horas_estimadas: 8.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Hacer mesada de corian de cocina (calar anafe y bacha)", orden: 21, horas_estimadas: 24.0, personas_necesarias: 1, observaciones: "Carpint. Fino" },
      { nombre: "Hacer mesadas de corian de baño de proa", orden: 22, horas_estimadas: 16.0, personas_necesarias: 1, observaciones: "Carpint. Fino" },
      { nombre: "Hacer mesadas de corian de baño de popa", orden: 23, horas_estimadas: 16.0, personas_necesarias: 1, observaciones: "Carpint. Fino" },
      { nombre: "Hacer puertas de bajo mesada de cockpit", orden: 24, horas_estimadas: 24.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
    ],
  },
  {
    nombre: "Cubierta",
    orden: 3,
    color: "#0ea5e9",
    dias_estimados: 20,
    tareas: [
      { nombre: "DESMOLDE DE CUBIERTA, nivelar", orden: 1, horas_estimadas: 4.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Pasar maquina en brida de cubierta", orden: 2, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Plastico" },
      { nombre: "Reparar zona de cockpit en cubierta (parte 1)", orden: 3, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carp. Grueso" },
      { nombre: "Laminar reparacion de cockpit en cubierta (Parte 1)", orden: 4, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Plastico" },
      { nombre: "Armar tiranteria de techo Proa", orden: 5, horas_estimadas: 6.0, personas_necesarias: 1, observaciones: "Carp. Grueso" },
      { nombre: "Reparar zona de cockpit en cubierta (parte 2)", orden: 6, horas_estimadas: 6.0, personas_necesarias: 1, observaciones: "Carp. Grueso" },
      { nombre: "Laminar reparacion de cockpit en cubierta (Parte 2)", orden: 7, horas_estimadas: 6.0, personas_necesarias: 1, observaciones: "Plastico" },
      { nombre: "Armar tiranteria de techo Salon", orden: 8, horas_estimadas: 6.0, personas_necesarias: 1, observaciones: "Carp. Grueso" },
      { nombre: "Laminar tiranteria de techo", orden: 9, horas_estimadas: 6.0, personas_necesarias: 1, observaciones: "Plastico" },
      { nombre: "Armar tiranteria de techo Popa", orden: 10, horas_estimadas: 6.0, personas_necesarias: 1, observaciones: "Carp. Grueso" },
      { nombre: "Armar bases de cubierta", orden: 11, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Laminar bases de cubierta", orden: 12, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Plastico" },
      { nombre: "Antirruido de cubierta en sala de maquinas", orden: 13, horas_estimadas: 8.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Electricidad de cubierta y calefaccion", orden: 14, horas_estimadas: 20.0, personas_necesarias: 2, observaciones: "Electricista" },
      { nombre: "Pegar contratechos (usar plantillas)", orden: 15, horas_estimadas: 6.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Terminar marco de entrada de cubierta", orden: 16, horas_estimadas: 12.0, personas_necesarias: 1, observaciones: "Plastico" },
    ],
  },
  {
    nombre: "Casco",
    orden: 4,
    color: "#3b82f6",
    dias_estimados: 25,
    tareas: [
      { nombre: "DESMOLDE DE CASCO, nivelar casco", orden: 1, horas_estimadas: 4.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Armado de bases de casco e imbornales", orden: 2, horas_estimadas: 24.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Cortar bowthruster y laminar tubo", orden: 3, horas_estimadas: 16.0, personas_necesarias: 1, observaciones: "Plastico" },
      { nombre: "Presentar mamparo principal (G1, G2 y G3)", orden: 4, horas_estimadas: 4.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Laminado de bases de casco", orden: 5, horas_estimadas: 12.0, personas_necesarias: 1, observaciones: "Plastico" },
      { nombre: "Presentar mamparo de sala de maquinas (G5 y G6)", orden: 6, horas_estimadas: 4.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Armado de tiranteria de pisos de salon y camarote de popa", orden: 7, horas_estimadas: 4.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Laminado de tiranteria de pisos, mamparo principal y mamparo de sala de maquinas", orden: 8, horas_estimadas: 10.0, personas_necesarias: 1, observaciones: "Plastico" },
      { nombre: "Pintar de sentina y bandas", orden: 9, horas_estimadas: 8.0, personas_necesarias: 1, observaciones: "Plastico" },
      { nombre: "Etapa 1 de Sanitarios", orden: 10, horas_estimadas: 36.0, personas_necesarias: 2, observaciones: "Sanitarista" },
      { nombre: "Ubicar, nivelar y pegar salon, agregar tirantes faltantes", orden: 11, horas_estimadas: 4.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Presentar Mamparo de proa del Salon (G4)", orden: 12, horas_estimadas: 4.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Ubicar, nivelar y pegar camarote de Popa, agregar tirantes faltantes", orden: 13, horas_estimadas: 6.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Laminar mamparo G4, salon y camarote de popa", orden: 14, horas_estimadas: 12.0, personas_necesarias: 1, observaciones: "Plastico" },
      { nombre: "Ubicar, nivelar y pegar camarote de Proa, agregar tirantes faltantes", orden: 15, horas_estimadas: 6.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Armar tiranteria de apoyo de baño de popa", orden: 16, horas_estimadas: 5.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Laminar camarote de proa y tiranteria de baño de popa", orden: 17, horas_estimadas: 6.0, personas_necesarias: 1, observaciones: "Plastico" },
      { nombre: "Pegar bandas de salon y cocina en zona de ventanas", orden: 18, horas_estimadas: 6.0, personas_necesarias: 1, observaciones: "Carp. Grueso" },
      { nombre: "Presentar Mamparo de camarote de Proa babor (G8)", orden: 19, horas_estimadas: 3.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Laminar mamparo G8", orden: 20, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Plastico" },
      { nombre: "Ubicar, nivelar y pegar baño de popa", orden: 21, horas_estimadas: 5.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Cortar ventanas de casco de salon y cocina", orden: 22, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carp. Grueso" },
      { nombre: "Ubicar, nivelar y pegar baño de proa", orden: 23, horas_estimadas: 5.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Presentar y pegar columna de plastico mamparo de baño de proa", orden: 24, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carp. Grueso" },
      { nombre: "Presentar y pegar mamparos de baño de proa", orden: 25, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carp. Grueso" },
      { nombre: "Presentar y pegar mamparo de baño de popa", orden: 26, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carp. Grueso" },
    ],
  },
  {
    nombre: "Despues del ensamble",
    orden: 5,
    color: "#10b981",
    dias_estimados: 30,
    tareas: [
      { nombre: "ENSAMBLE CASCO-CUBIERTA", orden: 1, horas_estimadas: 16.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Cubrir piso de cockpit con pisos de trabajo", orden: 2, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Laminar union casco-cubierta y mamparos", orden: 3, horas_estimadas: 16.0, personas_necesarias: 1, observaciones: "Plastico" },
      { nombre: "Pintar reparacion de piso de cockpit", orden: 4, horas_estimadas: 80.0, personas_necesarias: null, observaciones: "Pintura" },
      { nombre: "Nivelar contratechos en zona de asientos de mueble", orden: 5, horas_estimadas: 8.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Ajustar mueble de cockpit y llevar a repintar", orden: 6, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Pintar marco de entrada al salon", orden: 7, horas_estimadas: 32.0, personas_necesarias: null, observaciones: "Pintura" },
      { nombre: "Pulir zonas de pegado de laterales de cubierta", orden: 8, horas_estimadas: 5.0, personas_necesarias: null, observaciones: "Plastico" },
      { nombre: "Hacer corte para selectoras automaticas", orden: 9, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Poner postizos de proa p/HT y pestaña de apoyo de vidrios laterales", orden: 10, horas_estimadas: 10.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Cortar ojos de buey y pegar bandas", orden: 11, horas_estimadas: 10.0, personas_necesarias: 1, observaciones: "Carp. Grueso" },
      { nombre: "Alinear y pegar cabina HT", orden: 12, horas_estimadas: 5.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Laminar cabina HT en Proa", orden: 13, horas_estimadas: 12.0, personas_necesarias: null, observaciones: "Plastico" },
      { nombre: "Ajustar planchada", orden: 14, horas_estimadas: 14.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Poner tinteros", orden: 15, horas_estimadas: 10.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Laminar contratechos y bandas", orden: 16, horas_estimadas: 8.0, personas_necesarias: 1, observaciones: "Plastico" },
      { nombre: "Pintar cabina de HT", orden: 17, horas_estimadas: 24.0, personas_necesarias: null, observaciones: "Pintura" },
      { nombre: "Poner pieza de plastico de banda, cortar ventana y ojo de buey", orden: 18, horas_estimadas: 8.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Pintar union de cabina HT en Proa", orden: 19, horas_estimadas: 96.0, personas_necesarias: null, observaciones: "Pintura" },
      { nombre: "Colocar tomas de aire de sala de maquinas", orden: 20, horas_estimadas: 6.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Laminar planchada", orden: 21, horas_estimadas: 10.0, personas_necesarias: 1, observaciones: "Plastico" },
      { nombre: "Cerrar mamparo de sala de maquinas", orden: 22, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carp. Grueso" },
      { nombre: "Presentar Mamparo de Pique", orden: 23, horas_estimadas: 5.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Ajustar escotilla de acceso a sala de maquinas y llevar a repintar", orden: 24, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Laminar tomas de aire de sala de maquinas", orden: 25, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Plastico" },
      { nombre: "Pintar planchada", orden: 26, horas_estimadas: 120.0, personas_necesarias: null, observaciones: "Pintura" },
      { nombre: "Pintar piernas de popa (union casco-cubierta)", orden: 27, horas_estimadas: 96.0, personas_necesarias: null, observaciones: "Pintura" },
      { nombre: "Poner tambucho redondo de proa", orden: 28, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Ajustar tapa de escalera de planchada y llevar a repintar", orden: 29, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Laminar mamparo de pique", orden: 30, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Plastico" },
      { nombre: "Pintar tomas de aire de sala de máquinas", orden: 31, horas_estimadas: 96.0, personas_necesarias: null, observaciones: "Pintura" },
      { nombre: "Ajustar molduras de ventanas de casco", orden: 32, horas_estimadas: 7.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Armar riel y mamparo de puerta corrediza de camarote de popa", orden: 33, horas_estimadas: 14.0, personas_necesarias: 1, observaciones: "Carp. Grueso" },
      { nombre: "Pegar ojos de buey", orden: 34, horas_estimadas: 12.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Colocar piso de Pique", orden: 35, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Hacer listonado en mamparo de popa del salon, apoyo de escalera y corte para tablero electrico", orden: 36, horas_estimadas: 10.0, personas_necesarias: 1, observaciones: "Carp. Grueso" },
      { nombre: "Laminar piso de pique y pintar", orden: 37, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Plastico" },
      { nombre: "Hacer bases para cables detras de sillon y debajo de tablero, pintar", orden: 38, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carp. Grueso" },
      { nombre: "Pegar molduras de ventanas de casco", orden: 39, horas_estimadas: 8.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Amurar cajas de salida de aire y calefaccion", orden: 40, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Poner rejillas de entrada y salida de aire", orden: 41, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
    ],
  },
  {
    nombre: "Sala de Maquinas",
    orden: 6,
    color: "#f59e0b",
    dias_estimados: 20,
    tareas: [
      { nombre: "Colocar bases para filtros de agua de motor", orden: 1, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Completar antirruido de mamparo de sala de maquinas", orden: 2, horas_estimadas: 10.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Poner bases de calefactor y cajas de electricidad", orden: 3, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Base para pluma + base para aqualift", orden: 4, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Laminar bases de calefactor y elect.", orden: 5, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Plastico" },
      { nombre: "Poliamida hidraulica", orden: 6, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Mecánico" },
      { nombre: "Subir tanques de agua", orden: 7, horas_estimadas: 2.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Instalar motores", orden: 8, horas_estimadas: 16.0, personas_necesarias: null, observaciones: "Mecánico" },
      { nombre: "Colocar caja de baterias", orden: 9, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Poner babero de porton de popa", orden: 10, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Colocar pisos de sala de maquinas", orden: 11, horas_estimadas: 5.0, personas_necesarias: 1, observaciones: "Carp. Grueso" },
    ],
  },
  {
    nombre: "Camarote de Proa",
    orden: 7,
    color: "#ec4899",
    dias_estimados: 25,
    tareas: [
      { nombre: "Poner terciado de cama de proa", orden: 1, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Ajustar y pegar terciados de laterales de proa", orden: 2, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Amurar muebles esquineros de proa", orden: 3, horas_estimadas: 4.0, personas_necesarias: 2, observaciones: "Carpint. Fino" },
      { nombre: "Amurar muebles laterales de proa", orden: 4, horas_estimadas: 10.0, personas_necesarias: 2, observaciones: "Carpint. Fino" },
      { nombre: "Armar frente y lateral de ropero", orden: 5, horas_estimadas: 6.0, personas_necesarias: 2, observaciones: "Carpint. Fino" },
      { nombre: "Ajustar y pegar enchapados de ajuste de muebles de proa", orden: 6, horas_estimadas: 11.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Poner caja fuerte", orden: 7, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Armar interior de ropero (techo, base, tapas de inspeccion, tapizmel, barral, puerta, reten)", orden: 8, horas_estimadas: 16.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Ajustar y pegar enchapados de laterales de proa", orden: 9, horas_estimadas: 5.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Amurar cajonera de proa", orden: 10, horas_estimadas: 6.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Hacer listonado de calles de techo Proa", orden: 11, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino" },
      { nombre: "Poner marcos de puertas de camarote y baño de proa", orden: 12, horas_estimadas: 8.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Ajustar tapizados de mamparos de proa y mandar a tapizar", orden: 13, horas_estimadas: 8.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Hacer bandeau de laterales de proa y mandar a tapizar", orden: 14, horas_estimadas: 6.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Ajustar tapizado de pique y mandar a tapizar", orden: 15, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Armar puertas de muebles de proa (pistones, bisagras, topetinas, barral de inox.)", orden: 16, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Pegar tapizados de techo de proa", orden: 17, horas_estimadas: 5.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Pegar tapizados de mamparos de proa", orden: 18, horas_estimadas: 6.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Ajustar tapizados de calles de proa y mandar a tapizar", orden: 19, horas_estimadas: 5.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Pegar mesas de luz de proa", orden: 20, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Pegar tapizmel de cama de proa", orden: 21, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Amurar bandeau de cama de proa", orden: 22, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Amurar bandeau de laterales de proa", orden: 23, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Pegar tapizados de calles de proa", orden: 24, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Armar puertas de camarote y baño de proa (bisagras, picaportes, cerraduras)", orden: 25, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Poner retenes de puertas de camarote y baño de proa", orden: 26, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Colocar tapizado de pique", orden: 27, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
    ],
  },
  {
    nombre: "Baño de Proa",
    orden: 8,
    color: "#06b6d4",
    dias_estimados: 15,
    tareas: [
      { nombre: "Amurar frente de mueble vanitory de baño de proa", orden: 1, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Pegar pisos de baño de proa", orden: 2, horas_estimadas: 5.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Engomar junta de piso de baño de proa", orden: 3, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Amurar mueble de espejo de baño de proa", orden: 4, horas_estimadas: 5.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Amurar mueble alto de baño de proa", orden: 5, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Ajustar y pegar enchapados de ajuste de baño de proa", orden: 6, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Armar puertas de muebles altos de baño de proa (pistones, bisagras, topetinas, retenes)", orden: 7, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Amurar rejilla de extrator de baño de proa", orden: 8, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Armar sistema de mampara corrediza", orden: 9, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Armar y colgar mampara redonda de acrilico", orden: 10, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Poner perfil \"U\" de mamparas de baño de proa", orden: 11, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Cortar y poner acrilicos de mamparas de baño de proa", orden: 12, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Pegar mesadas de corian de baño de proa", orden: 13, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Poner accesorios de baño de proa", orden: 14, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Pegar espejo de mueble de baño de proa", orden: 15, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Colocar enjaretado de ducha de baño de proa", orden: 16, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Armar interior de mueble vanitory y puerta", orden: 17, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
    ],
  },
  {
    nombre: "Salon",
    orden: 9,
    color: "#a855f7",
    dias_estimados: 25,
    tareas: [
      { nombre: "Amurar mueble de salon", orden: 1, horas_estimadas: 4.0, personas_necesarias: 2, observaciones: "Carpint. Fino" },
      { nombre: "Pegar terciado de respaldo de sillon", orden: 2, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Amurar mueble de tablero electrico", orden: 3, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Ajustar y pegar enchapado de ajuste de mueble de salon y respaldo", orden: 4, horas_estimadas: 8.0, personas_necesarias: 2, observaciones: "Carpint. Fino" },
      { nombre: "Hacer listonado de calles de techo Salon", orden: 5, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carpint. Fino" },
      { nombre: "Ajustar tapizados de mamparos de salon y mandar a tapizar", orden: 6, horas_estimadas: 8.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Hacer plantilla de zocalo de inoxidable de entrada", orden: 7, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Fino" },
      { nombre: "Armar puertas de mueble (bisagras, pistones, topetinas y barral de inox)", orden: 8, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Pegar tapizados de techo de salon (el del limpiaparabrisas con cinta)", orden: 9, horas_estimadas: 4.0, personas_necesarias: 2, observaciones: "Carpint. Fino2" },
      { nombre: "Pegar tapizados de mamparos de salon", orden: 10, horas_estimadas: 8.0, personas_necesarias: 2, observaciones: "Carpint. Fino2" },
      { nombre: "Ajustar calles de techo de Salon", orden: 11, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino" },
      { nombre: "Armar soporte de TV de salon", orden: 12, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Amurar base de escalera de inox", orden: 13, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Armar escalones de madera", orden: 14, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Colocar puertas de acrilico de tablero electrico", orden: 15, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Colocar posabotellas en mueble de salon", orden: 16, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Presentar mesa de comedor y amurar bases de terciado", orden: 17, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Pegar calles de techo de Salon", orden: 18, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Fino" },
      { nombre: "Pegar tapizmel de sillon", orden: 19, horas_estimadas: 7.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Armar sillones", orden: 20, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Poner mesa de comedor", orden: 21, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carpint. Fino" },
      { nombre: "Pegar zocalo de entrada de inox", orden: 22, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Hacer contencion para subwoofer", orden: 23, horas_estimadas: 0.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
    ],
  },
  {
    nombre: "Cocina",
    orden: 10,
    color: "#f97316",
    dias_estimados: 15,
    tareas: [
      { nombre: "Amurar mueble alto de cocina", orden: 1, horas_estimadas: 3.0, personas_necesarias: 2, observaciones: "Carpint. Fino2" },
      { nombre: "Ajustar y pegar enchapado de ajuste de mueble alto de cocina", orden: 2, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Ajustar y pegar enchapados de mamparos de cocina", orden: 3, horas_estimadas: 8.0, personas_necesarias: 2, observaciones: "Carpint. Fino2" },
      { nombre: "Colgar puerta corrediza de camarote de popa", orden: 4, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Colgar puertas de mueble alto de cocina", orden: 5, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Amurar frente de mueble bajomesada de cocina, lateral de cajones", orden: 6, horas_estimadas: 7.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Poner terciado de apoyo de bacha de cocina y listones para mesada", orden: 7, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Colocar bacha de cocina", orden: 8, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Instalar heladera (hacer sistema de marco)", orden: 9, horas_estimadas: 8.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Armar interior de bajo mesada de cocina (estante y fondos)", orden: 10, horas_estimadas: 5.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Pegar mesada de corian de cocina", orden: 11, horas_estimadas: 4.0, personas_necesarias: 2, observaciones: "Carpint. Fino2" },
      { nombre: "Colocar caja de ducto de calefaccion", orden: 12, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Instalar anafe", orden: 13, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Colgar puertas y cajones de mueble bajomesada de cocina", orden: 14, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Colocar herraje de puerta de heladera", orden: 15, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Pegar piso de cocina", orden: 16, horas_estimadas: 4.0, personas_necesarias: 2, observaciones: "Carpint. Fino2" },
      { nombre: "Instalar microondas", orden: 17, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Poner marco de puerta corrediza de Cocina", orden: 18, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
    ],
  },
  {
    nombre: "Camarote de Popa",
    orden: 11,
    color: "#e11d48",
    dias_estimados: 25,
    tareas: [
      { nombre: "Armar riel de puerta corrediza de baño", orden: 1, horas_estimadas: 6.0, personas_necesarias: 1, observaciones: "Carp. Grueso" },
      { nombre: "Hacer caja bajo cama de popa", orden: 2, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Hacer cajas de parlantes de camarote de popa", orden: 3, horas_estimadas: 5.0, personas_necesarias: 1, observaciones: "Carp. Grueso" },
      { nombre: "Ajustar caja de tablero electrico, poner listones y hacer cortes para cables", orden: 4, horas_estimadas: 5.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Hacer listonado de calles de techo Popa", orden: 5, horas_estimadas: 5.0, personas_necesarias: 1, observaciones: "Carpint. Fino" },
      { nombre: "Poner marco de puerta corrediza de camarote de popa", orden: 6, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Ajustar tapizados de mamparos de popa y mandar a tapizar", orden: 7, horas_estimadas: 10.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Amurar mesa de luz de popa", orden: 8, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Colocar bordes de camas de popa", orden: 9, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Ajustar calles de tapizados de popa y mandar a tapizar", orden: 10, horas_estimadas: 6.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Pegar tapizados de techo de popa", orden: 11, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Poner caja de tablero electrico", orden: 12, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carp. Grueso" },
      { nombre: "Pegar tapizados de mamparos de popa", orden: 13, horas_estimadas: 8.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Ajustar y pegar estante de banda", orden: 14, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Ajustar tapizados de respaldos de cama de popa", orden: 15, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Amurar cajonera de popa", orden: 16, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Pegar tapizmel de camas de popa", orden: 17, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Pegar calles de tapizados de popa", orden: 18, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Pegar respaldos de camas de popa", orden: 19, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Amurar bandeau de camas de popa", orden: 20, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
    ],
  },
  {
    nombre: "Baño de Popa",
    orden: 12,
    color: "#0891b2",
    dias_estimados: 15,
    tareas: [
      { nombre: "Pegar pisos de baño de popa (proteger)", orden: 1, horas_estimadas: 7.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Engomar pisos de baño de popa", orden: 2, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carp. Grueso" },
      { nombre: "Poner mamparas de baño de popa y engomar", orden: 3, horas_estimadas: 16.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Amurar muebles superiores de baño de popa", orden: 4, horas_estimadas: 8.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Amurar mueble vanitory de baño de popa", orden: 5, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Pegar mesadas de corian de baño de popa", orden: 6, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Amurar estante de plastico de ducha de popa", orden: 7, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Ajustar y pegar marcos laterales de puerta de baño de popa", orden: 8, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Presentar puerta corrediza de baño de popa y llevar a pegar espejo", orden: 9, horas_estimadas: 7.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Armar puertas de muebles de baño de popa", orden: 10, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Pegar espejo de mueble de baño de popa", orden: 11, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Poner rejilla de extractor de baño de popa", orden: 12, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Armar barrales de inoxidable de popa", orden: 13, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Poner accesorios de baño de popa", orden: 14, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Colgar puerta corrediza de baño de popa y poner tirador", orden: 15, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
      { nombre: "Pegar marco superior de puerta de baño de popa", orden: 16, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Fino2" },
    ],
  },
  {
    nombre: "Interiores",
    orden: 13,
    color: "#6366f1",
    dias_estimados: 20,
    tareas: [
      { nombre: "Etapa 2 de Sanitarios", orden: 1, horas_estimadas: 24.0, personas_necesarias: 2, observaciones: "Sanitarista" },
      { nombre: "Etapa 3 de Sanitarios", orden: 2, horas_estimadas: 8.0, personas_necesarias: 2, observaciones: "Sanitarista" },
      { nombre: "Pintar pisos y tapas de inspeccion", orden: 3, horas_estimadas: 6.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Poner levantapisos de sentina", orden: 4, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Hacer tapacables de TV y mandar a tapizar", orden: 5, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Poner tapacables de TV", orden: 6, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carpint. Fino1" },
      { nombre: "Electricidad 1 (ver notas)", orden: 7, horas_estimadas: 32.0, personas_necesarias: 2, observaciones: "Electricista" },
      { nombre: "Electricidad 2 (luces de techo, tomas, teclas, luces de cortesia, inodoros)", orden: 8, horas_estimadas: 40.0, personas_necesarias: 2, observaciones: "Electricista" },
      { nombre: "Conectar tablero electrico", orden: 9, horas_estimadas: 16.0, personas_necesarias: 1, observaciones: "Electricista" },
      { nombre: "Electricidad 3 (instalar TVs, decos, estereos, ductos de aire)", orden: 10, horas_estimadas: 16.0, personas_necesarias: 2, observaciones: "Electricista" },
      { nombre: "Electricidad 4 (instrumenal de consola, arco radar, parlantes de proa)", orden: 11, horas_estimadas: 16.0, personas_necesarias: 2, observaciones: "Electricista" },
    ],
  },
  {
    nombre: "Exterior",
    orden: 14,
    color: "#84cc16",
    dias_estimados: 30,
    tareas: [
      { nombre: "Poner catalina y trabacadena", orden: 1, horas_estimadas: 3.0, personas_necesarias: 2, observaciones: "Carp. Exterior" },
      { nombre: "Armar cadena, punto fijo, grillete, etc.", orden: 2, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Poner sapito de desagote de ancla", orden: 3, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Colocar herraje de faro de proa", orden: 4, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Pegar ventanas de casco y techo de salon", orden: 5, horas_estimadas: 8.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Ajustar tapas de tomas de aire y poner varillas roscadas", orden: 6, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Ajustar porton de popa: cortes aspiración, tacos de madera", orden: 7, horas_estimadas: 8.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Colocar tapas de tomas de aire", orden: 8, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Instalar puerta corrediza de acceso a interiores", orden: 9, horas_estimadas: 16.0, personas_necesarias: null, observaciones: null },
      { nombre: "Ajustar consola, poner fondo y llevar a repintar", orden: 10, horas_estimadas: 7.0, personas_necesarias: 2, observaciones: "Carp. Exterior" },
      { nombre: "Poner escalera de planchada y presentar tapa", orden: 11, horas_estimadas: 6.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Pintar fondo", orden: 12, horas_estimadas: 32.0, personas_necesarias: null, observaciones: "Pintura" },
      { nombre: "Pintar bandas", orden: 13, horas_estimadas: 40.0, personas_necesarias: null, observaciones: "Pintura" },
      { nombre: "Armar sistema de techo corredizo", orden: 14, horas_estimadas: 6.0, personas_necesarias: 2, observaciones: "Carp. Exterior" },
      { nombre: "Poner tapas de inspeccion tapizadas de laterales", orden: 15, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Colocar pasamanos de laterales de HT", orden: 16, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Armar mueble de cockpit y conservadora", orden: 17, horas_estimadas: 6.0, personas_necesarias: null, observaciones: "Carp. Exterior" },
      { nombre: "Armar interior de mueble de cockpit", orden: 18, horas_estimadas: 6.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Instalar fabricadora de hielo", orden: 19, horas_estimadas: 4.0, personas_necesarias: null, observaciones: "Carp. Exterior" },
      { nombre: "Armar escotilla de acceso a sala de maquinas (cierre, bisagras, piston, antirruido, burlete)", orden: 20, horas_estimadas: 5.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Pegar cucharas de plastico de salida de extractor", orden: 21, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Colocar pasamanos de popa", orden: 22, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Pegar teka", orden: 23, horas_estimadas: 32.0, personas_necesarias: 2, observaciones: "Carp. Exterior" },
      { nombre: "Poner bisagras y levantapiso de tapa de escalera de planchada", orden: 24, horas_estimadas: 3.0, personas_necesarias: null, observaciones: "Carp. Exterior" },
      { nombre: "Pegar ventanas de cubierta y parabrisas", orden: 25, horas_estimadas: 6.0, personas_necesarias: 2, observaciones: "Carp. Exterior" },
      { nombre: "Engomar juntas de ventanas de todo el barco", orden: 26, horas_estimadas: 22.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Armar consola", orden: 27, horas_estimadas: 5.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Pegar moldura de consola", orden: 28, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Colocar pie de consola", orden: 29, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Colocar tapizados de contratecho HT", orden: 30, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Poner botazo", orden: 31, horas_estimadas: 12.0, personas_necesarias: 2, observaciones: "Carp. Grueso" },
      { nombre: "Pegar mesada de corian y armar tapa", orden: 32, horas_estimadas: 6.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Armar puertas de mueble", orden: 33, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Poner posavasos de acrilico de mueble de cockpit", orden: 34, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Armar puerta de cockpit", orden: 35, horas_estimadas: 5.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Armar porton de popa: bacha, antirruido", orden: 36, horas_estimadas: 7.0, personas_necesarias: 2, observaciones: "Carp. Exterior" },
      { nombre: "Colocar baranda de porton de popa", orden: 37, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Subir porton de popa", orden: 38, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Poner parrilla de popa", orden: 39, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Fino" },
      { nombre: "Armar tapa de parrilla de popa (pistones, bisagras, topetinas, contrachapa)", orden: 40, horas_estimadas: 8.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Colocar baranda de tapa de parrilla", orden: 41, horas_estimadas: 2.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Poner posavasos de acrilico de proa", orden: 42, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Colocar barandas de solarium", orden: 43, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carpint. Aux." },
      { nombre: "Armar mesa de cockpit", orden: 44, horas_estimadas: 6.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Amurar caja de selectoras y colocar puerta de acrilico", orden: 45, horas_estimadas: 4.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Poner cable guardamancebo", orden: 46, horas_estimadas: null, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Armar sillones y colchonetas de exterior", orden: 47, horas_estimadas: 5.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
      { nombre: "Poner posavasos de acrilico de sillon de cockpit", orden: 48, horas_estimadas: 3.0, personas_necesarias: 1, observaciones: "Carp. Exterior" },
    ],
  },
];

export const PLANTILLA_K52 = [
  {
    nombre: "Preparación General",
    orden: 1,
    color: "#64748b",
    dias_estimados: 15,
    tareas: [
      { nombre: "DESMOLDE DE CASCO, NIVELACION DE CASCO", orden: 1, horas_estimadas: 40.0, personas_necesarias: null, observaciones: null },
      { nombre: "PREPARACION DE TIRANTERIA DE INTERIORES", orden: 2, horas_estimadas: 160.0, personas_necesarias: null, observaciones: null },
      { nombre: "PREPARACION DE TIRANTERIA DE SALA DE MAQUINAS", orden: 3, horas_estimadas: 80.0, personas_necesarias: null, observaciones: null },
      { nombre: "DESMOLDE DE CUBIERTA", orden: 4, horas_estimadas: 120.0, personas_necesarias: null, observaciones: null },
      { nombre: "DESMOLDE DE LINERS", orden: 5, horas_estimadas: 120.0, personas_necesarias: null, observaciones: null },
      { nombre: "DESMOLDE DE TECHOS DE BAÑO", orden: 6, horas_estimadas: 120.0, personas_necesarias: null, observaciones: null },
      { nombre: "DESMOLDE DE BAÑOS", orden: 7, horas_estimadas: 120.0, personas_necesarias: null, observaciones: null },
      { nombre: "PINTADO DE SENTINA", orden: 8, horas_estimadas: 120.0, personas_necesarias: null, observaciones: null },
      { nombre: "ETAPA 1, SANITARIOS", orden: 9, horas_estimadas: 120.0, personas_necesarias: null, observaciones: null },
      { nombre: "ETAPA 1, ELECTRICIDAD", orden: 10, horas_estimadas: 120.0, personas_necesarias: null, observaciones: null },
      { nombre: "SUBIR LINERS DE INTERIORES, BAÑOS Y TECHOS DE BAÑO", orden: 11, horas_estimadas: 120.0, personas_necesarias: null, observaciones: null },
      { nombre: "DESMOLDE DE CUBIERTA, RECOCIDO DE CASCO Y CUBIERTA", orden: 12, horas_estimadas: 160.0, personas_necesarias: null, observaciones: null },
    ],
  },
  {
    nombre: "Camarote Principal",
    orden: 2,
    color: "#ec4899",
    dias_estimados: 30,
    tareas: [
      { nombre: "TIRANTERIA DE TECHOS DE CAMAROTE PRINCIPAL", orden: 1, horas_estimadas: 160.0, personas_necesarias: null, observaciones: null },
      { nombre: "ELECTRICIDAD, ETAPA 2", orden: 2, horas_estimadas: 200.0, personas_necesarias: null, observaciones: null },
      { nombre: "FORRADO DE TECHOS", orden: 3, horas_estimadas: 200.0, personas_necesarias: null, observaciones: null },
      { nombre: "AJUSTE DE MUEBLE DE VENTANA DE BABOR", orden: 4, horas_estimadas: 240.0, personas_necesarias: null, observaciones: null },
      { nombre: "PREPARAR MAMPAROS TAPIZADOS", orden: 5, horas_estimadas: 360.0, personas_necesarias: null, observaciones: null },
      { nombre: "PREPARAR TECHOS TAPIZADOS", orden: 6, horas_estimadas: 440.0, personas_necesarias: null, observaciones: null },
      { nombre: "ETAPA 3, ELECTRICIDAD (CONECTAR LUCES, BASTIDORES Y TOMAS)", orden: 7, horas_estimadas: 480.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR MARCOS Y PUERTAS DE CAMAROTE DE POPA", orden: 8, horas_estimadas: 720.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR ALFOMBRAS", orden: 9, horas_estimadas: 720.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR CORTINAS", orden: 10, horas_estimadas: 720.0, personas_necesarias: null, observaciones: null },
      { nombre: "ETAPA 4, ELECTRICIDAD (ARMADO DE TABLERO 12 Y 220V)", orden: 11, horas_estimadas: 1040.0, personas_necesarias: null, observaciones: null },
      { nombre: "ETAPA 5, ELECTRICIDAD (PRUEBA GENERAL DE APARATOS ELECTRICOS)", orden: 12, horas_estimadas: 1040.0, personas_necesarias: null, observaciones: null },
    ],
  },
  {
    nombre: "Salón",
    orden: 3,
    color: "#a855f7",
    dias_estimados: 30,
    tareas: [
      { nombre: "TIRANTERIA DE TECHOS DE SALON", orden: 1, horas_estimadas: 160.0, personas_necesarias: null, observaciones: null },
      { nombre: "ELECTRICIDAD, ETAPA 2", orden: 2, horas_estimadas: 200.0, personas_necesarias: null, observaciones: null },
      { nombre: "FORRADO DE TECHOS", orden: 3, horas_estimadas: 200.0, personas_necesarias: null, observaciones: null },
      { nombre: "AJUSTE DE MUEBLE DE VENTANA DE BABOR", orden: 4, horas_estimadas: 240.0, personas_necesarias: null, observaciones: null },
      { nombre: "PREPARAR PLANTILLAS DE MARMOLES", orden: 5, horas_estimadas: 360.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR PISO DE PVC", orden: 6, horas_estimadas: 400.0, personas_necesarias: null, observaciones: null },
      { nombre: "PREPARAR MAMPAROS TAPIZADOS", orden: 7, horas_estimadas: 440.0, personas_necesarias: null, observaciones: null },
      { nombre: "PREPARAR TECHOS TAPIZADOS", orden: 8, horas_estimadas: 520.0, personas_necesarias: null, observaciones: null },
      { nombre: "ETAPA 3, ELECTRICIDAD (CONECTAR LUCES, BASTIDORES Y TOMAS)", orden: 9, horas_estimadas: 600.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR MARCOS Y PUERTAS DE SALON", orden: 10, horas_estimadas: 720.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR CORTINAS", orden: 11, horas_estimadas: 720.0, personas_necesarias: null, observaciones: null },
      { nombre: "ETAPA 2 SANITARIOS, INSTALAR Y CONECTAR GRIFERIAS Y BACHAS", orden: 12, horas_estimadas: 520.0, personas_necesarias: null, observaciones: null },
      { nombre: "ETAPA 4, ELECTRICIDAD (ARMADO DE TABLERO 12 Y 220V)", orden: 13, horas_estimadas: 1040.0, personas_necesarias: null, observaciones: null },
      { nombre: "ETAPA 5, ELECTRICIDAD (PRUEBA GENERAL DE APARATOS ELECTRICOS)", orden: 14, horas_estimadas: 1040.0, personas_necesarias: null, observaciones: null },
    ],
  },
  {
    nombre: "Camarote de Proa",
    orden: 4,
    color: "#ec4899",
    dias_estimados: 25,
    tareas: [
      { nombre: "TIRANTERIA DE TECHOS DE CAMAROTE DE PROA", orden: 1, horas_estimadas: 160.0, personas_necesarias: null, observaciones: null },
      { nombre: "ELECTRICIDAD, ETAPA 2", orden: 2, horas_estimadas: 200.0, personas_necesarias: null, observaciones: null },
      { nombre: "FORRADO DE TECHOS", orden: 3, horas_estimadas: 200.0, personas_necesarias: null, observaciones: null },
      { nombre: "AJUSTE DE MUEBLE DE VENTANA DE BABOR", orden: 4, horas_estimadas: 240.0, personas_necesarias: null, observaciones: null },
      { nombre: "PREPARAR MAMPAROS TAPIZADOS", orden: 5, horas_estimadas: 360.0, personas_necesarias: null, observaciones: null },
      { nombre: "PREPARAR TECHOS TAPIZADOS", orden: 6, horas_estimadas: 440.0, personas_necesarias: null, observaciones: null },
      { nombre: "ETAPA 3, ELECTRICIDAD (CONECTAR LUCES, BASTIDORES Y TOMAS)", orden: 7, horas_estimadas: 480.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR MARCOS Y PUERTAS DE CAMAROTE DE POPA", orden: 8, horas_estimadas: 720.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR ALFOMBRAS", orden: 9, horas_estimadas: 720.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR CORTINAS", orden: 10, horas_estimadas: 720.0, personas_necesarias: null, observaciones: null },
      { nombre: "ETAPA 4, ELECTRICIDAD (ARMADO DE TABLERO 12 Y 220V)", orden: 11, horas_estimadas: 1040.0, personas_necesarias: null, observaciones: null },
      { nombre: "ETAPA 5, ELECTRICIDAD (PRUEBA GENERAL DE APARATOS ELECTRICOS)", orden: 12, horas_estimadas: 1040.0, personas_necesarias: null, observaciones: null },
    ],
  },
  {
    nombre: "Baño de Proa",
    orden: 5,
    color: "#06b6d4",
    dias_estimados: 15,
    tareas: [
      { nombre: "HACER MAMPARO DIVISIOR DE BAÑO", orden: 1, horas_estimadas: 160.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR CENEFA SEGÚN PLANTILLA Y AJUSTAR CONTRA EL MAMPARO", orden: 2, horas_estimadas: 400.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR PISO DE PVC", orden: 3, horas_estimadas: 440.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR ALACENA DE BAÑO", orden: 4, horas_estimadas: 480.0, personas_necesarias: null, observaciones: null },
      { nombre: "HACER PLANTILLAS DE MARMOL DE BAJO MESADA", orden: 5, horas_estimadas: 520.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR GRIFERIAS Y DUCHA", orden: 6, horas_estimadas: 680.0, personas_necesarias: null, observaciones: null },
      { nombre: "ELECTRICIDAD, ETAPA 1 Y 2 (LUCES, VASTIDORES, CONTROL DE ELECTROVALVULA)", orden: 7, horas_estimadas: 720.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR MARCOS DE PUERTA", orden: 8, horas_estimadas: 720.0, personas_necesarias: null, observaciones: null },
      { nombre: "HACER PRUEBAS SANITARIAS", orden: 9, horas_estimadas: 1040.0, personas_necesarias: null, observaciones: null },
    ],
  },
  {
    nombre: "Baño de Popa",
    orden: 6,
    color: "#0891b2",
    dias_estimados: 15,
    tareas: [
      { nombre: "HACER MAMPARO DIVISIOR DE BAÑO", orden: 1, horas_estimadas: 160.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR CENEFA SEGÚN PLANTILLA Y AJUSTAR CONTRA EL MAMPARO", orden: 2, horas_estimadas: 400.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR PISO DE PVC", orden: 3, horas_estimadas: 440.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR ALACENA DE BAÑO", orden: 4, horas_estimadas: 480.0, personas_necesarias: null, observaciones: null },
      { nombre: "HACER PLANTILLAS DE MARMOL DE BAJO MESADA", orden: 5, horas_estimadas: 520.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR GRIFERIAS Y DUCHA", orden: 6, horas_estimadas: 680.0, personas_necesarias: null, observaciones: null },
      { nombre: "ELECTRICIDAD, ETAPA 1 Y 2 (LUCES, VASTIDORES, CONTROL DE ELECTROVALVULA)", orden: 7, horas_estimadas: 720.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR MARCOS DE PUERTA", orden: 8, horas_estimadas: 720.0, personas_necesarias: null, observaciones: null },
      { nombre: "HACER PRUEBAS SANITARIAS", orden: 9, horas_estimadas: 1040.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR CORTINAS", orden: 10, horas_estimadas: 720.0, personas_necesarias: null, observaciones: null },
    ],
  },
  {
    nombre: "Cubierta y Cabina",
    orden: 7,
    color: "#0ea5e9",
    dias_estimados: 25,
    tareas: [
      { nombre: "INSTALAR TINTEROS DE CUBIERTA", orden: 1, horas_estimadas: 240.0, personas_necesarias: null, observaciones: null },
      { nombre: "AJUSTAR TOMA DE AIRE", orden: 2, horas_estimadas: 400.0, personas_necesarias: null, observaciones: null },
      { nombre: "AJUSTAR MUEBLE DE COCKPIT", orden: 3, horas_estimadas: 440.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR HERRAJES + GRILONES + ACRILICO DE PUERTA CORREDIZA", orden: 4, horas_estimadas: 480.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR FLEJE METALICO + LISTON DE MADERA DE PUERTA CORREDIZA", orden: 5, horas_estimadas: 480.0, personas_necesarias: null, observaciones: null },
      { nombre: "AJUSTAR SOBRE DE PUERTA CORREDIZA", orden: 6, horas_estimadas: 480.0, personas_necesarias: null, observaciones: null },
      { nombre: "AJUSTAR CONSOLA DE PUERTA CORREDIZA", orden: 7, horas_estimadas: 480.0, personas_necesarias: null, observaciones: null },
      { nombre: "IZAR CABINA, AJUSTAR, BAJAR Y LLEVAR A PINTURA", orden: 8, horas_estimadas: 240.0, personas_necesarias: null, observaciones: null },
      { nombre: "HACER PLANTILLAS DE MARMOL DE MUEBLE DE COCKPIT", orden: 9, horas_estimadas: 400.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR CONSOLA", orden: 10, horas_estimadas: 720.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR ACRILICOS E INSTRUMENTAL", orden: 11, horas_estimadas: 720.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR CABINA", orden: 12, horas_estimadas: 800.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR CERRAMIENTOS DE CABINA", orden: 13, horas_estimadas: 960.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR BARANDA PERIMETRAL", orden: 14, horas_estimadas: 960.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR TECA DE COCKPIT Y ESCALONES", orden: 15, horas_estimadas: 800.0, personas_necesarias: null, observaciones: null },
    ],
  },
  {
    nombre: "Sala de Máquinas",
    orden: 8,
    color: "#f59e0b",
    dias_estimados: 30,
    tareas: [
      { nombre: "HACER BASES DE CASCO, TIMONES, TANQUES Y SOPORTES DE TANQUES. HACER BASES DE CAJAS ROCKER ELECTRICAS Y BASES DE SEPARADOR DE AGUAS.", orden: 1, horas_estimadas: 160.0, personas_necesarias: null, observaciones: null },
      { nombre: "CERRAR ESPEJO, SEGÚN CORRESPONDA PLANCHADA TENDERLIFT O NO.", orden: 2, horas_estimadas: 200.0, personas_necesarias: null, observaciones: null },
      { nombre: "HACER PISOS DE SALA DE MAQUINAS Y SUS RESPECTIVAS TAPAS DE INSPECCION", orden: 3, horas_estimadas: 240.0, personas_necesarias: null, observaciones: null },
      { nombre: "MANDAR A LAMINAR Y PINTAR PISOS DE SALA DE MAQUINAS", orden: 4, horas_estimadas: 240.0, personas_necesarias: null, observaciones: null },
      { nombre: "PINTAR SALA DE MAQUINA", orden: 5, horas_estimadas: 280.0, personas_necesarias: null, observaciones: null },
      { nombre: "ETAPA 2 DE ELECTRICIDAD DE SALA DE MAQINAS, CABLECANALES Y DISTRIBUCIONES GENERALES. CAJAS ROCKER Y LLAVES BLUE SEA, VICTRON ENERGY, ETC", orden: 6, horas_estimadas: 320.0, personas_necesarias: null, observaciones: null },
      { nombre: "ETAPA 2 DE SANITARIOS DE SALA DE MAQUINAS, PASACASCOS", orden: 7, horas_estimadas: 360.0, personas_necesarias: null, observaciones: null },
      { nombre: "ETAPA 1 DE MECANICA, AJUSTE DE CHASIS DE MOTOR", orden: 8, horas_estimadas: 400.0, personas_necesarias: null, observaciones: null },
      { nombre: "ETAPA 2 DE MECANICA, AGUJEROS EN EL CASCO", orden: 9, horas_estimadas: 480.0, personas_necesarias: null, observaciones: null },
      { nombre: "ETAPA 3 DE MECANICA, TRAZADO DE LINEA DE EJE", orden: 10, horas_estimadas: 720.0, personas_necesarias: null, observaciones: null },
      { nombre: "ETAPA 4 DE MECANICA, PATAS DE GALLO Y MOTORES", orden: 11, horas_estimadas: 840.0, personas_necesarias: null, observaciones: null },
      { nombre: "ETAPA 5 DE MECANICA, CHASIS DE MOTORES", orden: 12, horas_estimadas: 960.0, personas_necesarias: null, observaciones: null },
      { nombre: "ETAPA 6 DE MECANICA, ARMADO DE ESCAPES, SISTEMA COMBUSTIBLE Y GRUPO ELECTROGENO", orden: 13, horas_estimadas: 1040.0, personas_necesarias: null, observaciones: null },
      { nombre: "ETAPA 3 DE ELECTRICIDAD, ARMADO DE BANCOS DE BATERIAS, CONEXIÓN DE MOTORES, SENSORES DE NIVEL DE COMBUSTIBLE, ETC", orden: 14, horas_estimadas: 1040.0, personas_necesarias: null, observaciones: null },
      { nombre: "ETAPA 3 DE SANITARIOS, CONEXIÓN DE SISTEMA DE AGUA POTABLE", orden: 15, horas_estimadas: 1040.0, personas_necesarias: null, observaciones: null },
      { nombre: "ETAPA 4 DE SANITARIOS, PRUEBAS HIDRAULICAS", orden: 16, horas_estimadas: 1080.0, personas_necesarias: null, observaciones: null },
      { nombre: "PRESENTADO DE BAUL, PUESTA A NIVEL", orden: 17, horas_estimadas: 1120.0, personas_necesarias: null, observaciones: null },
      { nombre: "INSTALAR TECA DE PLANCHADA", orden: 18, horas_estimadas: 1120.0, personas_necesarias: null, observaciones: null },
    ],
  },
];