// Generado desde los Excel "Motores asignacion y numeros 3.xlsx" (motores FPT
// Iveco y algunos Volvo) y "GRUPOS ELECTROGENOS en el galpon.xlsx" (hoja
// GRUPOS X OBRA) el 2026-09-18. Es la carga inicial de
// Motores y grupos; cuando exista la tabla equipos (migración
// 20260918100000_equipos_motores_grupos.sql) esto pasa a ser su importación.
// Cada registro dice en "origen" de qué hoja y fila salió. Se regenera con
// node scripts/equipos-desde-excel.cjs.

export const MOTORES_SEED = [
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "650 Angular",
    "potencia": 650,
    "transmision": "Angular",
    "numero_serie": "77288",
    "obra": "55-2",
    "linea": "K55",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 5"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "650 Angular",
    "potencia": 650,
    "transmision": "Angular",
    "numero_serie": "77598",
    "obra": "55-2",
    "linea": "K55",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 6"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "650 Angular",
    "potencia": 650,
    "transmision": "Angular",
    "numero_serie": null,
    "obra": "55-4",
    "linea": "K55",
    "estado": "pedido",
    "fecha_estimada": "Octubre",
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 7"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "650 Angular",
    "potencia": 650,
    "transmision": "Angular",
    "numero_serie": null,
    "obra": "55-4",
    "linea": "K55",
    "estado": "pedido",
    "fecha_estimada": "Octubre",
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 8"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2256893",
    "obra": "52-23",
    "linea": "K52",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 9"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2259099",
    "obra": "52-23",
    "linea": "K52",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 10"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2262564",
    "obra": "52-24",
    "linea": "K52",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 11"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2262807",
    "obra": "52-24",
    "linea": "K52",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 12"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": null,
    "obra": "52-25",
    "linea": "K52",
    "estado": "pedido",
    "fecha_estimada": "19-Oct",
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 13"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": null,
    "obra": "52-25",
    "linea": "K52",
    "estado": "pedido",
    "fecha_estimada": "19-Oct",
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 14"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": null,
    "obra": "52-26",
    "linea": "K52",
    "estado": "pedido",
    "fecha_estimada": "23-Nov",
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 15"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": null,
    "obra": "52-26",
    "linea": "K52",
    "estado": "pedido",
    "fecha_estimada": "23-Nov",
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 16"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": null,
    "obra": "52-27",
    "linea": "K52",
    "estado": "pedido",
    "fecha_estimada": "Febrero",
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 17"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": null,
    "obra": "52-27",
    "linea": "K52",
    "estado": "pedido",
    "fecha_estimada": "Febrero",
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 18"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2241132",
    "obra": "A29",
    "linea": "Antago",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 19"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2247547",
    "obra": "A29",
    "linea": "Antago",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 20"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": null,
    "obra": "A30",
    "linea": "Antago",
    "estado": "pedido",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 21"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": null,
    "obra": "A30",
    "linea": "Antago",
    "estado": "pedido",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 22"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2247507",
    "obra": "43-29",
    "linea": "K43",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 23"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2260410",
    "obra": "43-29",
    "linea": "K43",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 24"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2260416",
    "obra": "43-30",
    "linea": "K43",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 25"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2260419",
    "obra": "43-30",
    "linea": "K43",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 26"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2247502",
    "obra": "42-82",
    "linea": "K42",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 27"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2265441",
    "obra": "42-82",
    "linea": "K42",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 28"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "2185269",
    "obra": "37-42",
    "linea": "K37",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 29"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "2184888",
    "obra": "37-42",
    "linea": "K37",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 30"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "2244529",
    "obra": "37-43",
    "linea": "K37",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 31"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "2244531",
    "obra": "37-43",
    "linea": "K37",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 32"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": null,
    "obra": "37-44",
    "linea": "K37",
    "estado": "pedido",
    "fecha_estimada": "26-Oct",
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 33"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": null,
    "obra": "37-44",
    "linea": "K37",
    "estado": "pedido",
    "fecha_estimada": "26-Oct",
    "urgente": false,
    "cajas": null,
    "origen": "Motores · producción · fila 34"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "1413642",
    "obra": "43-7",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 5"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "1583118",
    "obra": "43-7",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 6"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive V2",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "1835564",
    "obra": "43-9",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 7"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive V2",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "1835533",
    "obra": "43-9",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 8"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive V2",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "1865101",
    "obra": "43-11",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 9"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive V2",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "1881010",
    "obra": "43-11",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 10"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive V2",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "1912415",
    "obra": "43-13",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 11"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive V2",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "1912420",
    "obra": "43-13",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 12"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive V2",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "1905930",
    "obra": "43-14",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 13"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive V2",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "1925192",
    "obra": "43-14",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 14"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive V2",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "1905926",
    "obra": "43-15",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 15"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive V2",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "1912419",
    "obra": "43-15",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 16"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive V2",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "2020069",
    "obra": "43-16",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 17"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive V2",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "2059459",
    "obra": "43-16",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 18"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive V2",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "2029472",
    "obra": "43-17",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 19"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive V2",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "2070007",
    "obra": "43-17",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 20"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive V2",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "2076194",
    "obra": "43-18",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 21"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive V2",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "2081244",
    "obra": "43-18",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 22"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive V2",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "2100746",
    "obra": "43-19",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 23"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive V2",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "2109347",
    "obra": "43-19",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 24"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "1584914",
    "obra": "42-64",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 25"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "1618170",
    "obra": "42-64",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 26"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "1576738",
    "obra": "A21",
    "linea": "Antago",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 27"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "1596542",
    "obra": "A21",
    "linea": "Antago",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 28"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "1583913",
    "obra": "A22",
    "linea": "Antago",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 29"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "1570431",
    "obra": "A22",
    "linea": "Antago",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 30"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "1787581",
    "obra": "A24",
    "linea": "Antago",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 31"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "1788848",
    "obra": "A24",
    "linea": "Antago",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 32"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "1863400",
    "obra": "A25",
    "linea": "Antago",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 33"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "1865457",
    "obra": "A25",
    "linea": "Antago",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 34"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "1576667",
    "obra": "52-1",
    "linea": "K52",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 35"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "1477884",
    "obra": "52-1",
    "linea": "K52",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 36"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "1787562",
    "obra": "52-2",
    "linea": "K52",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 37"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "1787561",
    "obra": "52-2",
    "linea": "K52",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 38"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "1864806",
    "obra": "52-3",
    "linea": "K52",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 39"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "1865673",
    "obra": "52-3",
    "linea": "K52",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 40"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "1879689",
    "obra": "52-4",
    "linea": "K52",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 41"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "1881009",
    "obra": "52-4",
    "linea": "K52",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 42"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "1925190",
    "obra": "52-5",
    "linea": "K52",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 43"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "1970829",
    "obra": "52-5",
    "linea": "K52",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 44"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "1920701",
    "obra": "52-6",
    "linea": "K52",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 45"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "1920704",
    "obra": "52-6",
    "linea": "K52",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 46"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "1912401",
    "obra": "52-7",
    "linea": "K52",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 47"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "1970806",
    "obra": "52-7",
    "linea": "K52",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 48"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2069998",
    "obra": "52-9",
    "linea": "K52",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 49"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2069999",
    "obra": "52-9",
    "linea": "K52",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 50"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2076195",
    "obra": "52-10",
    "linea": "K52",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 51"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2081219",
    "obra": "52-10",
    "linea": "K52",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 52"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2100749",
    "obra": "52-13",
    "linea": "K52",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 53"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2108215",
    "obra": "52-13",
    "linea": "K52",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 54"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2102247",
    "obra": "52-15",
    "linea": "K52",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 55"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2182373",
    "obra": "52-15",
    "linea": "K52",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 56"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "1562958",
    "obra": "43-5",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 57"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "1568841",
    "obra": "43-5",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 58"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "1661923",
    "obra": "43-6",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 59"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "1661921",
    "obra": "43-6",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 60"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "1796601",
    "obra": "43-8",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 61"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "1811903",
    "obra": "43-8",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 62"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "1864437",
    "obra": "43-10",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 63"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "1855962",
    "obra": "43-10",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 64"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "1864104",
    "obra": "43-12",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 65"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "1855966",
    "obra": "43-12",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 66"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive V2",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2087351",
    "obra": "43-21",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 67"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive V2",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2047461",
    "obra": "43-21",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 68"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive V2",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2037872",
    "obra": "43-22",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 69"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive V2",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2039420",
    "obra": "43-22",
    "linea": "K43",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 70"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "1652280",
    "obra": "42-62",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 71"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "1655685",
    "obra": "42-62",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 72"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "1864146",
    "obra": "42-68",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 73"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "1857814",
    "obra": "42-68",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 74"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "1922070",
    "obra": "42-69",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 75"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "1922071",
    "obra": "42-69",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 76"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "1864105",
    "obra": "42-70",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 77"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "1864109",
    "obra": "42-70",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 78"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "1856487",
    "obra": "42-71",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 79"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "1855968",
    "obra": "42-71",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 80"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2037344",
    "obra": "42-72",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 81"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2039359",
    "obra": "42-72",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 82"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2037346",
    "obra": "42-73",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": "Twin disc",
    "origen": "Motores · entregados · fila 83"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2045683",
    "obra": "42-73",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": "Twin disc",
    "origen": "Motores · entregados · fila 84"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "1804982",
    "obra": "42-63",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 85"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "1806999",
    "obra": "42-63",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 86"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "1828059",
    "obra": "42-65",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 87"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "1828076",
    "obra": "42-65",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 88"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "1811513",
    "obra": "42-66",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 89"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "1811646",
    "obra": "42-66",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 90"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "2038435",
    "obra": "42-74",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": "ZF chicas",
    "origen": "Motores · entregados · fila 91"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "2088454",
    "obra": "42-74",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": "ZF chicas",
    "origen": "Motores · entregados · fila 92"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "2185264",
    "obra": "42-76",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 93"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "2185265",
    "obra": "42-76",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 94"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "1947664",
    "obra": "37-4",
    "linea": "K37",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 95"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "1952452",
    "obra": "37-4",
    "linea": "K37",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 96"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "1876217",
    "obra": "37-9",
    "linea": "K37",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 97"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "1871023",
    "obra": "37-9",
    "linea": "K37",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 98"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "1948424",
    "obra": "37-12",
    "linea": "K37",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 99"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "1948468",
    "obra": "37-12",
    "linea": "K37",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 100"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "2038431",
    "obra": "37-13",
    "linea": "K37",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 101"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "2038434",
    "obra": "37-13",
    "linea": "K37",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 102"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "230 V-drive",
    "potencia": 230,
    "transmision": "V-drive",
    "numero_serie": "2256246",
    "obra": "37-2",
    "linea": "K37",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 103"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "230 V-drive",
    "potencia": 230,
    "transmision": "V-drive",
    "numero_serie": "2604634",
    "obra": "37-2",
    "linea": "K37",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 104"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "230 V-drive",
    "potencia": 230,
    "transmision": "V-drive",
    "numero_serie": "2597904",
    "obra": "37-8",
    "linea": "K37",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 105"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "230 V-drive",
    "potencia": 230,
    "transmision": "V-drive",
    "numero_serie": "2604635",
    "obra": "37-8",
    "linea": "K37",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 106"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2196950",
    "obra": "A28",
    "linea": "Antago",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 108"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2196959",
    "obra": "A28",
    "linea": "Antago",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 109"
  },
  {
    "tipo": "motor",
    "marca": "Volvo Penta",
    "modelo": "Volvo D6-440 c/pata",
    "potencia": 440,
    "transmision": "Pata",
    "numero_serie": "A1158401",
    "obra": "42-67",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 116"
  },
  {
    "tipo": "motor",
    "marca": "Volvo Penta",
    "modelo": "Volvo D6-440 c/pata",
    "potencia": 440,
    "transmision": "Pata",
    "numero_serie": "A1159028",
    "obra": "42-67",
    "linea": "K42",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 117"
  },
  {
    "tipo": "motor",
    "marca": "Volvo Penta",
    "modelo": "Volvo D6-380 c/pata",
    "potencia": 380,
    "transmision": "Pata",
    "numero_serie": "A1085497",
    "obra": "37-1",
    "linea": "K37",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 120"
  },
  {
    "tipo": "motor",
    "marca": "Volvo Penta",
    "modelo": "Volvo D6-400 c/pata",
    "potencia": 400,
    "transmision": "Pata",
    "numero_serie": "A1159479",
    "obra": "37-3",
    "linea": "K37",
    "estado": "entregado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · entregados · fila 121"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "Cursor 650 Angular",
    "potencia": 650,
    "transmision": "Angular",
    "numero_serie": "71536",
    "obra": "52-8",
    "linea": "K52",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 125"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "Cursor 650 Angular",
    "potencia": 650,
    "transmision": "Angular",
    "numero_serie": "73790",
    "obra": "52-8",
    "linea": "K52",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 126"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2102249",
    "obra": "52-16",
    "linea": "K52",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 127"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2102250",
    "obra": "52-16",
    "linea": "K52",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 128"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2189882",
    "obra": "52-17",
    "linea": "K52",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 129"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2190508",
    "obra": "52-17",
    "linea": "K52",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 130"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2180862",
    "obra": "52-18",
    "linea": "K52",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 131"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2188491",
    "obra": "52-18",
    "linea": "K52",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 132"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2112521",
    "obra": "52-19",
    "linea": "K52",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 133"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2181361",
    "obra": "52-19",
    "linea": "K52",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 134"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive V2",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "2185003",
    "obra": "43-25",
    "linea": "K43",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 135"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 V-drive V2",
    "potencia": 570,
    "transmision": "V-drive",
    "numero_serie": "2185004",
    "obra": "43-25",
    "linea": "K43",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 136"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2087349",
    "obra": "43-23",
    "linea": "K43",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 137"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2087354",
    "obra": "43-23",
    "linea": "K43",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 138"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2143374",
    "obra": "43-24",
    "linea": "K43",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 139"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2149412",
    "obra": "43-24",
    "linea": "K43",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 140"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2205988",
    "obra": "43-26",
    "linea": "K43",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": "Cajas nuevas",
    "origen": "Motores · recientes · fila 141"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2205989",
    "obra": "43-26",
    "linea": "K43",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": "Cajas nuevas",
    "origen": "Motores · recientes · fila 142"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2218877",
    "obra": "43-27",
    "linea": "K43",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 143"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2218879",
    "obra": "43-27",
    "linea": "K43",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 144"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "2196351",
    "obra": "42-79",
    "linea": "K42",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 145"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "2196353",
    "obra": "42-79",
    "linea": "K42",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 146"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "2142325",
    "obra": "42-80",
    "linea": "K42",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 147"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "2145954",
    "obra": "42-80",
    "linea": "K42",
    "estado": "asignado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": "Cajas nuevas",
    "origen": "Motores · recientes · fila 148"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2196947",
    "obra": "52-20",
    "linea": "K52",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 149"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2199308",
    "obra": "52-20",
    "linea": "K52",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 150"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "2041067",
    "obra": "42-81",
    "linea": "K42",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": "Cajas nuevas",
    "origen": "Motores · recientes · fila 151"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "400 V-drive",
    "potencia": 400,
    "transmision": "V-drive",
    "numero_serie": "2041064",
    "obra": "42-81",
    "linea": "K42",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": "Cajas nuevas",
    "origen": "Motores · recientes · fila 152"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2188493",
    "obra": "52-21",
    "linea": "K52",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 153"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2182034",
    "obra": "52-21",
    "linea": "K52",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 154"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2243156",
    "obra": "52-22",
    "linea": "K52",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 155"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "570 Angular V2",
    "potencia": 570,
    "transmision": "Angular",
    "numero_serie": "2246570",
    "obra": "52-22",
    "linea": "K52",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 156"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2206012",
    "obra": "43-28",
    "linea": "K43",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 157"
  },
  {
    "tipo": "motor",
    "marca": "FPT Iveco",
    "modelo": "450 V-drive",
    "potencia": 450,
    "transmision": "V-drive",
    "numero_serie": "2207128",
    "obra": "43-28",
    "linea": "K43",
    "estado": "instalado",
    "fecha_estimada": null,
    "urgente": false,
    "cajas": null,
    "origen": "Motores · recientes · fila 158"
  }
];

export const GRUPOS_SEED = [
  {
    "tipo": "generador",
    "marca": "Maze",
    "modelo": "6kVA (Maze)",
    "potencia": 6,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "37-15",
    "linea": "K37",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2024-01-03",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · por obra · fila 5",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "9,5kVA",
    "potencia": 9.5,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "52-7",
    "linea": "K52",
    "obra_origen": "A26",
    "estado": "instalado",
    "fecha_entrega": "2023-04-26",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [
      {
        "tipo": "reasignacion",
        "desde": "A26",
        "hacia": "52-7",
        "fecha": "2023-04-26"
      }
    ],
    "origen": "Grupos · por obra · fila 7",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "9 kVA",
    "potencia": 9,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "52-9",
    "linea": "K52",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2023-07-07",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · por obra · fila 8",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "9,5kVA",
    "potencia": 9.5,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "52-10",
    "linea": "K52",
    "obra_origen": "52-7",
    "estado": "instalado",
    "fecha_entrega": "2023-10-11",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [
      {
        "tipo": "reasignacion",
        "desde": "52-7",
        "hacia": "52-10",
        "fecha": "2023-10-11"
      }
    ],
    "origen": "Grupos · por obra · fila 9",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "9,5kVA",
    "potencia": 9.5,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "52-11",
    "linea": "K52",
    "obra_origen": "52-8",
    "estado": "instalado",
    "fecha_entrega": "2024-02-21",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [
      {
        "tipo": "reasignacion",
        "desde": "52-8",
        "hacia": "52-11",
        "fecha": "2024-02-21"
      }
    ],
    "origen": "Grupos · por obra · fila 10",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "7 kVA",
    "potencia": 7,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "42-72",
    "linea": "K42",
    "obra_origen": "42-72",
    "estado": "instalado",
    "fecha_entrega": "2023-08-04",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · por obra · fila 12",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "7 kVA",
    "potencia": 7,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "42-73",
    "linea": "K42",
    "obra_origen": "42-73",
    "estado": "instalado",
    "fecha_entrega": "2024-01-03",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · por obra · fila 13",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "6kVA",
    "potencia": 6,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "42-74",
    "linea": "K42",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2024-03-20",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · por obra · fila 14",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "9kVA",
    "potencia": 9,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "43-17",
    "linea": "K43",
    "obra_origen": "43-17",
    "estado": "instalado",
    "fecha_entrega": "2023-08-07",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · por obra · fila 16",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "9 kVA",
    "potencia": 9,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "43-18",
    "linea": "K43",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2023-11-15",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · por obra · fila 17",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "9,5 kVA",
    "potencia": 9.5,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "43-19",
    "linea": "K43",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2024-03-20",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · por obra · fila 18",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "14 kVA",
    "potencia": 14,
    "proveedor": "Folino",
    "numero_serie": null,
    "obra": "A26",
    "linea": "Antago",
    "obra_origen": "A26",
    "estado": "instalado",
    "fecha_entrega": "2023-07-07",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · por obra · fila 20",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "9kVA",
    "potencia": 9,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "A27",
    "linea": "Antago",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2023-11-01",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · por obra · fila 21",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "17 kVA",
    "potencia": 17,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "64-17",
    "linea": "K64",
    "obra_origen": "64-17",
    "estado": "instalado",
    "fecha_entrega": "2023-08-04",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · por obra · fila 23",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "20.5",
    "potencia": 20.5,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "64-18",
    "linea": "K64",
    "obra_origen": "64-18",
    "estado": "instalado",
    "fecha_entrega": "2024-06-18",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · por obra · fila 24",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "20kVA",
    "potencia": 20,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "64-19",
    "linea": "K64",
    "obra_origen": "64-19",
    "estado": "instalado",
    "fecha_entrega": "2025-05-07",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · por obra · fila 25",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "27kVA",
    "potencia": 27,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "85-3",
    "linea": "K85",
    "obra_origen": "85-3",
    "estado": "instalado",
    "fecha_entrega": "2026-02-26",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · por obra · fila 26",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "9kVA",
    "potencia": 9,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "52-12",
    "linea": "K52",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2024-06-05",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · por obra · fila 30",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "9,5 kVA",
    "potencia": 9.5,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": null,
    "linea": null,
    "obra_origen": "52-9",
    "estado": "en_galpon",
    "fecha_entrega": "2024-12-11",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [
      {
        "tipo": "devuelto",
        "desde": "52-9",
        "hacia": null,
        "fecha": "2024-12-11"
      }
    ],
    "origen": "Grupos · por obra · fila 31",
    "devuelto_a_stock": true
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "11kVA",
    "potencia": 11,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "52-13",
    "linea": "K52",
    "obra_origen": "52-10",
    "estado": "instalado",
    "fecha_entrega": "2024-09-20",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [
      {
        "tipo": "reasignacion",
        "desde": "52-10",
        "hacia": "52-13",
        "fecha": "2024-09-20"
      }
    ],
    "origen": "Grupos · por obra · fila 32",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "11kVA",
    "potencia": 11,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "52-14",
    "linea": "K52",
    "obra_origen": "A27",
    "estado": "instalado",
    "fecha_entrega": "2024-09-20",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [
      {
        "tipo": "reasignacion",
        "desde": "A27",
        "hacia": "52-14",
        "fecha": "2024-09-20"
      }
    ],
    "origen": "Grupos · por obra · fila 33",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "13,5 kVA",
    "potencia": 13.5,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "A28",
    "linea": "Antago",
    "obra_origen": "52-7",
    "estado": "instalado",
    "fecha_entrega": "2023-04-26",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [
      {
        "tipo": "reasignacion",
        "desde": "52-7",
        "hacia": "A28",
        "fecha": "2023-04-26"
      }
    ],
    "origen": "Grupos · por obra · fila 34",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "4kVA",
    "potencia": 4,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "H159",
    "linea": "Hunter",
    "obra_origen": "37-9",
    "estado": "instalado",
    "fecha_entrega": "2023-07-04",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [
      {
        "tipo": "reasignacion",
        "desde": "37-9",
        "hacia": "H159",
        "fecha": "2023-07-04"
      }
    ],
    "origen": "Grupos · por obra · fila 35",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "4kVA",
    "potencia": 4,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "37-16",
    "linea": "K37",
    "obra_origen": "37-10",
    "estado": "instalado",
    "fecha_entrega": "2023-10-11",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [
      {
        "tipo": "reasignacion",
        "desde": "37-10",
        "hacia": "37-16",
        "fecha": "2023-10-11"
      }
    ],
    "origen": "Grupos · por obra · fila 36",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "4kVA",
    "potencia": 4,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "37-17",
    "linea": "K37",
    "obra_origen": "37-13",
    "estado": "instalado",
    "fecha_entrega": "2023-10-11",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [
      {
        "tipo": "reasignacion",
        "desde": "37-13",
        "hacia": "37-17",
        "fecha": "2023-10-11"
      }
    ],
    "origen": "Grupos · por obra · fila 37",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "4kVA",
    "potencia": 4,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "37-12",
    "linea": "K37",
    "obra_origen": "37-12",
    "estado": "asignado",
    "fecha_entrega": "2023-10-11",
    "compra_cliente": false,
    "destino_externo": "SIRIUS",
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · por obra · fila 38",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "4kVA",
    "potencia": 4,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "H168",
    "linea": "Hunter",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2025-05-14",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · por obra · fila 39",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "4kVA",
    "potencia": 4,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": null,
    "linea": null,
    "obra_origen": null,
    "estado": "en_galpon",
    "fecha_entrega": "2025-01-03",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · por obra · fila 40",
    "devuelto_a_stock": true
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "6kVA",
    "potencia": 6,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "37-32",
    "linea": "K37",
    "obra_origen": "37-31",
    "estado": "instalado",
    "fecha_entrega": "2025-10-22",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [
      {
        "tipo": "reasignacion",
        "desde": "37-31",
        "hacia": "37-32",
        "fecha": "2025-10-22"
      }
    ],
    "origen": "Grupos · por obra · fila 41",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "6kVA",
    "potencia": 6,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "42-74",
    "linea": "K42",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2024-03-20",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 5",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "6kVA",
    "potencia": 6,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "37-18",
    "linea": "K37",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2024-05-08",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 6",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "6kVA",
    "potencia": 6,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "37-19",
    "linea": "K37",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2024-05-08",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 7",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "6kVA",
    "potencia": 6,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "37-30",
    "linea": "K37",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2025-08-14",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 8",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "7kVA",
    "potencia": 7,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "37-31",
    "linea": "K37",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2025-10-13",
    "compra_cliente": true,
    "destino_externo": null,
    "nota": "COMPRA CLIENTE",
    "movimientos": [],
    "origen": "Grupos · stock · fila 9",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "6kVA",
    "potencia": 6,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "37-32",
    "linea": "K37",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2025-01-03",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": "Se pasa al SAM",
    "movimientos": [],
    "origen": "Grupos · stock · fila 10",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "6kVA",
    "potencia": 6,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "37-33",
    "linea": "K37",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2025-12-11",
    "compra_cliente": true,
    "destino_externo": null,
    "nota": "COMPRA CLIENTE",
    "movimientos": [],
    "origen": "Grupos · stock · fila 11",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "6kVA",
    "potencia": 6,
    "proveedor": "Cliente",
    "numero_serie": null,
    "obra": "37-34",
    "linea": "K37",
    "obra_origen": null,
    "estado": "asignado",
    "fecha_entrega": null,
    "compra_cliente": false,
    "destino_externo": null,
    "nota": "CHUBUT",
    "movimientos": [],
    "origen": "Grupos · stock · fila 12",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "6kVA",
    "potencia": 6,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "37-35",
    "linea": "K37",
    "obra_origen": "37-33",
    "estado": "instalado",
    "fecha_entrega": "2026-02-26",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [
      {
        "tipo": "reasignacion",
        "desde": "37-33",
        "hacia": "37-35",
        "fecha": "2026-02-26"
      }
    ],
    "origen": "Grupos · stock · fila 13",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "6kVA",
    "potencia": 6,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "37-36",
    "linea": "K37",
    "obra_origen": "37-36",
    "estado": "instalado",
    "fecha_entrega": "2026-02-26",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 14",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "6kVA",
    "potencia": 6,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "42-82",
    "linea": "K42",
    "obra_origen": "37-37",
    "estado": "instalado",
    "fecha_entrega": "2026-07-13",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [
      {
        "tipo": "reasignacion",
        "desde": "37-37",
        "hacia": "42-82",
        "fecha": "2026-07-13"
      }
    ],
    "origen": "Grupos · stock · fila 15",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "6kVA",
    "potencia": 6,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "37-38",
    "linea": "K37",
    "obra_origen": "37-38",
    "estado": "asignado",
    "fecha_entrega": null,
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 16",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "6kVA",
    "potencia": 6,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "37-39",
    "linea": "K37",
    "obra_origen": "37-39",
    "estado": "asignado",
    "fecha_entrega": null,
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 17",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "6kVA",
    "potencia": 6,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "42-79",
    "linea": "K42",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2025-08-14",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 18",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": "Kohler",
    "modelo": "Kholer 7 kVA",
    "potencia": 7,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "42-80",
    "linea": "K42",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2025-08-14",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 19",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": "Sleeper",
    "modelo": "Sleeper 8kVA",
    "potencia": 8,
    "proveedor": "Folino",
    "numero_serie": null,
    "obra": "42-81",
    "linea": "K42",
    "obra_origen": "42-81",
    "estado": "instalado",
    "fecha_entrega": "2026-03-19",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 20",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": "Kohler",
    "modelo": "Kholer 9 kVA",
    "potencia": 9,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "52-17",
    "linea": "K52",
    "obra_origen": "52-17",
    "estado": "instalado",
    "fecha_entrega": "2025-06-02",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 21",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": "Kohler",
    "modelo": "Kholer 9 kVA",
    "potencia": 9,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "52-18",
    "linea": "K52",
    "obra_origen": "52-18",
    "estado": "instalado",
    "fecha_entrega": "2025-08-07",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 22",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": "Kohler",
    "modelo": "Kholer 9 kVA",
    "potencia": 9,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "52-19",
    "linea": "K52",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2025-09-03",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 23",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": "Kohler",
    "modelo": "Kholer 9 kVA",
    "potencia": 9,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "52-20",
    "linea": "K52",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2025-12-03",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 24",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": "Kohler",
    "modelo": "Kholer 9 kVA",
    "potencia": 9,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "52-21",
    "linea": "K52",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2026-03-19",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 25",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": "Kohler",
    "modelo": "Kholer 9 kVA",
    "potencia": 9,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "52-22",
    "linea": "K52",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2026-06-02",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 26",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": "Kohler",
    "modelo": "Kholer 9 kVA",
    "potencia": 9,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": null,
    "linea": null,
    "obra_origen": "52-23",
    "estado": "en_galpon",
    "fecha_entrega": "2026-08-04",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [
      {
        "tipo": "devuelto",
        "desde": "52-23",
        "hacia": null,
        "fecha": "2026-08-04"
      }
    ],
    "origen": "Grupos · stock · fila 27",
    "devuelto_a_stock": true
  },
  {
    "tipo": "generador",
    "marca": "Kohler",
    "modelo": "Kholer 9 kVA",
    "potencia": 9,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "43-25",
    "linea": "K43",
    "obra_origen": "43-25",
    "estado": "instalado",
    "fecha_entrega": "2025-06-02",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 28",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": "Kohler",
    "modelo": "Kholer 9 kVA",
    "potencia": 9,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "43-26",
    "linea": "K43",
    "obra_origen": "43-26",
    "estado": "instalado",
    "fecha_entrega": "2025-08-07",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 29",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "13,5 kVA",
    "potencia": 13.5,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": "43-27",
    "linea": "K43",
    "obra_origen": "52-8",
    "estado": "instalado",
    "fecha_entrega": "2025-12-03",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [
      {
        "tipo": "reasignacion",
        "desde": "52-8",
        "hacia": "43-27",
        "fecha": "2025-12-03"
      }
    ],
    "origen": "Grupos · stock · fila 30",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": "Kohler",
    "modelo": "Kholer 9 kVA",
    "potencia": 9,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "43-28",
    "linea": "K43",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2026-03-19",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 31",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": "Kohler",
    "modelo": "Kholer 9 kVA",
    "potencia": 9,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "43-23",
    "linea": "K43",
    "obra_origen": "43-27",
    "estado": "instalado",
    "fecha_entrega": "2025-09-03",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [
      {
        "tipo": "reasignacion",
        "desde": "43-27",
        "hacia": "43-23",
        "fecha": "2025-09-03"
      }
    ],
    "origen": "Grupos · stock · fila 32",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "9kVA",
    "potencia": 9,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "64-21",
    "linea": "K64",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2026-05-15",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 33",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "9kVA",
    "potencia": 9,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "43-29",
    "linea": "K43",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2026-07-29",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 34",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "9kVA",
    "potencia": 9,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": null,
    "linea": null,
    "obra_origen": null,
    "estado": "en_galpon",
    "fecha_entrega": null,
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 35",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "9kVA",
    "potencia": 9,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": null,
    "linea": null,
    "obra_origen": null,
    "estado": "en_galpon",
    "fecha_entrega": null,
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 36",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "9kVA",
    "potencia": 9,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": null,
    "linea": null,
    "obra_origen": null,
    "estado": "en_galpon",
    "fecha_entrega": null,
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 37",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "17kVA",
    "potencia": 17,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "55-1",
    "linea": "K55",
    "obra_origen": "55-1",
    "estado": "instalado",
    "fecha_entrega": "2026-05-15",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 38",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "17kVA",
    "potencia": 17,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "52-23",
    "linea": "K52",
    "obra_origen": "55-2",
    "estado": "instalado",
    "fecha_entrega": "2026-08-07",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [
      {
        "tipo": "reasignacion",
        "desde": "55-2",
        "hacia": "52-23",
        "fecha": "2026-08-07"
      }
    ],
    "origen": "Grupos · stock · fila 39",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": null,
    "modelo": "20kVA",
    "potencia": 20,
    "proveedor": "Trimer",
    "numero_serie": null,
    "obra": "64-21",
    "linea": "K64",
    "obra_origen": null,
    "estado": "instalado",
    "fecha_entrega": "2026-05-28",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 40",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": "Onan",
    "modelo": "9,5 Onan",
    "potencia": 9.5,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": null,
    "linea": null,
    "obra_origen": null,
    "estado": "en_galpon",
    "fecha_entrega": null,
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 41",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": "Onan",
    "modelo": "9,5 Onan",
    "potencia": 9.5,
    "proveedor": "Naval",
    "numero_serie": null,
    "obra": null,
    "linea": null,
    "obra_origen": null,
    "estado": "en_galpon",
    "fecha_entrega": null,
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 42",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": "Sleeper",
    "modelo": "Sleeper 10,8kVA",
    "potencia": 10.8,
    "proveedor": "Folino",
    "numero_serie": null,
    "obra": "37-38",
    "linea": "K37",
    "obra_origen": "37-38",
    "estado": "instalado",
    "fecha_entrega": "2026-07-01",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 43",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": "Sleeper",
    "modelo": "Sleeper 10,8kVA",
    "potencia": 10.8,
    "proveedor": "Folino",
    "numero_serie": null,
    "obra": "37-39",
    "linea": "K37",
    "obra_origen": "37-39",
    "estado": "instalado",
    "fecha_entrega": "2026-08-05",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 44",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": "Sleeper",
    "modelo": "Sleeper 8kVA",
    "potencia": 8,
    "proveedor": "Folino",
    "numero_serie": null,
    "obra": "37-40",
    "linea": "K37",
    "obra_origen": "37-40",
    "estado": "instalado",
    "fecha_entrega": "2026-08-20",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 45",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": "Sleeper",
    "modelo": "Sleeper 8kVA",
    "potencia": 8,
    "proveedor": "Folino",
    "numero_serie": null,
    "obra": "37-41",
    "linea": "K37",
    "obra_origen": "37-41",
    "estado": "instalado",
    "fecha_entrega": "2026-09-14",
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 46",
    "devuelto_a_stock": false
  },
  {
    "tipo": "generador",
    "marca": "Sleeper",
    "modelo": "Sleeper 8kVA",
    "potencia": 8,
    "proveedor": "Folino",
    "numero_serie": null,
    "obra": "37-42",
    "linea": "K37",
    "obra_origen": "37-42",
    "estado": "asignado",
    "fecha_entrega": null,
    "compra_cliente": false,
    "destino_externo": null,
    "nota": null,
    "movimientos": [],
    "origen": "Grupos · stock · fila 47",
    "devuelto_a_stock": false
  }
];
