const status = {
  obra: {
    activa: {
      dot: "var(--blue)",
      glow: "var(--blue)",
      top: "var(--blue-deep)",
      bg: "var(--blue-soft)",
      border: "var(--blue-border)",
      label: "Activa",
    },
    pausada: {
      dot: "var(--amber)",
      glow: "var(--amber)",
      top: "var(--amber-deep)",
      bg: "var(--amber-soft)",
      border: "var(--amber-border)",
      label: "Pausada",
    },
    terminada: {
      dot: "var(--green)",
      glow: "var(--green)",
      top: "var(--green-deep)",
      bg: "var(--green-soft)",
      border: "var(--green-border)",
      label: "Terminada",
    },
    cancelada: {
      dot: "var(--red)",
      glow: "var(--red)",
      top: "var(--red-deep)",
      bg: "var(--red-soft)",
      border: "var(--red-border)",
      label: "Cancelada",
    },
    vacio: {
      dot: "var(--dim)",
      glow: "var(--empty-glow)",
      top: "transparent",
      bg: "var(--panel)",
      border: "var(--border)",
      label: "Disponible",
    },
  },
  etapa: {
    pendiente: {
      dot: "var(--dim)",
      bar: "var(--panel-2)",
      text: "var(--dim)",
      label: "Pendiente",
    },
    en_curso: {
      dot: "var(--blue)",
      bar: "var(--blue-soft)",
      text: "var(--blue)",
      label: "En curso",
    },
    completado: {
      dot: "var(--green)",
      bar: "var(--green-soft)",
      text: "var(--green)",
      label: "Completado",
    },
    bloqueado: {
      dot: "var(--red)",
      bar: "var(--red-soft)",
      text: "var(--red)",
      label: "Bloqueado",
    },
  },
  tarea: {
    pendiente: { dot: "var(--dim)", text: "var(--dim)", label: "Pendiente" },
    en_progreso: { dot: "var(--blue)", text: "var(--blue)", label: "En progreso" },
    finalizada: { dot: "var(--green)", text: "var(--green)", label: "Finalizada" },
    bloqueada: { dot: "var(--red)", text: "var(--red)", label: "Bloqueada" },
    cancelada: { dot: "var(--subtle)", text: "var(--subtle)", label: "Cancelada" },
  },
  prioridad: {
    baja: { color: "var(--dim)", label: "Baja" },
    media: { color: "var(--blue)", label: "Media" },
    alta: { color: "var(--amber)", label: "Alta" },
    critica: { color: "var(--red)", label: "Critica" },
  },
  oc: {
    pendiente: {
      dot: "var(--dim)",
      bg: "var(--panel-2)",
      border: "var(--border)",
      label: "Pendiente",
    },
    solicitada: {
      dot: "var(--blue)",
      bg: "var(--blue-soft)",
      border: "var(--blue-border)",
      label: "Solicitada",
    },
    pedida: {
      dot: "var(--blue)",
      bg: "var(--blue-soft)",
      border: "var(--blue-border)",
      label: "Pedido",
    },
    aprobada: {
      dot: "var(--amber)",
      bg: "var(--amber-soft)",
      border: "var(--amber-border)",
      label: "Aprobada",
    },
    en_camino: {
      dot: "var(--violet)",
      bg: "var(--violet-soft)",
      border: "var(--violet-border)",
      label: "En camino",
    },
    recibida: {
      dot: "var(--green)",
      bg: "var(--green-soft)",
      border: "var(--green-border)",
      label: "Recibida",
    },
    cancelada: {
      dot: "var(--red)",
      bg: "var(--red-soft)",
      border: "var(--red-border)",
      label: "Cancelada",
    },
  },
};

export const C = {
  bg: "var(--bg)",
  bg1: "var(--panel-solid)",
  bg2: "var(--panel-solid-2)",
  bg3: "var(--panel-solid-3)",
  panel: "var(--panel)",
  panel2: "var(--panel-2)",
  panel3: "var(--panel-3)",
  panelSolid: "var(--panel-solid)",
  panelSolid2: "var(--panel-solid-2)",
  panelSolid3: "var(--panel-solid-3)",
  card: "var(--panel)",
  s0: "var(--panel)",
  s1: "var(--panel-2)",
  s2: "var(--panel-3)",
  border: "var(--border)",
  border2: "var(--border-2)",
  b0: "var(--border)",
  b1: "var(--border-2)",
  b2: "var(--border-3)",
  topbar: "var(--topbar)",
  topbarSoft: "var(--topbar-soft)",
  text: "var(--text)",
  muted: "var(--muted)",
  dim: "var(--dim)",
  t0: "var(--text)",
  t1: "var(--muted)",
  t2: "var(--dim)",
  t3: "var(--subtle)",
  blue: "var(--blue)",
  primary: "var(--blue)",
  amber: "var(--amber)",
  green: "var(--green)",
  red: "var(--red)",
  violet: "var(--violet)",
  purple: "var(--purple)",
  teal: "var(--teal)",
  cyan: "var(--cyan)",
  orange: "var(--orange)",
  indigo: "var(--indigo)",
  blueL: "var(--blue-soft)",
  blueB: "var(--blue-border)",
  violetL: "var(--violet-soft)",
  violetB: "var(--violet-border)",
  amberL: "var(--amber-soft)",
  amberB: "var(--amber-border)",
  greenL: "var(--green-soft)",
  greenB: "var(--green-border)",
  redL: "var(--red-soft)",
  redB: "var(--red-border)",
  mono: "'JetBrains Mono', 'IBM Plex Mono', monospace",
  sans: "'Outfit', system-ui, sans-serif",
  ...status,
};

export const THEMES = [
  { value: "dark", label: "Oscuro" },
  { value: "light", label: "Claro" },
  { value: "hc", label: "Alto contraste" },
];
