-- Marcas como variantes en items K37 (Whale se deja en el nombre)
BEGIN;
update panol_materiales set variantes='[]'::jsonb where origen='k37_enero2026';
update panol_materiales set variantes = variantes || '["Samsung"]'::jsonb where origen='k37_enero2026' and descripcion ~* '\mSamsung\M' and not (variantes @> '["Samsung"]');
update panol_materiales set variantes = variantes || '["LG"]'::jsonb where origen='k37_enero2026' and descripcion ~* '\mLG\M' and not (variantes @> '["LG"]');
update panol_materiales set variantes = variantes || '["Wema"]'::jsonb where origen='k37_enero2026' and descripcion ~* '\mWema\M' and not (variantes @> '["Wema"]');
update panol_materiales set variantes = variantes || '["Centek"]'::jsonb where origen='k37_enero2026' and descripcion ~* '\mCentek\M' and not (variantes @> '["Centek"]');
update panol_materiales set variantes = variantes || '["U-Flex"]'::jsonb where origen='k37_enero2026' and descripcion ~* 'u-flex' and not (variantes @> '["U-Flex"]');
update panol_materiales set variantes = variantes || '["Bennett"]'::jsonb where origen='k37_enero2026' and descripcion ~* '\mBennett\M' and not (variantes @> '["Bennett"]');
update panol_materiales set variantes = variantes || '["Craftman"]'::jsonb where origen='k37_enero2026' and descripcion ~* '\mCraftman\M' and not (variantes @> '["Craftman"]');
update panol_materiales set variantes = variantes || '["Rama"]'::jsonb where origen='k37_enero2026' and descripcion ~* '\mRama\M' and not (variantes @> '["Rama"]');
update panol_materiales set variantes = variantes || '["Perko"]'::jsonb where origen='k37_enero2026' and descripcion ~* '\mPerko\M' and not (variantes @> '["Perko"]');
update panol_materiales set variantes = variantes || '["Kallay"]'::jsonb where origen='k37_enero2026' and descripcion ~* '\mKallay\M' and not (variantes @> '["Kallay"]');
update panol_materiales set variantes = variantes || '["Hafele"]'::jsonb where origen='k37_enero2026' and descripcion ~* '\mHafele\M' and not (variantes @> '["Hafele"]');
update panol_materiales set variantes = variantes || '["Threebond"]'::jsonb where origen='k37_enero2026' and descripcion ~* '\mThreebond\M' and not (variantes @> '["Threebond"]');
update panol_materiales set variantes = variantes || '["Whirpool"]'::jsonb where origen='k37_enero2026' and descripcion ~* '\mWhirpool\M' and not (variantes @> '["Whirpool"]');
update panol_materiales set variantes = variantes || '["Atma"]'::jsonb where origen='k37_enero2026' and descripcion ~* '\mAtma\M' and not (variantes @> '["Atma"]');
update panol_materiales set variantes = variantes || '["U-Line"]'::jsonb where origen='k37_enero2026' and descripcion ~* 'u-line' and not (variantes @> '["U-Line"]');
update panol_materiales set variantes = variantes || '["Shakespeare"]'::jsonb where origen='k37_enero2026' and descripcion ~* '\mShakespeare\M' and not (variantes @> '["Shakespeare"]');
update panol_materiales set variantes = variantes || '["Bidematic"]'::jsonb where origen='k37_enero2026' and descripcion ~* '\mBidematic\M' and not (variantes @> '["Bidematic"]');
update panol_materiales set variantes = variantes || '["Johnson"]'::jsonb where origen='k37_enero2026' and descripcion ~* '\mJohnson\M' and not (variantes @> '["Johnson"]');
update panol_materiales set variantes = variantes || '["Lofrans"]'::jsonb where origen='k37_enero2026' and descripcion ~* '\mLofrans\M' and not (variantes @> '["Lofrans"]');
update panol_materiales set descripcion = regexp_replace(descripcion, '\s*/?\mSamsung\M', '', 'gi') where origen='k37_enero2026' and descripcion ~* '\mSamsung\M';
update panol_materiales set descripcion = regexp_replace(descripcion, '\s*/?\mLG\M', '', 'gi') where origen='k37_enero2026' and descripcion ~* '\mLG\M';
update panol_materiales set descripcion = regexp_replace(descripcion, '\s*/?\mWema\M', '', 'gi') where origen='k37_enero2026' and descripcion ~* '\mWema\M';
update panol_materiales set descripcion = regexp_replace(descripcion, '\s*/?\mCentek\M', '', 'gi') where origen='k37_enero2026' and descripcion ~* '\mCentek\M';
update panol_materiales set descripcion = regexp_replace(descripcion, '\s*/?u-flex', '', 'gi') where origen='k37_enero2026' and descripcion ~* 'u-flex';
update panol_materiales set descripcion = regexp_replace(descripcion, '\s*/?\mBennett\M', '', 'gi') where origen='k37_enero2026' and descripcion ~* '\mBennett\M';
update panol_materiales set descripcion = regexp_replace(descripcion, '\s*/?\mCraftman\M', '', 'gi') where origen='k37_enero2026' and descripcion ~* '\mCraftman\M';
update panol_materiales set descripcion = regexp_replace(descripcion, '\s*/?\mRama\M', '', 'gi') where origen='k37_enero2026' and descripcion ~* '\mRama\M';
update panol_materiales set descripcion = regexp_replace(descripcion, '\s*/?\mPerko\M', '', 'gi') where origen='k37_enero2026' and descripcion ~* '\mPerko\M';
update panol_materiales set descripcion = regexp_replace(descripcion, '\s*/?\mKallay\M', '', 'gi') where origen='k37_enero2026' and descripcion ~* '\mKallay\M';
update panol_materiales set descripcion = regexp_replace(descripcion, '\s*/?\mHafele\M', '', 'gi') where origen='k37_enero2026' and descripcion ~* '\mHafele\M';
update panol_materiales set descripcion = regexp_replace(descripcion, '\s*/?\mThreebond\M', '', 'gi') where origen='k37_enero2026' and descripcion ~* '\mThreebond\M';
update panol_materiales set descripcion = regexp_replace(descripcion, '\s*/?\mWhirpool\M', '', 'gi') where origen='k37_enero2026' and descripcion ~* '\mWhirpool\M';
update panol_materiales set descripcion = regexp_replace(descripcion, '\s*/?\mAtma\M', '', 'gi') where origen='k37_enero2026' and descripcion ~* '\mAtma\M';
update panol_materiales set descripcion = regexp_replace(descripcion, '\s*/?u-line', '', 'gi') where origen='k37_enero2026' and descripcion ~* 'u-line';
update panol_materiales set descripcion = regexp_replace(descripcion, '\s*/?\mShakespeare\M', '', 'gi') where origen='k37_enero2026' and descripcion ~* '\mShakespeare\M';
update panol_materiales set descripcion = regexp_replace(descripcion, '\s*/?\mBidematic\M', '', 'gi') where origen='k37_enero2026' and descripcion ~* '\mBidematic\M';
update panol_materiales set descripcion = regexp_replace(descripcion, '\s*/?\mJohnson\M', '', 'gi') where origen='k37_enero2026' and descripcion ~* '\mJohnson\M';
update panol_materiales set descripcion = regexp_replace(descripcion, '\s*/?\mLofrans\M', '', 'gi') where origen='k37_enero2026' and descripcion ~* '\mLofrans\M';
update panol_materiales set descripcion = btrim(regexp_replace(descripcion, '\s{2,}', ' ', 'g'), ' /,-') where origen='k37_enero2026';
COMMIT;
