// Generado automáticamente desde los archivos .mpp originales
// K42: 310 tareas, 14 etapas (Sector = campo TEXT2 del MPP)
// K52: 102 tareas, 9 etapas (agrupación manual por orden lógico)

export const PLANTILLA_K42 = [
  {
    nombre: "Matrices",
    orden: 1,
    color: "#8b5cf6",
    tareas: [
      { orden: 1, nombre: "Preparar Matriz de Casco con postizos", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 2, nombre: "Preparar Matriz de Cubierta con postizos", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 3, nombre: "Laminado de Casco", horas_estimadas: 80.0, personas_necesarias: 5 },
      { orden: 4, nombre: "Laminado de Cubierta", horas_estimadas: 64.0, personas_necesarias: 4 },
      { orden: 5, nombre: "Preparar matrices de interior con postizos", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 6, nombre: "Laminado de piezas de interiores", horas_estimadas: 40.0, personas_necesarias: 4 },
      { orden: 7, nombre: "Preparar de matrices de contratechos con postizos", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 8, nombre: "Laminado de piezas de contratechos", horas_estimadas: 32.0, personas_necesarias: 4 },
      { orden: 9, nombre: "Armado de grilla Long.", horas_estimadas: 16.0, personas_necesarias: 2 },
      { orden: 10, nombre: "Laminado de Grilla Long.", horas_estimadas: 6.0, personas_necesarias: 3 },
      { orden: 11, nombre: "Armado grilla transversal y caños de desmolde, sacar bulones de postizos", horas_estimadas: 16.0, personas_necesarias: 2 },
      { orden: 12, nombre: "Laminado de grilla transversal y caños de desmolde", horas_estimadas: 6.0, personas_necesarias: 3 },
    ],
  },
  {
    nombre: "Preparado abajo",
    orden: 2,
    color: "#64748b",
    tareas: [
      { orden: 1, nombre: "Preparado de bases de casco e imbornales", horas_estimadas: 8.0, personas_necesarias: 1 },
      { orden: 2, nombre: "Preparado de mamparos segun plantilla", horas_estimadas: 16.0, personas_necesarias: 1 },
      { orden: 3, nombre: "Preparado de tiranteria de pisos segun plano", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 4, nombre: "Hacer tapas de inspeccion de sentina, camas y sillon", horas_estimadas: 6.0, personas_necesarias: 1 },
      { orden: 5, nombre: "Ensamblar tomas de aire de sala de maquinas", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 6, nombre: "Armar estructura de cabina HT", horas_estimadas: 6.0, personas_necesarias: 1 },
      { orden: 7, nombre: "Ensamblar contratecho de cabina HT", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 8, nombre: "Ensamblar techo corredizo", horas_estimadas: 8.0, personas_necesarias: 1 },
      { orden: 9, nombre: "Sellar y pintar cabina de HT", horas_estimadas: 40.0, personas_necesarias: 2 },
      { orden: 10, nombre: "Ensamblar Baños", horas_estimadas: 8.0, personas_necesarias: 2 },
      { orden: 11, nombre: "Hacer cortes de inspeccion que falten en piezas de interior", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 12, nombre: "Cortar luces y tapas de inspeccion de contratechos", horas_estimadas: 6.0, personas_necesarias: 1 },
      { orden: 13, nombre: "Ajustar tapizados de techo de proa y mandar a tapizar", horas_estimadas: 7.0, personas_necesarias: 1 },
      { orden: 14, nombre: "Ajustar tapizados de techo de salon y mandar a tapizar", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 15, nombre: "Ajustar tapizados de techo de popa y mandar a tapizar", horas_estimadas: 8.0, personas_necesarias: 1 },
      { orden: 16, nombre: "Ajustar bandeau de cama de proa, poner liston y mandar a tapizar", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 17, nombre: "Ajustar bandeau de camas de popa, poner liston y mandar a tapizar", horas_estimadas: 5.0, personas_necesarias: 1 },
      { orden: 18, nombre: "Hacer mascaras de sillon y mandar a tapizar", horas_estimadas: 16.0, personas_necesarias: 1 },
      { orden: 19, nombre: "Ajustar mascara de sillones de cockpit", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 20, nombre: "Hacer pisos de sala de maquinas", horas_estimadas: 8.0, personas_necesarias: 1 },
      { orden: 21, nombre: "Hacer mesada de corian de cocina (calar anafe y bacha)", horas_estimadas: 24.0, personas_necesarias: 1 },
      { orden: 22, nombre: "Hacer mesadas de corian de baño de proa", horas_estimadas: 16.0, personas_necesarias: 1 },
      { orden: 23, nombre: "Hacer mesadas de corian de baño de popa", horas_estimadas: 16.0, personas_necesarias: 1 },
      { orden: 24, nombre: "Hacer puertas de bajo mesada de cockpit", horas_estimadas: 24.0, personas_necesarias: 1 },
    ],
  },
  {
    nombre: "Cubierta",
    orden: 3,
    color: "#0ea5e9",
    tareas: [
      { orden: 1, nombre: "DESMOLDE DE CUBIERTA, nivelar", horas_estimadas: 4.0, personas_necesarias: 2 },
      { orden: 2, nombre: "Pasar maquina en brida de cubierta", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 3, nombre: "Reparar zona de cockpit en cubierta (parte 1)", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 4, nombre: "Laminar reparacion de cockpit en cubierta (Parte 1)", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 5, nombre: "Armar tiranteria de techo Proa", horas_estimadas: 6.0, personas_necesarias: 1 },
      { orden: 6, nombre: "Reparar zona de cockpit en cubierta (parte 2)", horas_estimadas: 6.0, personas_necesarias: 1 },
      { orden: 7, nombre: "Laminar reparacion de cockpit en cubierta (Parte 2)", horas_estimadas: 6.0, personas_necesarias: 1 },
      { orden: 8, nombre: "Armar tiranteria de techo Salon", horas_estimadas: 6.0, personas_necesarias: 1 },
      { orden: 9, nombre: "Laminar tiranteria de techo", horas_estimadas: 6.0, personas_necesarias: 1 },
      { orden: 10, nombre: "Armar tiranteria de techo Popa", horas_estimadas: 6.0, personas_necesarias: 1 },
      { orden: 11, nombre: "Armar bases de cubierta", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 12, nombre: "Laminar bases de cubierta", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 13, nombre: "Antirruido de cubierta en sala de maquinas", horas_estimadas: 8.0, personas_necesarias: 1 },
      { orden: 14, nombre: "Electricidad de cubierta y calefaccion", horas_estimadas: 20.0, personas_necesarias: 2 },
      { orden: 15, nombre: "Pegar contratechos (usar plantillas)", horas_estimadas: 6.0, personas_necesarias: 2 },
      { orden: 16, nombre: "Terminar marco de entrada de cubierta", horas_estimadas: 12.0, personas_necesarias: 1 },
    ],
  },
  {
    nombre: "Casco",
    orden: 4,
    color: "#3b82f6",
    tareas: [
      { orden: 1, nombre: "DESMOLDE DE CASCO, nivelar casco", horas_estimadas: 4.0, personas_necesarias: 2 },
      { orden: 2, nombre: "Armado de bases de casco e imbornales", horas_estimadas: 24.0, personas_necesarias: 2 },
      { orden: 3, nombre: "Cortar bowthruster y laminar tubo", horas_estimadas: 16.0, personas_necesarias: 1 },
      { orden: 4, nombre: "Presentar mamparo principal (G1, G2 y G3)", horas_estimadas: 4.0, personas_necesarias: 2 },
      { orden: 5, nombre: "Laminado de bases de casco", horas_estimadas: 12.0, personas_necesarias: 1 },
      { orden: 6, nombre: "Presentar mamparo de sala de maquinas (G5 y G6)", horas_estimadas: 4.0, personas_necesarias: 2 },
      { orden: 7, nombre: "Armado de tiranteria de pisos de salon y camarote de popa", horas_estimadas: 4.0, personas_necesarias: 2 },
      { orden: 8, nombre: "Laminado de tiranteria de pisos, mamparo principal y mamparo de sala de maquinas", horas_estimadas: 10.0, personas_necesarias: 1 },
      { orden: 9, nombre: "Pintar de sentina y bandas", horas_estimadas: 8.0, personas_necesarias: 1 },
      { orden: 10, nombre: "Etapa 1 de Sanitarios", horas_estimadas: 36.0, personas_necesarias: 2 },
      { orden: 11, nombre: "Ubicar, nivelar y pegar salon, agregar tirantes faltantes", horas_estimadas: 4.0, personas_necesarias: 2 },
      { orden: 12, nombre: "Presentar Mamparo de proa del Salon (G4)", horas_estimadas: 4.0, personas_necesarias: 2 },
      { orden: 13, nombre: "Ubicar, nivelar y pegar camarote de Popa, agregar tirantes faltantes", horas_estimadas: 6.0, personas_necesarias: 2 },
      { orden: 14, nombre: "Laminar mamparo G4, salon y camarote de popa", horas_estimadas: 12.0, personas_necesarias: 1 },
      { orden: 15, nombre: "Ubicar, nivelar y pegar camarote de Proa, agregar tirantes faltantes", horas_estimadas: 6.0, personas_necesarias: 2 },
      { orden: 16, nombre: "Armar tiranteria de apoyo de baño de popa", horas_estimadas: 5.0, personas_necesarias: 2 },
      { orden: 17, nombre: "Laminar camarote de proa y tiranteria de baño de popa", horas_estimadas: 6.0, personas_necesarias: 1 },
      { orden: 18, nombre: "Pegar bandas de salon y cocina en zona de ventanas", horas_estimadas: 6.0, personas_necesarias: 1 },
      { orden: 19, nombre: "Presentar Mamparo de camarote de Proa babor (G8)", horas_estimadas: 3.0, personas_necesarias: 2 },
      { orden: 20, nombre: "Laminar mamparo G8", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 21, nombre: "Ubicar, nivelar y pegar baño de popa", horas_estimadas: 5.0, personas_necesarias: 2 },
      { orden: 22, nombre: "Cortar ventanas de casco de salon y cocina", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 23, nombre: "Ubicar, nivelar y pegar baño de proa", horas_estimadas: 5.0, personas_necesarias: 2 },
      { orden: 24, nombre: "Presentar y pegar columna de plastico mamparo de baño de proa", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 25, nombre: "Presentar y pegar mamparos de baño de proa", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 26, nombre: "Presentar y pegar mamparo de baño de popa", horas_estimadas: 3.0, personas_necesarias: 1 },
    ],
  },
  {
    nombre: "Despues del ensamble",
    orden: 5,
    color: "#10b981",
    tareas: [
      { orden: 1, nombre: "ENSAMBLE CASCO-CUBIERTA", horas_estimadas: 16.0, personas_necesarias: 2 },
      { orden: 2, nombre: "Cubrir piso de cockpit con pisos de trabajo", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 3, nombre: "Laminar union casco-cubierta y mamparos", horas_estimadas: 16.0, personas_necesarias: 1 },
      { orden: 4, nombre: "Pintar reparacion de piso de cockpit", horas_estimadas: 80.0, personas_necesarias: null },
      { orden: 5, nombre: "Nivelar contratechos en zona de asientos de mueble", horas_estimadas: 8.0, personas_necesarias: 2 },
      { orden: 6, nombre: "Ajustar mueble de cockpit y llevar a repintar", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 7, nombre: "Pintar marco de entrada al salon", horas_estimadas: 32.0, personas_necesarias: null },
      { orden: 8, nombre: "Pulir zonas de pegado de laterales de cubierta", horas_estimadas: 5.0, personas_necesarias: null },
      { orden: 9, nombre: "Hacer corte para selectoras automaticas", horas_estimadas: 1.0, personas_necesarias: 1 },
      { orden: 10, nombre: "Poner postizos de proa p/HT y pestaña de apoyo de vidrios laterales", horas_estimadas: 10.0, personas_necesarias: 2 },
      { orden: 11, nombre: "Cortar ojos de buey y pegar bandas", horas_estimadas: 10.0, personas_necesarias: 1 },
      { orden: 12, nombre: "Alinear y pegar cabina HT", horas_estimadas: 5.0, personas_necesarias: 1 },
      { orden: 13, nombre: "Laminar cabina HT en Proa", horas_estimadas: 12.0, personas_necesarias: null },
      { orden: 14, nombre: "Ajustar planchada", horas_estimadas: 14.0, personas_necesarias: 2 },
      { orden: 15, nombre: "Poner tinteros", horas_estimadas: 10.0, personas_necesarias: 2 },
      { orden: 16, nombre: "Laminar contratechos y bandas", horas_estimadas: 8.0, personas_necesarias: 1 },
      { orden: 17, nombre: "Pintar cabina de HT", horas_estimadas: 24.0, personas_necesarias: null },
      { orden: 18, nombre: "Poner pieza de plastico de banda, cortar ventana y ojo de buey", horas_estimadas: 8.0, personas_necesarias: 2 },
      { orden: 19, nombre: "Pintar union de cabina HT en Proa", horas_estimadas: 96.0, personas_necesarias: null },
      { orden: 20, nombre: "Colocar tomas de aire de sala de maquinas", horas_estimadas: 6.0, personas_necesarias: 2 },
      { orden: 21, nombre: "Laminar planchada", horas_estimadas: 10.0, personas_necesarias: 1 },
      { orden: 22, nombre: "Cerrar mamparo de sala de maquinas", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 23, nombre: "Presentar Mamparo de Pique", horas_estimadas: 5.0, personas_necesarias: 2 },
      { orden: 24, nombre: "Ajustar escotilla de acceso a sala de maquinas y llevar a repintar", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 25, nombre: "Laminar tomas de aire de sala de maquinas", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 26, nombre: "Pintar planchada", horas_estimadas: 120.0, personas_necesarias: null },
      { orden: 27, nombre: "Pintar piernas de popa (union casco-cubierta)", horas_estimadas: 96.0, personas_necesarias: null },
      { orden: 28, nombre: "Poner tambucho redondo de proa", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 29, nombre: "Ajustar tapa de escalera de planchada y llevar a repintar", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 30, nombre: "Laminar mamparo de pique", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 31, nombre: "Pintar tomas de aire de sala de máquinas", horas_estimadas: 96.0, personas_necesarias: null },
      { orden: 32, nombre: "Ajustar molduras de ventanas de casco", horas_estimadas: 7.0, personas_necesarias: 2 },
      { orden: 33, nombre: "Armar riel y mamparo de puerta corrediza de camarote de popa", horas_estimadas: 14.0, personas_necesarias: 1 },
      { orden: 34, nombre: "Pegar ojos de buey", horas_estimadas: 12.0, personas_necesarias: 2 },
      { orden: 35, nombre: "Colocar piso de Pique", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 36, nombre: "Hacer listonado en mamparo de popa del salon, apoyo de escalera y corte para tablero electrico", horas_estimadas: 10.0, personas_necesarias: 1 },
      { orden: 37, nombre: "Laminar piso de pique y pintar", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 38, nombre: "Hacer bases para cables detras de sillon y debajo de tablero, pintar", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 39, nombre: "Pegar molduras de ventanas de casco", horas_estimadas: 8.0, personas_necesarias: 2 },
      { orden: 40, nombre: "Amurar cajas de salida de aire y calefaccion", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 41, nombre: "Poner rejillas de entrada y salida de aire", horas_estimadas: 1.0, personas_necesarias: 1 },
    ],
  },
  {
    nombre: "Sala de Maquinas",
    orden: 6,
    color: "#f59e0b",
    tareas: [
      { orden: 1, nombre: "Colocar bases para filtros de agua de motor", horas_estimadas: 1.0, personas_necesarias: 1 },
      { orden: 2, nombre: "Completar antirruido de mamparo de sala de maquinas", horas_estimadas: 10.0, personas_necesarias: 1 },
      { orden: 3, nombre: "Poner bases de calefactor y cajas de electricidad", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 4, nombre: "Base para pluma + base para aqualift", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 5, nombre: "Laminar bases de calefactor y elect.", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 6, nombre: "Poliamida hidraulica", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 7, nombre: "Subir tanques de agua", horas_estimadas: 2.0, personas_necesarias: 2 },
      { orden: 8, nombre: "Instalar motores", horas_estimadas: 16.0, personas_necesarias: null },
      { orden: 9, nombre: "Colocar caja de baterias", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 10, nombre: "Poner babero de porton de popa", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 11, nombre: "Colocar pisos de sala de maquinas", horas_estimadas: 5.0, personas_necesarias: 1 },
    ],
  },
  {
    nombre: "Camarote de Proa",
    orden: 7,
    color: "#ec4899",
    tareas: [
      { orden: 1, nombre: "Poner terciado de cama de proa", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 2, nombre: "Ajustar y pegar terciados de laterales de proa", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 3, nombre: "Amurar muebles esquineros de proa", horas_estimadas: 4.0, personas_necesarias: 2 },
      { orden: 4, nombre: "Amurar muebles laterales de proa", horas_estimadas: 10.0, personas_necesarias: 2 },
      { orden: 5, nombre: "Armar frente y lateral de ropero", horas_estimadas: 6.0, personas_necesarias: 2 },
      { orden: 6, nombre: "Ajustar y pegar enchapados de ajuste de muebles de proa", horas_estimadas: 11.0, personas_necesarias: 1 },
      { orden: 7, nombre: "Poner caja fuerte", horas_estimadas: 1.0, personas_necesarias: 1 },
      { orden: 8, nombre: "Armar interior de ropero (techo, base, tapas de inspeccion, tapizmel, barral, puerta, reten)", horas_estimadas: 16.0, personas_necesarias: 1 },
      { orden: 9, nombre: "Ajustar y pegar enchapados de laterales de proa", horas_estimadas: 5.0, personas_necesarias: 1 },
      { orden: 10, nombre: "Amurar cajonera de proa", horas_estimadas: 6.0, personas_necesarias: 1 },
      { orden: 11, nombre: "Hacer listonado de calles de techo Proa", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 12, nombre: "Poner marcos de puertas de camarote y baño de proa", horas_estimadas: 8.0, personas_necesarias: 1 },
      { orden: 13, nombre: "Ajustar tapizados de mamparos de proa y mandar a tapizar", horas_estimadas: 8.0, personas_necesarias: 1 },
      { orden: 14, nombre: "Hacer bandeau de laterales de proa y mandar a tapizar", horas_estimadas: 6.0, personas_necesarias: 1 },
      { orden: 15, nombre: "Ajustar tapizado de pique y mandar a tapizar", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 16, nombre: "Armar puertas de muebles de proa (pistones, bisagras, topetinas, barral de inox.)", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 17, nombre: "Pegar tapizados de techo de proa", horas_estimadas: 5.0, personas_necesarias: 1 },
      { orden: 18, nombre: "Pegar tapizados de mamparos de proa", horas_estimadas: 6.0, personas_necesarias: 1 },
      { orden: 19, nombre: "Ajustar tapizados de calles de proa y mandar a tapizar", horas_estimadas: 5.0, personas_necesarias: 1 },
      { orden: 20, nombre: "Pegar mesas de luz de proa", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 21, nombre: "Pegar tapizmel de cama de proa", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 22, nombre: "Amurar bandeau de cama de proa", horas_estimadas: 1.0, personas_necesarias: 1 },
      { orden: 23, nombre: "Amurar bandeau de laterales de proa", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 24, nombre: "Pegar tapizados de calles de proa", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 25, nombre: "Armar puertas de camarote y baño de proa (bisagras, picaportes, cerraduras)", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 26, nombre: "Poner retenes de puertas de camarote y baño de proa", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 27, nombre: "Colocar tapizado de pique", horas_estimadas: 2.0, personas_necesarias: 1 },
    ],
  },
  {
    nombre: "Baño de Proa",
    orden: 8,
    color: "#06b6d4",
    tareas: [
      { orden: 1, nombre: "Amurar frente de mueble vanitory de baño de proa", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 2, nombre: "Pegar pisos de baño de proa", horas_estimadas: 5.0, personas_necesarias: 1 },
      { orden: 3, nombre: "Engomar junta de piso de baño de proa", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 4, nombre: "Amurar mueble de espejo de baño de proa", horas_estimadas: 5.0, personas_necesarias: 1 },
      { orden: 5, nombre: "Amurar mueble alto de baño de proa", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 6, nombre: "Ajustar y pegar enchapados de ajuste de baño de proa", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 7, nombre: "Armar puertas de muebles altos de baño de proa (pistones, bisagras, topetinas, retenes)", horas_estimadas: 1.0, personas_necesarias: 1 },
      { orden: 8, nombre: "Amurar rejilla de extrator de baño de proa", horas_estimadas: 1.0, personas_necesarias: 1 },
      { orden: 9, nombre: "Armar sistema de mampara corrediza", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 10, nombre: "Armar y colgar mampara redonda de acrilico", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 11, nombre: "Poner perfil \"U\" de mamparas de baño de proa", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 12, nombre: "Cortar y poner acrilicos de mamparas de baño de proa", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 13, nombre: "Pegar mesadas de corian de baño de proa", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 14, nombre: "Poner accesorios de baño de proa", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 15, nombre: "Pegar espejo de mueble de baño de proa", horas_estimadas: 1.0, personas_necesarias: 1 },
      { orden: 16, nombre: "Colocar enjaretado de ducha de baño de proa", horas_estimadas: 1.0, personas_necesarias: 1 },
      { orden: 17, nombre: "Armar interior de mueble vanitory y puerta", horas_estimadas: 1.0, personas_necesarias: 1 },
    ],
  },
  {
    nombre: "Salon",
    orden: 9,
    color: "#a855f7",
    tareas: [
      { orden: 1, nombre: "Amurar mueble de salon", horas_estimadas: 4.0, personas_necesarias: 2 },
      { orden: 2, nombre: "Pegar terciado de respaldo de sillon", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 3, nombre: "Amurar mueble de tablero electrico", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 4, nombre: "Ajustar y pegar enchapado de ajuste de mueble de salon y respaldo", horas_estimadas: 8.0, personas_necesarias: 2 },
      { orden: 5, nombre: "Hacer listonado de calles de techo Salon", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 6, nombre: "Ajustar tapizados de mamparos de salon y mandar a tapizar", horas_estimadas: 8.0, personas_necesarias: 1 },
      { orden: 7, nombre: "Hacer plantilla de zocalo de inoxidable de entrada", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 8, nombre: "Armar puertas de mueble (bisagras, pistones, topetinas y barral de inox)", horas_estimadas: 1.0, personas_necesarias: 1 },
      { orden: 9, nombre: "Pegar tapizados de techo de salon (el del limpiaparabrisas con cinta)", horas_estimadas: 4.0, personas_necesarias: 2 },
      { orden: 10, nombre: "Pegar tapizados de mamparos de salon", horas_estimadas: 8.0, personas_necesarias: 2 },
      { orden: 11, nombre: "Ajustar calles de techo de Salon", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 12, nombre: "Armar soporte de TV de salon", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 13, nombre: "Amurar base de escalera de inox", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 14, nombre: "Armar escalones de madera", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 15, nombre: "Colocar puertas de acrilico de tablero electrico", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 16, nombre: "Colocar posabotellas en mueble de salon", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 17, nombre: "Presentar mesa de comedor y amurar bases de terciado", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 18, nombre: "Pegar calles de techo de Salon", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 19, nombre: "Pegar tapizmel de sillon", horas_estimadas: 7.0, personas_necesarias: 1 },
      { orden: 20, nombre: "Armar sillones", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 21, nombre: "Poner mesa de comedor", horas_estimadas: 1.0, personas_necesarias: 1 },
      { orden: 22, nombre: "Pegar zocalo de entrada de inox", horas_estimadas: 1.0, personas_necesarias: 1 },
      { orden: 23, nombre: "Hacer contencion para subwoofer", horas_estimadas: 8.0, personas_necesarias: 1 },
    ],
  },
  {
    nombre: "Cocina",
    orden: 10,
    color: "#f97316",
    tareas: [
      { orden: 1, nombre: "Amurar mueble alto de cocina", horas_estimadas: 3.0, personas_necesarias: 2 },
      { orden: 2, nombre: "Ajustar y pegar enchapado de ajuste de mueble alto de cocina", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 3, nombre: "Ajustar y pegar enchapados de mamparos de cocina", horas_estimadas: 8.0, personas_necesarias: 2 },
      { orden: 4, nombre: "Colgar puerta corrediza de camarote de popa", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 5, nombre: "Colgar puertas de mueble alto de cocina", horas_estimadas: 1.0, personas_necesarias: 1 },
      { orden: 6, nombre: "Amurar frente de mueble bajomesada de cocina, lateral de cajones", horas_estimadas: 7.0, personas_necesarias: 1 },
      { orden: 7, nombre: "Poner terciado de apoyo de bacha de cocina y listones para mesada", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 8, nombre: "Colocar bacha de cocina", horas_estimadas: 1.0, personas_necesarias: 1 },
      { orden: 9, nombre: "Instalar heladera (hacer sistema de marco)", horas_estimadas: 8.0, personas_necesarias: 1 },
      { orden: 10, nombre: "Armar interior de bajo mesada de cocina (estante y fondos)", horas_estimadas: 5.0, personas_necesarias: 1 },
      { orden: 11, nombre: "Pegar mesada de corian de cocina", horas_estimadas: 4.0, personas_necesarias: 2 },
      { orden: 12, nombre: "Colocar caja de ducto de calefaccion", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 13, nombre: "Instalar anafe", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 14, nombre: "Colgar puertas y cajones de mueble bajomesada de cocina", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 15, nombre: "Colocar herraje de puerta de heladera", horas_estimadas: 1.0, personas_necesarias: 1 },
      { orden: 16, nombre: "Pegar piso de cocina", horas_estimadas: 4.0, personas_necesarias: 2 },
      { orden: 17, nombre: "Instalar microondas", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 18, nombre: "Poner marco de puerta corrediza de Cocina", horas_estimadas: 2.0, personas_necesarias: 1 },
    ],
  },
  {
    nombre: "Camarote de Popa",
    orden: 11,
    color: "#e11d48",
    tareas: [
      { orden: 1, nombre: "Armar riel de puerta corrediza de baño", horas_estimadas: 6.0, personas_necesarias: 1 },
      { orden: 2, nombre: "Hacer caja bajo cama de popa", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 3, nombre: "Hacer cajas de parlantes de camarote de popa", horas_estimadas: 5.0, personas_necesarias: 1 },
      { orden: 4, nombre: "Ajustar caja de tablero electrico, poner listones y hacer cortes para cables", horas_estimadas: 5.0, personas_necesarias: 1 },
      { orden: 5, nombre: "Hacer listonado de calles de techo Popa", horas_estimadas: 5.0, personas_necesarias: 1 },
      { orden: 6, nombre: "Poner marco de puerta corrediza de camarote de popa", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 7, nombre: "Ajustar tapizados de mamparos de popa y mandar a tapizar", horas_estimadas: 10.0, personas_necesarias: 1 },
      { orden: 8, nombre: "Amurar mesa de luz de popa", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 9, nombre: "Colocar bordes de camas de popa", horas_estimadas: 1.0, personas_necesarias: 1 },
      { orden: 10, nombre: "Ajustar calles de tapizados de popa y mandar a tapizar", horas_estimadas: 6.0, personas_necesarias: 1 },
      { orden: 11, nombre: "Pegar tapizados de techo de popa", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 12, nombre: "Poner caja de tablero electrico", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 13, nombre: "Pegar tapizados de mamparos de popa", horas_estimadas: 8.0, personas_necesarias: 1 },
      { orden: 14, nombre: "Ajustar y pegar estante de banda", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 15, nombre: "Ajustar tapizados de respaldos de cama de popa", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 16, nombre: "Amurar cajonera de popa", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 17, nombre: "Pegar tapizmel de camas de popa", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 18, nombre: "Pegar calles de tapizados de popa", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 19, nombre: "Pegar respaldos de camas de popa", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 20, nombre: "Amurar bandeau de camas de popa", horas_estimadas: 1.0, personas_necesarias: 1 },
    ],
  },
  {
    nombre: "Baño de Popa",
    orden: 12,
    color: "#0891b2",
    tareas: [
      { orden: 1, nombre: "Pegar pisos de baño de popa (proteger)", horas_estimadas: 7.0, personas_necesarias: 2 },
      { orden: 2, nombre: "Engomar pisos de baño de popa", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 3, nombre: "Poner mamparas de baño de popa y engomar", horas_estimadas: 16.0, personas_necesarias: 2 },
      { orden: 4, nombre: "Amurar muebles superiores de baño de popa", horas_estimadas: 8.0, personas_necesarias: 1 },
      { orden: 5, nombre: "Amurar mueble vanitory de baño de popa", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 6, nombre: "Pegar mesadas de corian de baño de popa", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 7, nombre: "Amurar estante de plastico de ducha de popa", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 8, nombre: "Ajustar y pegar marcos laterales de puerta de baño de popa", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 9, nombre: "Presentar puerta corrediza de baño de popa y llevar a pegar espejo", horas_estimadas: 7.0, personas_necesarias: 1 },
      { orden: 10, nombre: "Armar puertas de muebles de baño de popa", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 11, nombre: "Pegar espejo de mueble de baño de popa", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 12, nombre: "Poner rejilla de extractor de baño de popa", horas_estimadas: 1.0, personas_necesarias: 1 },
      { orden: 13, nombre: "Armar barrales de inoxidable de popa", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 14, nombre: "Poner accesorios de baño de popa", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 15, nombre: "Colgar puerta corrediza de baño de popa y poner tirador", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 16, nombre: "Pegar marco superior de puerta de baño de popa", horas_estimadas: 2.0, personas_necesarias: 1 },
    ],
  },
  {
    nombre: "Interiores",
    orden: 13,
    color: "#6366f1",
    tareas: [
      { orden: 1, nombre: "Etapa 2 de Sanitarios", horas_estimadas: 24.0, personas_necesarias: 2 },
      { orden: 2, nombre: "Etapa 3 de Sanitarios", horas_estimadas: 8.0, personas_necesarias: 2 },
      { orden: 3, nombre: "Pintar pisos y tapas de inspeccion", horas_estimadas: 6.0, personas_necesarias: 1 },
      { orden: 4, nombre: "Poner levantapisos de sentina", horas_estimadas: 1.0, personas_necesarias: 1 },
      { orden: 5, nombre: "Hacer tapacables de TV y mandar a tapizar", horas_estimadas: 1.0, personas_necesarias: 1 },
      { orden: 6, nombre: "Poner tapacables de TV", horas_estimadas: 1.0, personas_necesarias: 1 },
      { orden: 7, nombre: "Electricidad 1 (ver notas)", horas_estimadas: 32.0, personas_necesarias: 2 },
      { orden: 8, nombre: "Electricidad 2 (luces de techo, tomas, teclas, luces de cortesia, inodoros)", horas_estimadas: 40.0, personas_necesarias: 2 },
      { orden: 9, nombre: "Conectar tablero electrico", horas_estimadas: 16.0, personas_necesarias: 1 },
      { orden: 10, nombre: "Electricidad 3 (instalar TVs, decos, estereos, ductos de aire)", horas_estimadas: 16.0, personas_necesarias: 2 },
      { orden: 11, nombre: "Electricidad 4 (instrumenal de consola, arco radar, parlantes de proa)", horas_estimadas: 16.0, personas_necesarias: 2 },
    ],
  },
  {
    nombre: "Exterior",
    orden: 14,
    color: "#84cc16",
    tareas: [
      { orden: 1, nombre: "Poner catalina y trabacadena", horas_estimadas: 3.0, personas_necesarias: 2 },
      { orden: 2, nombre: "Armar cadena, punto fijo, grillete, etc.", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 3, nombre: "Poner sapito de desagote de ancla", horas_estimadas: 1.0, personas_necesarias: 1 },
      { orden: 4, nombre: "Colocar herraje de faro de proa", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 5, nombre: "Pegar ventanas de casco y techo de salon", horas_estimadas: 8.0, personas_necesarias: 2 },
      { orden: 6, nombre: "Ajustar tapas de tomas de aire y poner varillas roscadas", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 7, nombre: "Ajustar porton de popa: cortes aspiración, tacos de madera", horas_estimadas: 8.0, personas_necesarias: 1 },
      { orden: 8, nombre: "Colocar tapas de tomas de aire", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 9, nombre: "Instalar puerta corrediza de acceso a interiores", horas_estimadas: 16.0, personas_necesarias: null },
      { orden: 10, nombre: "Ajustar consola, poner fondo y llevar a repintar", horas_estimadas: 7.0, personas_necesarias: 2 },
      { orden: 11, nombre: "Poner escalera de planchada y presentar tapa", horas_estimadas: 6.0, personas_necesarias: 1 },
      { orden: 12, nombre: "Pintar fondo", horas_estimadas: 32.0, personas_necesarias: null },
      { orden: 13, nombre: "Pintar bandas", horas_estimadas: 40.0, personas_necesarias: null },
      { orden: 14, nombre: "Armar sistema de techo corredizo", horas_estimadas: 6.0, personas_necesarias: 2 },
      { orden: 15, nombre: "Poner tapas de inspeccion tapizadas de laterales", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 16, nombre: "Colocar pasamanos de laterales de HT", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 17, nombre: "Armar mueble de cockpit y conservadora", horas_estimadas: 6.0, personas_necesarias: null },
      { orden: 18, nombre: "Armar interior de mueble de cockpit", horas_estimadas: 6.0, personas_necesarias: 1 },
      { orden: 19, nombre: "Instalar fabricadora de hielo", horas_estimadas: 4.0, personas_necesarias: null },
      { orden: 20, nombre: "Armar escotilla de acceso a sala de maquinas (cierre, bisagras, piston, antirruido, burlete)", horas_estimadas: 5.0, personas_necesarias: 1 },
      { orden: 21, nombre: "Pegar cucharas de plastico de salida de extractor", horas_estimadas: 1.0, personas_necesarias: 1 },
      { orden: 22, nombre: "Colocar pasamanos de popa", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 23, nombre: "Pegar teka", horas_estimadas: 32.0, personas_necesarias: 2 },
      { orden: 24, nombre: "Poner bisagras y levantapiso de tapa de escalera de planchada", horas_estimadas: 3.0, personas_necesarias: null },
      { orden: 25, nombre: "Pegar ventanas de cubierta y parabrisas", horas_estimadas: 6.0, personas_necesarias: 2 },
      { orden: 26, nombre: "Engomar juntas de ventanas de todo el barco", horas_estimadas: 22.0, personas_necesarias: 1 },
      { orden: 27, nombre: "Armar consola", horas_estimadas: 5.0, personas_necesarias: 1 },
      { orden: 28, nombre: "Pegar moldura de consola", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 29, nombre: "Colocar pie de consola", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 30, nombre: "Colocar tapizados de contratecho HT", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 31, nombre: "Poner botazo", horas_estimadas: 12.0, personas_necesarias: 2 },
      { orden: 32, nombre: "Pegar mesada de corian y armar tapa", horas_estimadas: 6.0, personas_necesarias: 1 },
      { orden: 33, nombre: "Armar puertas de mueble", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 34, nombre: "Poner posavasos de acrilico de mueble de cockpit", horas_estimadas: 1.0, personas_necesarias: 1 },
      { orden: 35, nombre: "Armar puerta de cockpit", horas_estimadas: 5.0, personas_necesarias: 1 },
      { orden: 36, nombre: "Armar porton de popa: bacha, antirruido", horas_estimadas: 7.0, personas_necesarias: 2 },
      { orden: 37, nombre: "Colocar baranda de porton de popa", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 38, nombre: "Subir porton de popa", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 39, nombre: "Poner parrilla de popa", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 40, nombre: "Armar tapa de parrilla de popa (pistones, bisagras, topetinas, contrachapa)", horas_estimadas: 8.0, personas_necesarias: 1 },
      { orden: 41, nombre: "Colocar baranda de tapa de parrilla", horas_estimadas: 2.0, personas_necesarias: 1 },
      { orden: 42, nombre: "Poner posavasos de acrilico de proa", horas_estimadas: 3.0, personas_necesarias: 1 },
      { orden: 43, nombre: "Colocar barandas de solarium", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 44, nombre: "Armar mesa de cockpit", horas_estimadas: 6.0, personas_necesarias: 1 },
      { orden: 45, nombre: "Amurar caja de selectoras y colocar puerta de acrilico", horas_estimadas: 4.0, personas_necesarias: 1 },
      { orden: 46, nombre: "Poner cable guardamancebo", horas_estimadas: 1.0, personas_necesarias: 1 },
      { orden: 47, nombre: "Armar sillones y colchonetas de exterior", horas_estimadas: 5.0, personas_necesarias: 1 },
      { orden: 48, nombre: "Poner posavasos de acrilico de sillon de cockpit", horas_estimadas: 3.0, personas_necesarias: 1 },
    ],
  },
];

export const PLANTILLA_K52 = [
  {
    nombre: "Preparación General",
    orden: 1,
    color: "#64748b",
    tareas: [
      { orden: 1, nombre: "DESMOLDE DE CASCO, NIVELACION DE CASCO", horas_estimadas: 40.0, personas_necesarias: null },
      { orden: 2, nombre: "PREPARACION DE TIRANTERIA DE INTERIORES", horas_estimadas: 160.0, personas_necesarias: null },
      { orden: 3, nombre: "PREPARACION DE TIRANTERIA DE SALA DE MAQUINAS", horas_estimadas: 80.0, personas_necesarias: null },
      { orden: 4, nombre: "DESMOLDE DE CUBIERTA", horas_estimadas: 120.0, personas_necesarias: null },
      { orden: 5, nombre: "DESMOLDE DE LINERS", horas_estimadas: 120.0, personas_necesarias: null },
      { orden: 6, nombre: "DESMOLDE DE TECHOS DE BAÑO", horas_estimadas: 120.0, personas_necesarias: null },
      { orden: 7, nombre: "DESMOLDE DE BAÑOS", horas_estimadas: 120.0, personas_necesarias: null },
      { orden: 8, nombre: "PINTADO DE SENTINA", horas_estimadas: 120.0, personas_necesarias: null },
      { orden: 9, nombre: "ETAPA 1, SANITARIOS", horas_estimadas: 120.0, personas_necesarias: null },
      { orden: 10, nombre: "ETAPA 1, ELECTRICIDAD", horas_estimadas: 120.0, personas_necesarias: null },
      { orden: 11, nombre: "SUBIR LINERS DE INTERIORES, BAÑOS Y TECHOS DE BAÑO", horas_estimadas: 120.0, personas_necesarias: null },
      { orden: 12, nombre: "DESMOLDE DE CUBIERTA, RECOCIDO DE CASCO Y CUBIERTA", horas_estimadas: 160.0, personas_necesarias: null },
    ],
  },
  {
    nombre: "Camarote Principal",
    orden: 2,
    color: "#ec4899",
    tareas: [
      { orden: 1, nombre: "TIRANTERIA DE TECHOS DE CAMAROTE PRINCIPAL", horas_estimadas: 160.0, personas_necesarias: null },
      { orden: 2, nombre: "ELECTRICIDAD, ETAPA 2", horas_estimadas: 200.0, personas_necesarias: null },
      { orden: 3, nombre: "FORRADO DE TECHOS", horas_estimadas: 200.0, personas_necesarias: null },
      { orden: 4, nombre: "AJUSTE DE MUEBLE DE VENTANA DE BABOR", horas_estimadas: 240.0, personas_necesarias: null },
      { orden: 5, nombre: "PREPARAR MAMPAROS TAPIZADOS", horas_estimadas: 360.0, personas_necesarias: null },
      { orden: 6, nombre: "PREPARAR TECHOS TAPIZADOS", horas_estimadas: 440.0, personas_necesarias: null },
      { orden: 7, nombre: "ETAPA 3, ELECTRICIDAD (CONECTAR LUCES, BASTIDORES Y TOMAS)", horas_estimadas: 480.0, personas_necesarias: null },
      { orden: 8, nombre: "INSTALAR MARCOS Y PUERTAS DE CAMAROTE DE POPA", horas_estimadas: 720.0, personas_necesarias: null },
      { orden: 9, nombre: "INSTALAR ALFOMBRAS", horas_estimadas: 720.0, personas_necesarias: null },
      { orden: 10, nombre: "INSTALAR CORTINAS", horas_estimadas: 720.0, personas_necesarias: null },
      { orden: 11, nombre: "ETAPA 4, ELECTRICIDAD (ARMADO DE TABLERO 12 Y 220V)", horas_estimadas: 1040.0, personas_necesarias: null },
      { orden: 12, nombre: "ETAPA 5, ELECTRICIDAD (PRUEBA GENERAL DE APARATOS ELECTRICOS)", horas_estimadas: 1040.0, personas_necesarias: null },
    ],
  },
  {
    nombre: "Salón",
    orden: 3,
    color: "#a855f7",
    tareas: [
      { orden: 1, nombre: "TIRANTERIA DE TECHOS DE SALON", horas_estimadas: 160.0, personas_necesarias: null },
      { orden: 2, nombre: "ELECTRICIDAD, ETAPA 2", horas_estimadas: 200.0, personas_necesarias: null },
      { orden: 3, nombre: "FORRADO DE TECHOS", horas_estimadas: 200.0, personas_necesarias: null },
      { orden: 4, nombre: "AJUSTE DE MUEBLE DE VENTANA DE BABOR", horas_estimadas: 240.0, personas_necesarias: null },
      { orden: 5, nombre: "PREPARAR PLANTILLAS DE MARMOLES", horas_estimadas: 360.0, personas_necesarias: null },
      { orden: 6, nombre: "INSTALAR PISO DE PVC", horas_estimadas: 400.0, personas_necesarias: null },
      { orden: 7, nombre: "PREPARAR MAMPAROS TAPIZADOS", horas_estimadas: 440.0, personas_necesarias: null },
      { orden: 8, nombre: "PREPARAR TECHOS TAPIZADOS", horas_estimadas: 520.0, personas_necesarias: null },
      { orden: 9, nombre: "ETAPA 3, ELECTRICIDAD (CONECTAR LUCES, BASTIDORES Y TOMAS)", horas_estimadas: 600.0, personas_necesarias: null },
      { orden: 10, nombre: "INSTALAR MARCOS Y PUERTAS DE SALON", horas_estimadas: 720.0, personas_necesarias: null },
      { orden: 11, nombre: "INSTALAR CORTINAS", horas_estimadas: 720.0, personas_necesarias: null },
      { orden: 12, nombre: "ETAPA 2 SANITARIOS, INSTALAR Y CONECTAR GRIFERIAS Y BACHAS", horas_estimadas: 520.0, personas_necesarias: null },
      { orden: 13, nombre: "ETAPA 4, ELECTRICIDAD (ARMADO DE TABLERO 12 Y 220V)", horas_estimadas: 1040.0, personas_necesarias: null },
      { orden: 14, nombre: "ETAPA 5, ELECTRICIDAD (PRUEBA GENERAL DE APARATOS ELECTRICOS)", horas_estimadas: 1040.0, personas_necesarias: null },
    ],
  },
  {
    nombre: "Camarote de Proa",
    orden: 4,
    color: "#f97316",
    tareas: [
      { orden: 1, nombre: "TIRANTERIA DE TECHOS DE CAMAROTE DE PROA", horas_estimadas: 160.0, personas_necesarias: null },
      { orden: 2, nombre: "ELECTRICIDAD, ETAPA 2", horas_estimadas: 200.0, personas_necesarias: null },
      { orden: 3, nombre: "FORRADO DE TECHOS", horas_estimadas: 200.0, personas_necesarias: null },
      { orden: 4, nombre: "AJUSTE DE MUEBLE DE VENTANA DE BABOR", horas_estimadas: 240.0, personas_necesarias: null },
      { orden: 5, nombre: "PREPARAR MAMPAROS TAPIZADOS", horas_estimadas: 360.0, personas_necesarias: null },
      { orden: 6, nombre: "PREPARAR TECHOS TAPIZADOS", horas_estimadas: 440.0, personas_necesarias: null },
      { orden: 7, nombre: "ETAPA 3, ELECTRICIDAD (CONECTAR LUCES, BASTIDORES Y TOMAS)", horas_estimadas: 480.0, personas_necesarias: null },
      { orden: 8, nombre: "INSTALAR MARCOS Y PUERTAS DE CAMAROTE DE POPA", horas_estimadas: 720.0, personas_necesarias: null },
      { orden: 9, nombre: "INSTALAR ALFOMBRAS", horas_estimadas: 720.0, personas_necesarias: null },
      { orden: 10, nombre: "INSTALAR CORTINAS", horas_estimadas: 720.0, personas_necesarias: null },
      { orden: 11, nombre: "ETAPA 4, ELECTRICIDAD (ARMADO DE TABLERO 12 Y 220V)", horas_estimadas: 1040.0, personas_necesarias: null },
      { orden: 12, nombre: "ETAPA 5, ELECTRICIDAD (PRUEBA GENERAL DE APARATOS ELECTRICOS)", horas_estimadas: 1040.0, personas_necesarias: null },
    ],
  },
  {
    nombre: "Baño de Proa",
    orden: 5,
    color: "#06b6d4",
    tareas: [
      { orden: 1, nombre: "HACER MAMPARO DIVISIOR DE BAÑO", horas_estimadas: 160.0, personas_necesarias: null },
      { orden: 2, nombre: "INSTALAR CENEFA SEGÚN PLANTILLA Y AJUSTAR CONTRA EL MAMPARO", horas_estimadas: 400.0, personas_necesarias: null },
      { orden: 3, nombre: "INSTALAR PISO DE PVC", horas_estimadas: 440.0, personas_necesarias: null },
      { orden: 4, nombre: "INSTALAR ALACENA DE BAÑO", horas_estimadas: 480.0, personas_necesarias: null },
      { orden: 5, nombre: "HACER PLANTILLAS DE MARMOL DE BAJO MESADA", horas_estimadas: 520.0, personas_necesarias: null },
      { orden: 6, nombre: "INSTALAR GRIFERIAS Y DUCHA", horas_estimadas: 680.0, personas_necesarias: null },
      { orden: 7, nombre: "ELECTRICIDAD, ETAPA 1 Y 2 (LUCES, VASTIDORES, CONTROL DE ELECTROVALVULA)", horas_estimadas: 720.0, personas_necesarias: null },
      { orden: 8, nombre: "INSTALAR MARCOS DE PUERTA", horas_estimadas: 720.0, personas_necesarias: null },
      { orden: 9, nombre: "HACER PRUEBAS SANITARIAS", horas_estimadas: 1040.0, personas_necesarias: null },
    ],
  },
  {
    nombre: "Baño de Popa",
    orden: 6,
    color: "#0891b2",
    tareas: [
      { orden: 1, nombre: "HACER MAMPARO DIVISIOR DE BAÑO", horas_estimadas: 160.0, personas_necesarias: null },
      { orden: 2, nombre: "INSTALAR CENEFA SEGÚN PLANTILLA Y AJUSTAR CONTRA EL MAMPARO", horas_estimadas: 400.0, personas_necesarias: null },
      { orden: 3, nombre: "INSTALAR PISO DE PVC", horas_estimadas: 440.0, personas_necesarias: null },
      { orden: 4, nombre: "INSTALAR ALACENA DE BAÑO", horas_estimadas: 480.0, personas_necesarias: null },
      { orden: 5, nombre: "HACER PLANTILLAS DE MARMOL DE BAJO MESADA", horas_estimadas: 520.0, personas_necesarias: null },
      { orden: 6, nombre: "INSTALAR GRIFERIAS Y DUCHA", horas_estimadas: 680.0, personas_necesarias: null },
      { orden: 7, nombre: "ELECTRICIDAD, ETAPA 1 Y 2 (LUCES, VASTIDORES, CONTROL DE ELECTROVALVULA)", horas_estimadas: 720.0, personas_necesarias: null },
      { orden: 8, nombre: "INSTALAR MARCOS DE PUERTA", horas_estimadas: 720.0, personas_necesarias: null },
      { orden: 9, nombre: "HACER PRUEBAS SANITARIAS", horas_estimadas: 1040.0, personas_necesarias: null },
    ],
  },
  {
    nombre: "Terminaciones Interiores",
    orden: 7,
    color: "#6366f1",
    tareas: [
      { orden: 1, nombre: "INSTALAR CORTINAS", horas_estimadas: 720.0, personas_necesarias: null },
    ],
  },
  {
    nombre: "Cubierta y Cabina",
    orden: 8,
    color: "#0ea5e9",
    tareas: [
      { orden: 1, nombre: "INSTALAR TINTEROS DE CUBIERTA", horas_estimadas: 240.0, personas_necesarias: null },
      { orden: 2, nombre: "AJUSTAR TOMA DE AIRE", horas_estimadas: 400.0, personas_necesarias: null },
      { orden: 3, nombre: "AJUSTAR MUEBLE DE COCKPIT", horas_estimadas: 440.0, personas_necesarias: null },
      { orden: 4, nombre: "INSTALAR HERRAJES + GRILONES + ACRILICO DE PUERTA CORREDIZA", horas_estimadas: 480.0, personas_necesarias: null },
      { orden: 5, nombre: "INSTALAR FLEJE METALICO + LISTON DE MADERA DE PUERTA CORREDIZA", horas_estimadas: 480.0, personas_necesarias: null },
      { orden: 6, nombre: "AJUSTAR SOBRE DE PUERTA CORREDIZA", horas_estimadas: 480.0, personas_necesarias: null },
      { orden: 7, nombre: "AJUSTAR CONSOLA DE PUERTA CORREDIZA", horas_estimadas: 480.0, personas_necesarias: null },
      { orden: 8, nombre: "IZAR CABINA, AJUSTAR, BAJAR Y LLEVAR A PINTURA", horas_estimadas: 240.0, personas_necesarias: null },
      { orden: 9, nombre: "HACER PLANTILLAS DE MARMOL DE MUEBLE DE COCKPIT", horas_estimadas: 400.0, personas_necesarias: null },
      { orden: 10, nombre: "INSTALAR CONSOLA", horas_estimadas: 720.0, personas_necesarias: null },
      { orden: 11, nombre: "INSTALAR ACRILICOS E INSTRUMENTAL", horas_estimadas: 720.0, personas_necesarias: null },
      { orden: 12, nombre: "INSTALAR CABINA", horas_estimadas: 800.0, personas_necesarias: null },
      { orden: 13, nombre: "INSTALAR CERRAMIENTOS DE CABINA", horas_estimadas: 960.0, personas_necesarias: null },
      { orden: 14, nombre: "INSTALAR BARANDA PERIMETRAL", horas_estimadas: 960.0, personas_necesarias: null },
      { orden: 15, nombre: "INSTALAR TECA DE COCKPIT Y ESCALONES", horas_estimadas: 800.0, personas_necesarias: null },
    ],
  },
  {
    nombre: "Sala de Máquinas",
    orden: 9,
    color: "#f59e0b",
    tareas: [
      { orden: 1, nombre: "HACER BASES DE CASCO, TIMONES, TANQUES Y SOPORTES DE TANQUES. HACER BASES DE CAJAS ROCKER ELECTRICAS Y BASES DE SEPARADOR DE AGUAS.", horas_estimadas: 160.0, personas_necesarias: null },
      { orden: 2, nombre: "CERRAR ESPEJO, SEGÚN CORRESPONDA PLANCHADA TENDERLIFT O NO.", horas_estimadas: 200.0, personas_necesarias: null },
      { orden: 3, nombre: "HACER PISOS DE SALA DE MAQUINAS Y SUS RESPECTIVAS TAPAS DE INSPECCION", horas_estimadas: 240.0, personas_necesarias: null },
      { orden: 4, nombre: "MANDAR A LAMINAR Y PINTAR PISOS DE SALA DE MAQUINAS", horas_estimadas: 240.0, personas_necesarias: null },
      { orden: 5, nombre: "PINTAR SALA DE MAQUINA", horas_estimadas: 280.0, personas_necesarias: null },
      { orden: 6, nombre: "ETAPA 2 DE ELECTRICIDAD DE SALA DE MAQINAS, CABLECANALES Y DISTRIBUCIONES GENERALES. CAJAS ROCKER Y LLAVES BLUE SEA, VICTRON ENERGY, ETC", horas_estimadas: 320.0, personas_necesarias: null },
      { orden: 7, nombre: "ETAPA 2 DE SANITARIOS DE SALA DE MAQUINAS, PASACASCOS", horas_estimadas: 360.0, personas_necesarias: null },
      { orden: 8, nombre: "ETAPA 1 DE MECANICA, AJUSTE DE CHASIS DE MOTOR", horas_estimadas: 400.0, personas_necesarias: null },
      { orden: 9, nombre: "ETAPA 2 DE MECANICA, AGUJEROS EN EL CASCO", horas_estimadas: 480.0, personas_necesarias: null },
      { orden: 10, nombre: "ETAPA 3 DE MECANICA, TRAZADO DE LINEA DE EJE", horas_estimadas: 720.0, personas_necesarias: null },
      { orden: 11, nombre: "ETAPA 4 DE MECANICA, PATAS DE GALLO Y MOTORES", horas_estimadas: 840.0, personas_necesarias: null },
      { orden: 12, nombre: "ETAPA 5 DE MECANICA, CHASIS DE MOTORES", horas_estimadas: 960.0, personas_necesarias: null },
      { orden: 13, nombre: "ETAPA 6 DE MECANICA, ARMADO DE ESCAPES, SISTEMA COMBUSTIBLE Y GRUPO ELECTROGENO", horas_estimadas: 1040.0, personas_necesarias: null },
      { orden: 14, nombre: "ETAPA 3 DE ELECTRICIDAD, ARMADO DE BANCOS DE BATERIAS, CONEXIÓN DE MOTORES, SENSORES DE NIVEL DE COMBUSTIBLE, ETC", horas_estimadas: 1040.0, personas_necesarias: null },
      { orden: 15, nombre: "ETAPA 3 DE SANITARIOS, CONEXIÓN DE SISTEMA DE AGUA POTABLE", horas_estimadas: 1040.0, personas_necesarias: null },
      { orden: 16, nombre: "ETAPA 4 DE SANITARIOS, PRUEBAS HIDRAULICAS", horas_estimadas: 1080.0, personas_necesarias: null },
      { orden: 17, nombre: "PRESENTADO DE BAUL, PUESTA A NIVEL", horas_estimadas: 1120.0, personas_necesarias: null },
      { orden: 18, nombre: "INSTALAR TECA DE PLANCHADA", horas_estimadas: 1120.0, personas_necesarias: null },
    ],
  },
];